### ISSUE TITLE
Make flag for releasing all results accessible from user admin interface

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#105]
The flag was added in 622885915681f6cf8fe93b3c08c52bb526d5b346 and can only be edited from the Django admin interface.

It should be brought out to the user admin interface, similarly to (and probably in the same place as) #35.

**Comment by philipbelesky** [comment]
"Release all" should probably become a tournament preference rather than a property of a `Tournament`. Should be a pretty easy switch.
