### ISSUE TITLE
Add adjudicator-adjudicator conflicts

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#108]
Including trainee-adjudicator conflicts.

**Comment by philipbelesky** [comment]
Was this a priority for this year's Australs? Am kind of surprised this hasn't caused issues previously, would be keen to try and get it going before Easters

**Comment by czlee** [comment]
I guess it could be. Probably should be.

**Comment by czlee** [comment]
As an aside, incorporating this into the adjudicator allocation algorithm is probably highly non-trivial, so this issue should probably be closed when there's room for it in the database and it's highlighted in the manual allocation UI, and a new issue opened for the algorithm.

**Comment by philipbelesky** [comment]
Being worked on in feature/adj-adj-conflicts

**Comment by philipbelesky** [comment]
With regards to working this into the importer, am I correct in thinking that import_adjudicators is iterative and that adj-adj conflicts cannot be create here because the required objects may not have been created  yet?

**Comment by czlee** [comment]
That's correct. I thought about it at the time and don't have a good
solution to this... Either we could make _import much more complicated, or
just insist that adj-adj conflicts are in their own file.

**Comment by philipbelesky** [comment]
Yea, there's usually not many so leaving them to be manually entered shouldn't be a problem

**Comment by czlee** [comment]
It wouldn't be too hard to write another import function dedicated to adj-adj conflicts if they're in a separate file, but I agree that it's probably low priority.

**Comment by philipbelesky** [comment]
Closed with #185
