### ISSUE TITLE
When there is only one break category, just use the break index page to show the break

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#120]
Relates to #119.

**Comment by czlee** [comment]
No need for Australs 2015, there is definitely more than one break category there

**Comment by philipbelesky** [comment]
I'm not sure if this is for the admin break index or the public one. If the latter the break index doesn't exist anymore; if the former then I don't think its necessary.

**Comment by czlee** [comment]
It's for the public one. The idea was that when there's only one break, there shouldn't be a need to specify that it's the "open break" or to put it at break/teams/open rather than just break/teams. But I agree that if there's no break index page then this isn't as important and is probably more hassle than it's worth.
