### ISSUE TITLE
Add ability to edit breaking adjudicators

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#122]
Breaking adjudicators page was implemented in 3b0e52d45ede6f9a273b29754a5d303008ba2559, but there is currently no mechanism for identifying breaking adjudicators other than by going into the Django admin interface. There should be some sort of page allowing the identification of breaking adjudicators (probably not checkboxes, some sort of list might be better) in the normal admin interface.

**Comment by philipbelesky** [comment]
Up in 61297cf38bf50df690ee1068a56be3890d5f57c5. Essentially a series of checkboxes for each adj on the Feedback page seemed the easiest way to go here. Unclear how a list would be easier (is this a drag an drop list?) but feel free to reopen if you want that added in.

**Comment by czlee** [comment]
Oh, I guess I was thinking one of those drag-and-drop lists, so that adj cores can just see their list of breaking adjudicators. I'm not really fussed about it though. Checkboxes are fine unless/until we get feedback to the contrary.
