### ISSUE TITLE
Rooms without venues show "None" in edit screen, should be blank cell

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#124]

**Comment by czlee** [comment]
@philipbelesky was the effect of fb71a19523ecce1bfbddfca3960421f3e910b263 to fix this?

**Comment by philipbelesky** [comment]
Looks so, although I don't recall what the intent was here. Possibly to allow debates and/or the draw to go ahead without rooms being set?

**Comment by czlee** [comment]
It was just a UI thing, it used to show a drag-and-drop thing with "None" written in it for rooms that didn't have venues.

**Comment by czlee** [comment]
Like it didn't come up in practice unless you manually assembled a draw and forgot to assign venues.

**Comment by czlee** [comment]
Pretty sure this is fixed now.
