### ISSUE TITLE
Emoji assignments break for rounds where not all teams are debating

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#128]
Presumably this is a side effect of the technique used to ensure that a bunch of high team IDs (arising from deleting and re-adding teams multiple times) don't cause the system to run out of emoji. I think the effect is that the first emoji, :poop:, is always there for the lowest-numbered team *on the draw for that round* (as opposed to in the tournament), and then other emoji are just numbered from whatever that number is.

So for example, compare:
http://tab.australs2014.com/t/australs2014/results/round/12/
to:
http://tab.australs2014.com/t/australs2014/results/round/8/

**Comment by philipbelesky** [comment]
As of 992f57e17de9e784c0c284486573a1667a98e119 Emoji now reference an Emoji ID field (assigned on input) or their team ID (as a fall back) so things should be more consistent.
