### ISSUE TITLE
Investigate moving intensive tasks to asynchronous processes

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#130]
Candidates:
* Adjudicator allocation
* Draw generation
* Team/speaker/reply standings generation

These can take several seconds and hold up everything else in the queue, which can cause some requests to time out. On Heroku, this causes [H12 errors](https://devcenter.heroku.com/articles/error-codes#h12-request-timeout).

Concerns:
* How will it work with Heroku?
* Will it be handled in a sufficiently generic way, that it won't be tied to Heroku?

**Comment by philipbelesky** [comment]
Removing the milestone as performance improvements would seem to make this less of a necessity.

**Comment by czlee** [comment]
Yeah, we haven't seen this in sufficiently long that I'm no longer concerned about it, really.

**Comment by tienne-B** [comment]
Can this be merged (is that a thing in Github) with #590? They seem to be about the same thing.

**Comment by philipbelesky** [comment]
@tienne-B Yea they are the same thing just created a good year or two apart. Given this has been closed we can consider it superceded by #590
