### ISSUE TITLE
Group the config settings and explain them better

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#139]
There are too many config settings now, they need to be grouped for usability and clarity. The interface will probably need to be adjusted to allow longer help strings, what they're used for, *etc.*

See also #113.

**Comment by czlee** [comment]
Requirements:

Specification of options
---------------------------------
* Should be in code somewhere, either at the bottom of config.py or (probably) in its own file.
* Should specify:
    * key
    * type - int, str, choice, float, bool
    * default value
    * short description ("help")
    * long description ("explanation")
* The order of specification in the options should imply an order in the config settings UI
* bool options should specify whether "Yes/No", "True/False", "On/Off", "Enabled/Disabled"...

Interface with database
---------------------------------
* Should be stored in a table, both keys and values as text
* Each config object should provide methods to convert between "real" format and "database" format

User interface (config pages)
----------------------------------------
* Config module should automatically provide the entire form, using only the option specifications
* (Implicitly, each config object should automatically provide a widget)
* Settings should be grouped by category of some sort

Accessing options from source code
--------------------------------------------------
* There should be a global means of retrieving the config, and config value, for a particular key
* It should always return value in "real" format
* No means of dynamically setting anything - should be modified through UI only

Public pages
------------------
See #113.
* If it's marked as a public page option, it should be automatically imported into config_processors.py, and automatically added to the relevant menus.

**Comment by philipbelesky** [comment]
Quick extra thoughts:

- A [tabbed interface](http://getbootstrap.com/javascript/#tabs), where each tab is a 'group' of related settings is probably the best and easiest way of divvying up the UI
- It would be nice to have the ability to set a 'standard' set of defaults all at once. IE it would automatically set all the defaults for Australs, Joynt, etc. Ideally the very first tab would have a series of radio buttons, one for each of these default. Javascript could set the relevant options in the other tabs. This would require keeping a list of each format's defaults, but I don't think they would be especially onerous given they are rules that rarely change

**Comment by philipbelesky** [comment]
Might be of use: https://github.com/jezdez/django-appconf

**Comment by czlee** [comment]
Added config dependencies to list of requirements. For example, "show all results" only makes sense if "public results" is enabled.

**Comment by czlee** [comment]
Additional requirement: It should provide an efficient means of retrieving multiple settings in one go, i.e., one database hit.

**Comment by philipbelesky** [comment]
Random thought: when this restructure goes through it would be advantageous to have present configs; ie "Au Easters", "NZ Easters", "Australs", etc.

Until then we could potentially make pre-built ```config.csv```s or add explicit settings lists to the documentation.

**Comment by philipbelesky** [comment]
Note: this is ongoing on ```config-refactor-dynamic```. Given how deeply embedded the config options are across the code this will need some extensive testing when completed.

Did you have thoughts on how to handle presets data? With a small enough subset for each style they shouldn't be too difficult to maintain. Perhaps just simple key/dictionary ```.py``` files that live in a special folder in ```data```?

**Comment by czlee** [comment]
Yeah, I think that would be easiest to maintain. The only thing is I suspect it will end up making more sense for it to be a class than a dict, but that's minor, all things considered.

**Comment by philipbelesky** [comment]
[ ] Complete deprecations for BaseScoreField
[ ] Complete deprecations for OPTIONS_TO_CONFIG_MAPPING
[ ] Complete deprecations for public_optional_tournament_view
[ ] Fix tests - they don't seem to be able to access preferences
[ ] Create presets for major styles
[ ] Check config presets against constitutional rules
[ ] Create a choice field
[ ] Figure out how to control field order in the UI
[ ] Figure out how to maintain compatability with the importer's ability to read options.csvs

**Comment by philipbelesky** [comment]
[ ] Look at integrating these presets into the documentation (docstrings/something that will display properties?); it would be great to have a resource that precisely outlines for the rules for major styles

**Comment by philipbelesky** [comment]
So at present this is functional, I've done some basic manual tests to check/fix bugs, do you mind if I merge into develop? WADL will be deploying from develop this year and this will make the setup much easier, and also a chance to find bugs in a less pressured environment than a tournament. The NUJSPD tournament is using master, so this shouldn't affect anyone.

**Comment by czlee** [comment]
Merge away :smiley:
