### ISSUE TITLE
Investigate upgrading to Django 1.7

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#142]
1.7 has been released, with a key featuring being a built in database migration system. Ditching South may make installation/setup/development easier and/or mean that upgrades to future versions of Django would be easier. Or not — I've yet to look into the new system in depth.

**Comment by czlee** [comment]
Just making a(n explicit) note (having just discovered this) that South is end-of-lifed in favour of the new migrations framework in Django, and South explicitly will not work in Django 1.7. So there's no question about ditching South. We should probably keep up to date with the latest version of Django just as a general habit.

**Comment by philipbelesky** [comment]
This is up in 0ac5274df362979d4aa3bc0c0c043ddd68231d70 on the 'develop' branch.

I think we've discussed this before but I've been using the [Gitflow semantics](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) for branch names and the like. But obviously disregard them if you're not keen.

Once this has been folded into master the following changes need to be made to the [wiki page](https://github.com/czlee/tabbycat/wiki/Installing-locally):

```$ python manage.py syncdb
$ python manage.py schemamigration debate --initial
$ python manage.py migrate debate````

Becomes

```$ python manage.py migrate
$ python manage.py createsuperuser```

**Comment by philipbelesky** [comment]
Oh also just realised I should have kept my original feature branch for 1.7 intact (instead I finished and folded into develop). So ```develop``` also contains sundry bug fixes and enhancements (that aren't just WADL related). But will only send feature branches in future! (And will try and get them as pull requests but having the repo private seems to have broken Githubs pull system)
