### ISSUE TITLE
Migrate to help_text based forms to increase usability

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#144]
Model fields can have a help_text:
```
    text = models.CharField(max_length=500, help_text="The motion itself")
```

Which we can then use in form displays to better describe what each thing does:

````
<label for="{{ form.text.id_for_label }}" class="col-sm-1 control-label" {% if form.text.help_text %}data-toggle="tooltip" title="{{ form.text.help_text }}"{% endif %}>
````

Ideally all non-obvious fields should have this, both as code documentation and to aid user understanding. We could also begin to standardise our form methods around this setup (I'm looking at you ```config.py```)

**Comment by czlee** [comment]
I'm not really sure that this is useful for `config.py`, it uses a generic key-value structure (with all values converted to strings) to store things in the database, rather than a field for each setting. (See #139 for plans there.)

**Comment by philipbelesky** [comment]
Largely completed now
