### ISSUE TITLE
Generate printable ballots for each round

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#147]
Possibly marginally useful (even for small tournaments) and not to difficult to implement. Just needs:

- [ ] A template block with a decent print stylesheet (this would take the place of the current indesign file) that would be aware of various config options (replies, range, number of speakers, etc)
- [x] A page for each round that will repeat the template and fill each instance with a debate matchup
- [x] A page that displays a single unfilled instance (for regular printing)

**Comment by czlee** [comment]
Just as a note, I've used ReportLab before to generate PDFs (it's a Python library for PDF generation) in a different context, but it worked well and others (according to their website) have used it in a web content context. So it's an option, but I'm sure there are other ways too.

Actually, I just did a quick Google, ReportLab happens to be what Django has in mind:
https://docs.djangoproject.com/en/1.7/howto/outputting-pdf/

**Comment by czlee** [comment]
Design questions:
 * How will we deal with the fact that we don't know what order speakers will speak in?
 * How does this affect the data entry UI? At the moment we select speakers in order. If we print speakers' names and put a "speaker order" field on the print ballot, we'd need to update the data entry UI to match the new scoresheets.

**Comment by philipbelesky** [comment]
ReportLab looks good as it would allow people to pass around a single file with all the ballots in it. Although doing it with a print stylesheet and working from the existing ballot-entry UI would be much faster.

As for speaker orders, I was assuming we would just use a blank space and use the typical "write the name in the blank space" option (perhaps with a list of possible names at the bottom of the page). I'm unclear if shifting to a design with a "speaker order" field would be any fast for data entry, and possibly would be confusing to most people filling in the ballots

**Comment by czlee** [comment]
Oh wait, to be clear, are we talking about individualized ballot forms for each debate like the ones Tabbie generates?

By "print stylesheet" are you thinking HTML or PDF (or something else)? Sorry, I'm confused with terminology.

I agree re speaker orders with list of possible names at bottom of page.

**Comment by philipbelesky** [comment]
Yea, individualized ballots forms for each debate.

By print stylesheet I mean a CSS stylesheet with ```@print``` specific rules to address things like margins, page breaks, etc

**Comment by czlee** [comment]
Oh, wow, you can use CSS to paginate things? You learn something every day.

**Comment by philipbelesky** [comment]
Completed in d9a757140a8fa1016d1540da27da11badebdcd48, although the nature of different tournaments is that each one will have slightly different ideas as to how to configure their ballot. These should (ideally) be added in as configuration flags (either conditional on existing flags, or potentially adding a small number of new ones) as needed.

**Comment by philipbelesky** [comment]
Example Ballots:
- https://github.com/czlee/tabbycat/raw/f6d014c985cb8d9a0bbad7f17ee9d3e022435a7e/templates/print/Example%20Feedback%20Ballots.pdf
- https://github.com/czlee/tabbycat/raw/f6d014c985cb8d9a0bbad7f17ee9d3e022435a7e/templates/print/Example%20Score%20Ballots.pdf
