### ISSUE TITLE
Add support for Novice Speakers (and perhaps SpeakerCategories more generally)

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#149]
In the same way that [teams should have BreakCategories](https://github.com/czlee/tabbycat/issues/119) such as ESL, then speakers should also be able to be given categories.

This is most useful for designating particular speakers as novices, given Easters in Aus, and many NZ tournaments have best novice awards.

At first, I don't think this category needs to be able to support arbitrary tags. Are boolean field for each Person as to whether they are a Novice or not should be sufficient? A config flag would be used to show/hide these in the UI.

**Comment by czlee** [comment]
A boolean field would be enough if it's only novice categories, but it might not be that hard to make the database generic. I think the difficulty with generic categories is in the logic to support views and the like.

**Comment by czlee** [comment]
Oh, and also, in the UI to define the categories. So if we want to avoid that in the short term, do a generic database, but make the category types hard-coded?

**Comment by philipbelesky** [comment]
Implemented by augmenting the existing novice status boolean in f96e5d6b4dd64889a83c4cf7d609efc8c71a24d1 and 2407cf8ff796db76960ee984293ead2abc109126.

Also note that ```novice``` field is also used now to indicate unaccredited adjudicators (in the case of NZ styles) as this is distinct from how most other styles where 'trainee' refers to a general category of adjudicators who aren't suitable panelists, rather than a hard and fast rule that someone has not passed accreditation.

We could possibly reopen this for more generic speaker categories, but I think our current ones are sufficient to cover most instances at major tournaments.
