### ISSUE TITLE
Improve support for multiple tournaments

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#15]
Would probably need to think this through.  Tournaments should really be isolated from each other—different institutions, debaters, user accounts etc.—maybe to the extent of being different databases? But if hosted on a web server for multiple tournaments, the server would need to be able to service several at once.

**Comment by czlee** [comment]
More thoughts:
* `Tournament`s probably shouldn't be isolated from each other. The same institution might go to multiple tournaments; the fact that they are the same institution might be nice to have in the database. The same goes all `Person`s as well.
* Accordingly, the relationship between `Tournament` and `Institution`, `Person`, _etc._ should be many-to-many, not one-to-many.
* User accounts should obviously be global—this would make logins so much easier for everyone.
* In particular, where multiple competitions are being run concurrently (or consecutively) by the same organization, there might be explicit value in identifying relationships between teams in different competitions.
* Having institutions participate in multiple tournaments could cause issues if we allow multiple tournaments, run by different organizations, to be run on the same server, because changes to the institution for one tournament would affect all other tournaments on the same server. We could make it a design assumption that a single server is being run for a single organization, in other words, only a slight relaxation of the status quo. Or would could create a new top-level model called `Organization` that can run multiple `Tournament`s, and associate each institution _etc._ with an `Organization` rather than a `Tournament`.

**Comment by philipbelesky** [comment]
Just a note that I've started this on ```feature/multiple-tournaments.``` I'm holding off on major architectural changes for now; just fixing the bug that sees Venues, Teams, and Adjs being shared across tournaments at the moment

**Comment by philipbelesky** [comment]
Just a note on a change that I'm going to test out. Currently we rely on looking up a ```Team```'s  or ```Adjudicator```'s ```Institution``` when filtering by ```Tournament```. Because Institutions are quite likely to be shared between Tournaments (and to be unique generally) I think it would be better to have ```tournament``` fields on both ```Team``` and ```Adjudicator``` and to use those for filtering instead.

This does create some weirdness given that ```Adjudicator``` has properties that are exclusive to particular tournaments (IE test scores, trainee status) while also inheriting from ```Person``` which is basically unique and could easily be shared across tournaments. 

However, for the applications where it makes sense to share adjudicators across tournaments (just schools tournaments at this point) we can probably ignore this as those are situations where there aren't tournament-specific conflicts, test scores, etc

**Comment by czlee** [comment]
One option is to have a new `TournamentAdjudicator` model that has foreign keys to both `Tournament` and `Adjudicator` and contains fields specific to the combination, similar to how `DebateAdjudicator` works. Then all current references to `Adjudicator` would have to be changes to `TournamentAdjudicator`, so it'd be an irritating change to make, but if there's a need for it then it should be done.

(I probably wouldn't say the same about `Team` though.)

**Comment by philipbelesky** [comment]
Closing this general issue as multiple tournament support has been extensively developed and tested over the last few months. Will remake separate more specific issues for future problems/improvements.

**Comment by czlee** [comment]
Cool, we should probably re-jig the models at some point as discussed above (though it seems major to be a top priority right now).

**Comment by evank28** [comment]
If user accounts are global, there should be a setting to disable superuser accounts from having access to specified tournaments. It is conceivable to have different tabs directors or chief adjudicators for each tournament. You should be able to do this in the same deployment of tabby cat -- just select which users can access which tournament.

**Comment by philipbelesky** [comment]
Hey, thanks for the suggestion @evank28. Would you mind opening a new issue for that specific requirement?

Tbh, it probably wouldn't be high on the priority for future development, as these multi-tournament setups are relatively rare (to my knowledge) or are used in a context (like internal club training or high school competitions) where security control isn't hugely necessary. We would be happy to accept a PR to this effect though!

**Comment by evank28** [comment]
thanks @philipbelesky. I suppose it actually relates to @tienne-B 's comment on #131. I agree with him completely - while users are global their permissions should be unique to each tournament. 
I as a tabs director want to be able to host multiple tournaments with different staff teams within the same deployment of tabbycat.

When I have some time, I'll see if I can work on a PR.
