### ISSUE TITLE
Add support for break rounds

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#150]
I mostly tapped out of tab things at Otago once the break was announced, so I'm a bit unclear about what the status of break round support is. Are there GUIs (ideally in public, but also in admin) for the following?:

- [x] Selecting which teams break (ie checking them in for break rounds)
- [x] Creating match ups between breaking teams for first eliminations
- [x] Creating match ups between breaking teams for subsequent eliminations

**Comment by czlee** [comment]
Nothing works. There is no support for break rounds.

Here's how I did break rounds at Otago Australs:

1. Go to the Django admin interface
2. Create a new `Round` and set its status to "confirmed"
3. Create as many new `Debate`s as you need to
4. Enter the `DebateTeam`s for each debate
5. Go to the tab director's interface
6. Allocate judges as usual
7. Release the draw

In other words, everything was manually allocated. We didn't use Tabbycat for any break-round administration. The only reason I bothered with it at all was so people overseas could follow.

**Comment by czlee** [comment]
By the way, here is how in my opinion break rounds should work:
* In `draw.py`, there should be a new class of `BaseDrawGenerator` that generates break rounds.
    * There is already some infrastructure for this - that's what the `results` parameter of `DrawGenerator`, which isn't currently used, is supposed to be for.
    * I think there will need to be distinct classes for the first break round and subsequent break rounds
* Both automatic side allocation (random with no regard to `aff_count`) and manual (coin toss) should be permitted
    * This requires that draws have the ability to contain no side information, which may require a database schema change.
* Scoresheets should be entered as usual
    * Eventually, support could be added for "winner-only" debates. If this is done, it should be done in a manner not specific to break rounds, as it is also used in preliminary rounds for some schools leagues.

**Comment by philipbelesky** [comment]
If we were to add the ability to have makeup rounds (for teams that say couldn't make a Friday night debate, as is common at some Australian tournaments) would it make sense to have a GUI that could edit a generated draw?

Ie a GUI each debate might be a row/debate with drop downs for the aff and neg teams. Which could then be edited and saved. (Or perhaps it might be drag and drop). The starting point for this would be a normally generated draw.

In the case of break rounds, ideally these matchups would be all pre-allocated using appropriate rules. However in the case of coin-tossing for sides, this GUI (or something similar) would be useful for that side of things. It would also be useful for when particular teams need to be matched to each other (say for rescheduling a particular debate).

**Comment by philipbelesky** [comment]
Also, this is only sort of related (in as much as I confused their purpose) but can you clarify what rules ```FirstEliminationDrawGenerator``` and ```EliminationDrawGenerator``` are implementing (maybe this should be a quick wiki page on round the ```draw_types``` rules?). They seem to have been for Joynt break rounds...?

**Comment by czlee** [comment]
Two answer the last question, the first one takes the top N teams from the standings, and the second one takes the winners of the previous round. Neither are implemented. Nothing to do with Joynt - they are both meant to be generic.

**Comment by philipbelesky** [comment]
Ok, so both are the starting point for creating draw rules for break rounds? That was what I had assumed was the case.

**Comment by czlee** [comment]
Yeah. I didn't get very far because I found it quite hard to figure out how to instruct it to take winners from particular rounds (it's not necessarily the last round, if there are multiple break categories). It's probably not that hard, just required too much thinking at the time. Try to keep `draw.py` well abstracted though - in principle it should rely on duck typing and know absolutely nothing about Django or databases.

**Comment by czlee** [comment]
Re GUI, my inclination is to create a feature for each of those jobs, since it's less prone to user error. I know there's some demand for editable draws. I don't know how I feel about them - in principle people should not be editing draws, and if there's an exceptional circumstance, there's a back-end for that. But it's probably not a bad idea, in case the draw algorithm actually does mess up.

**Comment by philipbelesky** [comment]
Just a note that I'm starting on this for WADL's purposes back on the feature branch. Will try and keep it vaguely relevant for Australs although having different types of breaks may not make the cut
