### ISSUE TITLE
Add a name field to the Tournament model

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#152]
Having a Tournament's name be the same as it's URL is quite annoying. Because the name is also a URL it can't have things like spaces, or many grammar characters. We should add a name field that is used for all interface displays of the tournament's title. We can still use the data folder's name in ```import_tournament``` we just need to [slugify it](https://docs.djangoproject.com/en/1.7/ref/utils/#django.utils.text.slugify) first

**Comment by philipbelesky** [comment]
Up in 0d82aba534c91afbfd9eab1fba44846b545b3fbc and 35c4528068a69e3c9aca4007bbb1960908361ec5 on feature/tournament-names

@czlee did you want to double check then fold into develop? (Maybe we should using the time when we fold in a feature branch as an excuse to do some kind of code review?)

**Comment by czlee** [comment]
I don't think `name` and `short_name` need to be unique (I mean it's good practice but system-wise it needn't be enforced), other that looks great.

**Comment by philipbelesky** [comment]
I think having them unique probably wont matter, but is a good guard against user error (probably mostly my own) especially with data importing.

**Comment by czlee** [comment]
Maybe. I generally hold the philosophy that it's better not to second-guess what restrictions tab directors might like, as opposed to what is necessary for the system to work. If we want a guard against user error, we should include a check with warning, not a database constraint.

**Comment by philipbelesky** [comment]
Sure, changed in b8bc24be711d20b6c3b143ca4a4de37e7b057d1a
