### ISSUE TITLE
Improve/Fix Motions Editing UI

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#154]
- [x] Unclear if this a regression, but deleting motions seems to no longer work
- [x] Also unclear if this is a regression, but there is no indication as to which fields are required, and saving without the required fields fails silently
- [x] It might be optimal to start with just one motion area, and use a button/javascript to add more (via unhiding) forms to the page dynamically. This seems like it would be faster than having to wait for a post, and also may make it less confusing when using formats which have set motions 
- [x] The current warning seems overly alarmist (did it proceed the release to public option?). Perhaps we should remove it (and rely on docs / the Release button) or reword it

**Comment by czlee** [comment]
It's meant to use a Django built-in form class. Could the regression have been introduced by Django 1.7 API changes?
