### ISSUE TITLE
Tournament data import module

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#157]
This obsoletes #24.

This module will be responsible for doing the processing of CSV files passed to it. Its job is:
* Read CSV files passed to it
* Write the data in them to the database
* Validate the data and decline to import faulty lines
   * As a principle, it will not raise exceptions in all except the most dire circumstances, but instead will log messages using `logging.error()`.
   * It will skip over faulty lines if it can.
   * __Question__: Should it also return error messages for a client to write to the GUI?
* Use `logging.info()` to print some comforting messages to the console.

Specifically, the following are not functions:
* Any sort of user interface management, including
   * "Are you sure?" messages
   * Any sort of options handling
* Finding or opening files in the file system (for flexibility, it expects an open file to be passed to it)
* Setting up a new `Tournament` instance

Feedback appreciated =)

Proposed API if implemented as class
==============================

Advantages
* Different importers can run without affecting each other's parameters (though why two would ever run simultaneously is unclear)
* `tournament` argument can be passed as a parameter

Disadvantages
* More annoying for clients to set up.

``` python
class TournamentDataImporter(object):
    def __init__(self, tournament, **kwargs):
        ...
    def auto_make_rounds(self, num_rounds):
        ...
    def import_rounds(self, f):
    def import_venues(self, f):
    def import_teams(self, f):
    def import_adjudicators(self, f):
    [...]
```

Client:
``` python
import debate.importer
import debate.models
tournament = debate.models.Tournament.objects.get(slug='demo')
importer = debate.importer.TournamentDataImporter(tournament)
importer.import_rounds(open('rounds.csv'))
importer.import_venues(open('venues.csv'))
```

Proposed API if implemented as functions
==============================
Advantages
* No set up required, can use default options

Disadvantages
* Parameters affect everyone
* Some arguments might get repetitive

``` python
def auto_make_rounds(tournament, num_rounds):
    ...
def import_rounds(tournament, f):
    ...
def import_venues(tournament, f):
def import_teams(tournament, f):
def import_adjudicators(tournament, f):
```

Client:
``` python
import debate.importer as importer
import debate.models
tournament = debate.models.Tournament.objects.get(slug='demo')
importer.import_rounds(tournament, open('rounds.csv'))
importer.import_venues(tournament, open('venues.csv'))
```

**Comment by philipbelesky** [comment]
One quick note: it might be good to have a 'strict' mode where a single line error prevents future operations and prevents the previous objects being saved. When importing large amounts of data it's useful for the debug/editing process to have things halt before a full import (to prevent having partial data sets)

**Comment by czlee** [comment]
Scratch the functions idea, I'm going with classes.

More notes:
1. The various `import_*` functions won't necessarily have disjoint domain. That is, they'll overlap, and it's on the client not to engage them in a nonsensical way.
2. 

I like the strict mode idea. It won't (without extra work) prevent partial data sets though, since if it halts when it's (say) halfway through the teams list then you'll have everything up to the team that crashed it. Should it validate everything first, or should we just make the user scrub and import as many times as is necessary to clear the errors?

**Comment by philipbelesky** [comment]
Yea, I kind of like the idea of not having anything .save() right until the very end after validation. It probably helps with importing data that isn't tournament specific (and can't be easily deleted on reimport). Plus it prevents the primary keys from getting super high!

**Comment by czlee** [comment]
How robust is the Django model validation? Is it sufficient to guard against errors when calling `.save()`, or does it perform a subset of the requisite checks that one would need to avoid `.save()` errors?

So in my mind the process in each import function would be:

1. Create all of the model objects (`Institution`, `Team` or whatever), saving them in a list.
2. Run `.full_clean()` on each of them in turn. If any of them fails, collect a list of all of the `ValidationError`s.
3. If `self.strict` is true any model failed validation, raise a single `ValidationError` containing all of the `ValidationErrors` caught in validation above. (If `self.strict` is false, just log the errors.)
4. Run `.save()` on all of them.

So like:
``` python
def import_teams(self, f):
    reader = # set up the reader
    teams = list()
    errors = list()

    for line in reader:
        # parse line
        team = m.Team(...)
        try:
            team.full_clean()
        except ValidationError as e:
            errors.append(e)
            logger.log(logging.ERROR if self.strict else logging.WARNING, e.message)

    if self.strict and errors:
        raise ValidationError(errors)

    for team in teams:
        team.save()
```

Thoughts?

**Comment by philipbelesky** [comment]
Sure, I was more thinking common classes or errors the happen before ```.save()``` such as institution objects not being found, misplaced commas etc. But validating the models also sounds good.

**Comment by czlee** [comment]
Some thoughts I encountered during implementation. The bottom line is that it's
not possible to write an import script that doesn't save to the database until
everything is validated. But some compromises could be made.

1. Should the importer save to the database after every file, or after all
   files?

2. If after _all_ files, I'm not sure that this is possible. It would require us
   to create objects that reference other objects before they are saved. For
   example, teams (often) require a reference to their institution. Now, if that
   object was just created and we still have a handle to it, that's fine. But if
   it requires a database lookup, _e.g._ to identify an institution from its
   name/code, then we can't do that without first saving to the database. This
   necessarily requires that saves be done, at least in groups, before the
   entire import is completed.

   Does this completely cripple our hopes of preventing primary key inflation?

3. In particular, it's our current practice to `get_or_create` some items.
   `get_or_create` saves model instances if they don't already exist. Should
   we get rid of all of these?

   If we do, then this would require us to insist (at a minimum) that all
   institutions are completely imported before teams are created, all teams are
   imported before speakers, rounds before motions, venue groups before venues,
   _etc._

   We can avoid asking the user to provide redundant information by just doing
   multiple passes of files that involve this, _e.g._ in a teams list that also
   provides information about institutions, do a first pass for institutions
   (uniquifying them using Python processing rather than `get_or_create`), then
   a second pass to create teams. But this still requires us to run multiple
   database saves for that file.

4. As a particularly fun case where this is distinctly unavoidable, consider
   adjudicator-adjudicator conflicts (not currently supported). Either we
   have to do two passes of the adjudicators file, or we have to ask that
   adj-adj conflicts be provided in a separate list.

**Comment by philipbelesky** [comment]
If we can't delay from saving until the end, then perhaps it is best to treat things on a type-by-type basis. So for example, if the ```Institutions``` (whether from an institutions file, or gathered from a teams file) are all valid, then they can be saved. When re-running the import it shouldn't be adding new values anyway as they already exist. So maybe (either as a strict option or as a default) it will halt if there are any invalid objects for each type, but yea it does seem like each section of imports should probably be saved, so the strict sectioning mentioned in 3 doesn't seem like an issue. 

Get or create is mostly a shorthand method to the standard get/saves; so we could just write our own version that creates (if it cannot get the item) without saving the instance.

Preferably the importer would be flexible about whether data is strictly separated (ie having a teams.csv and an institutions.csv or just inferring from teams.csv). So maybe the strict option (or a second option) would toggle whether to create missing references or to rely on them already being imported.

**Comment by czlee** [comment]
A "get-or-create" that doesn't save is still more complicated than it sounds. Subsequent lines (say, venues or speakers) will still need to be able to find containers (venue groups, teams) that were created in earlier lines, and so haven't been saved. This, in turn, means that the `Model.objects.filter()` and `Model.objects.get()` methods can't be used.

It's still not impossible: we could write a custom filter/get method that tries a database lookup first, and then searches in a list of recently-created objects if it that fails. The latter search would necessarily be Python-based, and therefore inefficient, but (presumably) functional.

But this starts to raise questions about how far we should go. As we insert more layers between the importer and the basic Django functionality, it also becomes less maintainable (steeper learning curve). To me, making it easy for future contributors to add import functions for new file formats easily is half the point of the rewrite. So I start to wonder if other tactics would be better. For example, is it possible to erase an entire database (without dropping the database) and reset primary key counters to zero? Is there a use-case where one would want to do strict imports file by file, reverting only to the last file if it goes wrong, or do we tend to import the vast bulk of tournament data at once, at the beginning?

**Comment by philipbelesky** [comment]
Sorry I mean it doesn't save *immediately*. I had imagined that at the end of each type of data, the data that had been created but not saved, would then be saved collectively (if they are all valid) so that they may be referenced in future sections. So by the time you get to Venues or Teams, there would be Groups and Institutions available for reference. Which should simplify things? (It would have its flaws but I think its more than good enough)

In terms of erasing the database, the flush() management command does that. But thats not desirable when multiple tournaments exist.

**Comment by czlee** [comment]
I think that's probably feasible. So basically the rule is, it will do as many passes of a file as it needs to, creating only one type of object per pass. So _e.g._ with adjudicators:

- First institutions (probably optional)
- Then adjudicators
- Then adjudicator-institution conflicts
- Then adjudicator-team conflicts (crashing if a team is not found)
- Then adjudicator-adjudicator conflicts (not current implemented)

How useful would this be? Sometimes it might not be desirable, say if an institution name is misspelt in the team list, it would just silently create the missing institution. But the main script could just have a "create-on-demand" option or something, and if the user wants to use it, then it's user beware.

**Comment by philipbelesky** [comment]
I think there's a couple of use cases:

- Instances where you really don't want new objects created if there is an error with the data; IE when importing large tournaments and there's a large chance you'll need to debug at least a little bad data / faulty relationships. Or when importing a new tournament into a multi-tournament setup where you don't want to potentially import bad data into a database that can't easy reset. That said dumping/restoring the database prior to imports should kind of make this easier

- Instances where its a smaller tournament and small errors can easily imported manually in the backend, so the 'just import everything warts and all' mode is fine.

- A hypothetical future GUI importer that processes things file-by-file (in a strict sequence) where the data needs to be modularised to the extent that importing institutions, teams and adjudicators are quite separate steps. This doesn't necessarily have any bearing on the earlier use cases, but does highlight the need for a modular approach.

Which is all to say the proposed sequence above sounds useful.
