### ISSUE TITLE
Venue split names cut off everything after first set of digits

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#160]
_e.g._ "E1 - neg prep E2" displays as "E 1", omitting everything after the "1".

Probably caused by the regular expression match not picking up on groups after the pattern match:
``` python
class Debate(models.Model):
    @property
    def venue_splitname(self):
        match = re.match(r"([a-z]+)([0-9]+)", str(self.venue.name), re.I)
        [...]
```

**Comment by philipbelesky** [comment]
Are split names even useful anymore? Any name with a space in it should wrap over two lines; and the function is only used in the print ballots (where it is also unnecessary)

**Comment by czlee** [comment]
Weren't they used to manage column widths for mobile interfaces?

**Comment by philipbelesky** [comment]
Hmm, not currently, and if they were that's better done through CSS restrictions
