### ISSUE TITLE
Saving motions are allowed despite having reference field left blank.

### ISSUE THREAD

**Issue by wytanj** [czlee/tabbycat#172]
Saving motions are allowed despite having reference field left blank. However, motions are not saved and you would just have to key them again.

Situation encountered: once draw was out without motions being keyed.

**Comment by philipbelesky** [comment]
Fixed in 2cc28b44d341796ed40d64fa75a1d2e5cd9f835a, will be in a new release shortly (is in master now). The fields now show inline validation errors when key fields are left blank. Let me know if additional validation rules are needed!
