### ISSUE TITLE
local setup throws error on database

### ISSUE THREAD

**Issue by prasgema** [czlee/tabbycat#173]
the newest version: local connection to database failed. it said "improper databases setting". I think it is because it doesnt read the local_settings.py
![screenshot from 2015-05-29 22 03 58](https://cloud.githubusercontent.com/assets/11336579/7885540/a3500152-064e-11e5-835a-3f6f81ff95f8.png)

**Comment by philipbelesky** [comment]
Should be fixed in 2cc28b44d341796ed40d64fa75a1d2e5cd9f835a, will be in a new release shortly (is in master now). Thanks for letting us know!
