### ISSUE TITLE
reply speaker standing displays their substantive scores

### ISSUE THREAD

**Issue by prasgema** [czlee/tabbycat#174]
In post tournament (version pulled on April 20th), the reply speaker standing displays their substantive scores.

However, each score displayed at the correct round for each debater. So, I suppose it's only a column name mismatch
![screenshot from 2015-05-29 22 10 16](https://cloud.githubusercontent.com/assets/11336579/7885729/c6931a72-064f-11e5-9d40-51faf9589f50.png)

**Comment by philipbelesky** [comment]
Sorry, this is fixed in 2cc28b44d341796ed40d64fa75a1d2e5cd9f835a, will be in a new release shortly (is in master now). Thanks for catching it!
