### ISSUE TITLE
Reply speaker scores are shown wrongly in two ways, despite database in django showing accurately

### ISSUE THREAD

**Issue by wytanj** [czlee/tabbycat#176]
First erroneous display: scores of reply reflecting main speaks( I.e. 78 for a reply)
Second erroneous display: scores being allocated to other teammate whom never did reply through the tournament( I.e. third speaker getting reply speaks)

**Comment by wytanj** [comment]
Apologies did not see #174. Closing and awaiting fix.

**Comment by wytanj** [comment]
Reopened as Philip might not have saw the second part of the error

**Comment by philipbelesky** [comment]
Hi, this should have been fixed at the same time as #174 as it was the same bug causing both issues. The fix should be in the current master branch, so if you update everything should work properly. Let me know if not though!
