### ISSUE TITLE
Add a shadow tab/draw system

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#177]
This might be a little ambitious to pull off in time for ADAM, but would be a good goal to work towards. Basic jist is to be able to pre-form panels prior to draw generation

**Comment by czlee** [comment]
Random comment, but if we do this properly (i.e. you can pre-form panels prior to draw generation) then we should probably be bold and call it something other than "shadow tab", in favour of something more descriptive, like "pre-formed panels".

(To me shadow tab means a separate tab system intended to shadow the real tab…)

**Comment by philipbelesky** [comment]
Superseeded by #258
