### ISSUE TITLE
Extend gender highlighting/flags to include Region and ESL status

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#178]

**Comment by philipbelesky** [comment]
Similarly, I think different highlights should be used to indicate institutional vs personal conflicts.

**Comment by philipbelesky** [comment]
[ ] The importer should handle creating the appropriate `Region`s for each imported `Institution`. I assume this is done by adding a fourth (optional) column to `institutions.csv` and and extra key to `anorak.py`'s `_institution_line_parser`. Is that right @czlee?

**Comment by czlee** [comment]
Bingo! Though if you want it to create regions on the fly while importing institutions, you'll need to insert another parser (`_region_parser()`) and `_import()` call. See some of the later functions for examples of how to daisy-chain `_import()` calls. Alternatively you could add an `import_regions()` method.

**Comment by czlee** [comment]
Actually `import_venues` would be the best example. Auto-creating regions should probably be an option (default `True`). If the region doesn't exist in the CSV file, `_region_parser()` should return `None`. And `_import()` should be called with `expect_unique=False`.

**Comment by philipbelesky** [comment]
Cool. As an aside: Regions are currently attached to Institutions not
teams, which is a bit inconsistent with the other flags (esl/efl) but would
speed up manual data massively. Do you think that's the correctly to go?

**Comment by philipbelesky** [comment]
Done with #185
