### ISSUE TITLE
Add descriptor of round status to the round menus

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#182]
Just to explain what the (very useful) color-coding means :smiley:

Thinking just above "Team Checkins", in this case "Status: Released" written in the same blue, and not a link:
![image](https://cloud.githubusercontent.com/assets/1725499/7944783/b424607e-0921-11e5-81b5-dff03327a99e.png)

(@philipbelesky, thoughts?)

**Comment by philipbelesky** [comment]
Good idea!
