### ISSUE TITLE
Optimise the get_draw() function

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#186]
Currently this is a critical bottle neck in serving of many views, and as currently structured is hard to optimise using ```select_related``` and other methods to combine SQL queries.

**Comment by czlee** [comment]
I sort of did this in #336, at least with respect to teams, and I think it's much faster now (though we don't have rigorous benchmarking tools). The other things that need to be done faster are retrieving split adjudicators (#331), find a way to list debate adjudicators other than by instantiating each `AdjudicatorAllocation` individually (#337) and retrieving ballot submission versions in bulk (#338). There might be others, but I think those are the main ones.

**Comment by czlee** [comment]
Closing in favour of new sub-issues.
