### ISSUE TITLE
Team standings places teams with no results ahead of teams with results

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#206]
Presumably because the `points` aggregation field returns `NULL` which sorts first in SQL with descending-order sorting.

**Comment by czlee** [comment]
The new `standings` module (available in 0.7.2) doesn't use the database `order_by` to sort any more, to unify the approach it always relies on Python's `sort()` function. So this should no longer be an issue.

Have not tested it explicitly, so should do so at some point, then close this.

**Comment by czlee** [comment]
link to #134

**Comment by philipbelesky** [comment]
Given #134 is closed; is this also?

**Comment by czlee** [comment]
Possibly. I think I haven't actually tried it, so didn't close it.

**Comment by czlee** [comment]
Actually, now it doesn't place teams with no results in the standings at all, because it filters teams for `debateteam__debate__round__seq__lte=round.seq`. Which is possibly a bug, because it means that teams who haven't competed yet might break the "draw with details" page.

**Comment by czlee** [comment]
Okay, an obscure hangover from the last standings refactor (not the most recent, the one before that) was getting the wrong queryset, leading to many bugs. It's fixed in 20cc52c. There were actually several small bugs that only hit corner cases and in some cases "cancel out" to have no visible effect.

But I've checked that this issue is also resolved, and it is, because the new standings classes never return `None` for a metric, they always replace it with 0 if appropriate so that it is Python-comparable.
