### ISSUE TITLE
Current round cache may be too persistent for results page to show

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#212]
At Australs 2015, after the current round was incremented from 8 to 9, the results page for 8 still wouldn't show, and would be denied because the current round was still "8" (even though it was actually 9).

Flushing the cache fixed the problem.

This may be a non-issue (maybe I just wasn't patient enough).

**Comment by philipbelesky** [comment]
Not sure if this is still an issue, but I suspect the round cache isn't automatically being invalidate when the round is incremented, which it should be. Any changes to a particular round object should also invalidate it.

**Comment by philipbelesky** [comment]
Link to #266 (I think)

**Comment by philipbelesky** [comment]
Removing the milestone as afaik this either hasn't occurred at Australs and/or there aren't any leads on how to fix it.

**Comment by czlee** [comment]
I think fc47c752e00bbdf423f36c9ab01b7ed87dec31e5/b293900d6286d65dbbc77f3fb0e67f5a7087f710 might've fixed this?

**Comment by philipbelesky** [comment]
Hopefully; I'll close and we can reopen if needed.
