### ISSUE TITLE
Add new AIDA institution cap mechanism

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#213]
Apparently this was changed at AIDA Council this year, so `breaking.py` will need to be modified accordingly. Probably best to make it a configuration in `BreakCategory` alongside `BreakCategory.institution_cap`. Need to get specifics on mechanics from minutes.

**Comment by philipbelesky** [comment]
Just to confirm: this has been rolled in and is completed? Or is further work needed here?

**Comment by czlee** [comment]
I think I left it on a branch because I was nervous about whether it would work and wanted to review it when we weren't under pressure. But the implementation is done and rolled into develop.

**Comment by philipbelesky** [comment]
Ok, shall we consider it done then? There are probably some test cases we could write for edge cases. Oh and we probably need to split out `BREAK_QUALIFICATION_RULE_AIDA_2016` into seperate Easters and Australs variants, but that wouldn't need to happen until Easters next year. But each of those should probably be seperate issues if this is considered done.

**Comment by czlee** [comment]
Yeah, probably. I should probably write tests for it, but I think that's better done under #307. Will delete the branch when I next get a chance.
