### ISSUE TITLE
Investigate interface errors in the adjudicator allocation page

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#215]
What happened a few times during Australs was that adjs, once dragged from the Unused column, would not drop properly but instead become stuck in the top left. Couldn't diagnose at that well time, but I suspect there was a javascript error that meant some portion of the UI code was not run. So ideally the AJAX calls here would be asynchronous, but we should also rule out that the bug isn't in the UI code, and possibly also catch failed callbacks so that they can either reload or fail in a way that does not bring down the rest of the interface.

**Comment by czlee** [comment]
@philipbelesky is this still a thing, or is this rendered obsolete by the new adj allocation page?

**Comment by philipbelesky** [comment]
Yea hopefully it's obsolete. Either way I don't think there is enough info to reproduce the errors anyway.
