### ISSUE TITLE
Show version codename and number on UI somewhere

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#218]
It's probably good practice for the version to be displayed somewhere on the UI. Not sure exactly how to implement this.

**Comment by philipbelesky** [comment]
Just set as a constant somewhere and remember to bump it? It should probably in the footer just after the "Tabby Cat"

**Comment by czlee** [comment]
Yeah, could do, I think that's the typical practice.

**Comment by philipbelesky** [comment]
Have just put this as a string in the footer; I think anything more complicated is probably less likely to be updated. Also mental note that we need to change this to whatever the Bengal milestone version number ends up being (have set as 0.8.0 for now)
