### ISSUE TITLE
Removing abbreviation on Institution

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#219]
As far as I can tell, an Institution's ```abbreviation``` is not explicitly used anywhere except as a fallback for its ```code```. To make data entry slightly faster and clearer, I think it should be removed. Any reasons why not?

**Comment by czlee** [comment]
It's used in the adjudicator allocation interface, to save space. If it's not, it probably should be. To my knowledge, it's not used anywhere else, but one place seems sufficient to me.

If it's an issue with data entry we should redesign our data entry so that it generates these automatically.
