### ISSUE TITLE
Should migrations be included in distributions?

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#224]
Okay, so the root cause of the migrations failure, and the need to run `python manage.py makemigrations auth` first, is that some of our apps refer to `settings.AUTH_USER_MODEL`, *e.g.* all `Submission` subclasses use `settings.AUTH_USER_MODEL` to track who entered the submission.

According to the [Django documentation on migrations](https://docs.djangoproject.com/en/1.7/topics/migrations/#dependencies):
> Be aware, however, that unmigrated apps cannot depend on migrated apps, by the very nature of not having migrations. This means that it is not generally possible to have an unmigrated app have a `ForeignKey` or `ManyToManyField` to a migrated app; some cases may work, but it will eventually fail.

As a first pass, I ran this command, to generate *all* migrations before migrating:
``` bash
$ python manage.py makemigrations action_logs allocations availabilities breaks draws feedbacks motions options participants results tournaments venues
$ python manage.py migrate
```
and that worked. Running `python manage.py makemigrations` by itself does not work, because this (deliberately) does not migrate unsynchronized apps.

We surely can't be the first to want to refer to `settings.AUTH_USER_MODEL` in our own apps, so there must be some common practice for this. [Sure enough](https://docs.djangoproject.com/en/1.7/topics/migrations/#the-commands):
> The migration files for each app live in a “migrations” directory inside of that app, and are designed to be committed to, and distributed as part of, its codebase. You should be making them once on your development machine and then running the same migrations on your colleagues’ machines, your staging machines, and eventually your production machines.

[In fact](https://docs.djangoproject.com/en/1.7/topics/migrations/#dependencies):
> **Warning**
> 
> Even if things appear to work with unmigrated apps depending on migrated apps, Django may not generate all the necessary foreign key constraints!

Therefore: Should we be distributing migrations as part of our releases?

In many ways, this would be sensible. Third-party apps often come with migrations built-in: note, for example, that `django.contrib.auth` does not start out "unsynchronized". Based on the documentation, this is obviously how things are meant to work.

Of course, it increases our development overhead. At least, currently, my practice is to run migrations often as I'm trying out different data structures. Also, you can't just remove and add migrations at will, as I currently am locally. Django's migrations app keeps track of migrations *by name* (abridged):
```
demo=> SELECT * FROM django_migrations;
 id |      app       |                     name                     |            applied            
----+----------------+----------------------------------------------+-------------------------------
  1 | breaks         | 0001_initial                                 | 2015-08-17 08:44:22.492495+12
  2 | participants   | 0001_initial                                 | 2015-08-17 08:44:22.703873+12
  7 | auth           | 0001_initial                                 | 2015-08-17 08:44:23.30473+12
  8 | motions        | 0001_initial                                 | 2015-08-17 08:44:23.387379+12
  9 | draws          | 0001_initial                                 | 2015-08-17 08:44:23.515709+12
 18 | allocations    | 0002_auto_20150817_0643                      | 2015-08-17 08:44:27.122389+12
 19 | contenttypes   | 0002_remove_content_type_name                | 2015-08-17 08:44:27.538933+12
 20 | auth           | 0002_alter_permission_name_max_length        | 2015-08-17 08:44:27.694896+12
 21 | auth           | 0003_alter_user_email_max_length             | 2015-08-17 08:44:27.876704+12
 22 | auth           | 0004_alter_user_username_opts                | 2015-08-17 08:44:28.035654+12
 33 | participants   | 0002_auto_20150817_0643                      | 2015-08-17 08:44:38.906152+12
 34 | tournaments    | 0002_auto_20150817_0643                      | 2015-08-17 08:44:40.81811+12
```

I'm actually not too concerned about the development overhead: it seems to be good practice, and the `makemigrations` tools are intended precisely for this purpose. We can write helper scripts to make it less tedious if that becomes necessary, but I suspect it won't. But it's worth noting that the cost to us is not zero.

It seems, though, that if we're doing this properly we should be committing migrations and never removing them. So I worried about a migrations bloat, where we have lots of small migrations accumulated during development that should be just one big one. Also, I'm a neat freak, so if I add a field then decide it was a dumb idea, I think those migration commands should be excluded from the distribution. But then, [from the documentation on squashing migrations](https://docs.djangoproject.com/en/1.7/topics/migrations/#squashing-migrations):

>You are encouraged to make migrations freely and not worry about how many you have; the migration code is optimized to deal with hundreds at a time without much slowdown. However, eventually you will want to move back from having several hundred migrations to just a few, and that’s where squashing comes in.
>
>Squashing is the act of reducing an existing set of many migrations down to one (or sometimes a few) migrations which still represent the same changes.
>
>Django does this by taking all of your existing migrations, extracting their `Operations` and putting them all in sequence, and then running an optimizer over them to try and reduce the length of the list - for example, it knows that `CreateModel` and `DeleteModel` cancel each other out, and it knows that `AddField` can be rolled into `CreateModel`.

In a nutshell: We're doing it wrong. At the same time, the migrations concept probably requires at least a minimal degree of stability. I don't think we've violated that before the current app restructure, but then, the whole point of keeping away from 1.0.0 was to allow us this freedom.

## Proposal

We should include migrations in our distributions.

**Prior to 1.0.0**, migration continuity is guaranteed for **patch releases**, but there is no assumption of migration continuity for **minor releases**.

**Starting with 1.0.0**, migration continuity is guaranteed for **minor releases** (and patch releases), but not **major releases**.

In minor releases before 1.0.0 and major releases starting from 1.0.0, release notes should indicate whether migrations are compatible.

**Meaning of "migration continuity":** Basically, migration continuity exists if you can upgrade from any prior version on an existing running instance, by applying migrations. This means
* All previously existing migrations are either still there, or are squashed into a new migration.
* All new migrations follow from previously existing migrations.

We may squash or re-generate migrations incurred during development since the last release if we like: guarantees are provided only *relative to the last release*. I would do this if, for example, I know that I added then removed a field or model. I probably wouldn't bother if I just happened to make three incremental migrations during development.

Note that squashing migrations keeps current migrations in tact: Django knows how to replace lots of migrations with a squashed migration when it migrates a database.

When there is no assumption of migration continuity, it is in effect assumed that you're setting up a new instance from scratch. We may, but don't have to, remove all migrations from all apps and replace them with new initial migrations, without even squashing them.

**Comment by czlee** [comment]
Update: I didn't try to reproduce the issues where the unit tests fail because of database setup, but with migrations created for all apps I'm not seeing the issue, so I suspect that's it. Now the tests are all failing, but that's another issue.

**Comment by philipbelesky** [comment]
Sounds good, although I don't have a particularly good memory for the kind of hassles that migrations have caused in the past. In any case, they mostly have been a hassle working in development, given most installed instances are rarely migrated. But even if thats true, better to have more hassles in development than a less smooth deployment process.

Does migration continuity include instances where some degree of intervention is required? IE setting one-off values? Although from what I remember, all migrations once deployed to heroku require an intervention, although perhaps we could add in migration commands to the post-compile hook.

Also with regards to development effects, I'm guessing that the procedure would be that any changes requiring a migration should probably be in feature branches, and that the procedure would be to squash any new migrations (you can specify particular migrations to squash, which in this case would be any new ones since branch creation) before merging it back into develop? 

I'll add this to the checklist in #221

**Comment by czlee** [comment]
I think you can modify migrations to specify that one-off value, if we don't want it to come up with that annoying prompt. So yeah, for specifying one-off values we should always generate the migrations in a way that doesn't require that. From memory, it asks for one-off values during `makemigrations`, not `migrate`, right? Which would do the trick anyway.

I think a post-compile hook might let us drop the requirement to install Heroku toolbelt and allow full deployment directly from GitHub, if we can get it to work? I've been looking around on the internets though and no-one recommends this approach. I'm not sure why.

Re procedure, yes, but there seems to be an encouragement in the documentation not to be so obsessive about squashing migrations. I'd squash where migrations cancel each other out, maybe not so important if they're just incremental adds/modifications.

**Comment by czlee** [comment]
Also, agree with migrations not causing issues in deployment because existing deployments rarely migrated. I always thought causation might be the other way round though: we don't do it because it's such a hassle. (Well, also because there's normally no need for it, I guess.) Maybe if it were easier there'd be more motivation to upgrade existing deployments :smile:.

Also, if we can get this working, it reduces one massive barrier to a permanent software-as-a-service deployment. Not that I'm advocating it, but it'd be nice to keep the door open.

**Comment by philipbelesky** [comment]
Did you want to go ahead and implement this into the current ```develop```?

**Comment by czlee** [comment]
I was going to, and then wondered if we should hold off until either (a) Python 3 port is complete (so that the migrations are in Python 3) or (b) just before our next pre-release. Thoughts?

**Comment by philipbelesky** [comment]
Once the python3 branch is rolled it that sounds like a good start, as it does simplify the dev setup process somewhat and there probably wont be many more drastic changes to the models coming up.
