### ISSUE TITLE
Python 3 port

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#225]
There's a handy website here:
https://caniusepython3.com/

Our page:
https://caniusepython3.com/check/8b0ce386-8c01-4692-bd51-d7e799612e7b

![Python 3 port status](https://caniusepython3.com/check/8b0ce386-8c01-4692-bd51-d7e799612e7b.svg)

According to this, as of 17 August 2015, the one package holding us up is django-ipware. The caniusepython3 tool works by checking for categories on PyPI, and [django-ipware doesn't list Python 3](https://pypi.python.org/pypi/django-ipware/1.1.0). However the discussion at un33k/django-ipware#4 seems to indicate that it actually is Python 3 compatible. So it looks like we're good to go, when we're ready.

**Comment by philipbelesky** [comment]
Ok, have created a feature branch. Is there a particular version we are aiming for?

**Comment by czlee** [comment]
No, but by default aim for the latest (3.4). I wouldn't start trying until we're done and dusted with the app restructure.

Originally I was going to say that we should finish whatever overhauls we have in mind as well, but on second thoughts, once we decide to port to Python 3, it makes sense to do it sooner rather than later, so that we can get used to it as early as possible before release—even if the code is in a messy state now.

The main decision is the decision to leave behind Python 2. I can't think of any compelling arguments against it—Python 3 has been around for five years now, is included in Ubuntu and can be easily installed on other operating systems—but it's definitely not a decision one takes lightly. There are some though: Most packages are Python 3-ready but not all, and if we decide to port, it could narrow our options later. Also, it raises the barriers slightly for some local installs.

**Comment by czlee** [comment]
Or if you meant whether we're aiming for a version of Tabbycat... no. But like the app restructure, we should do it once and leave behind the old code when we do.

**Comment by philipbelesky** [comment]
I had meant python version. Looks like Heroku runs [up to 3.4.3](https://devcenter.heroku.com/articles/python-runtimes#available-runtimes)

Looking at the [Django porting documentation](https://docs.djangoproject.com/en/1.8/topics/python3/) it doesn't seem like it would be *too* hard to have a version compatible with both 2 & 3. Although maintaining that would be an ongoing annoyance.

**Comment by czlee** [comment]
Yeah, I'm basically inclined to say I'm too lazy to support both. We have no downstream dependencies, so it doesn't seem worth any nontrivial effort. The only benefit of supporting Python 2 is that some people won't have to install Python 3. Two years ago, that was a solid argument. From what I can gather, the [tide is starting to turn](http://www.i-programmer.info/news/98-languages/5767-python-33-overtakes-27-time-to-switch.html), so this isn't as strong an argument as it used to be. Also, Ubuntu's apparently [dropping Python 2 in its 15.10 branch](http://news.softpedia.com/news/Ubuntu-15-10-to-Finally-Drop-Python-2-X-Support-477830.shtml). But it's [not as if](http://www.i-programmer.info/news/98-languages/8269-python-2-versus-python-3-revisited.html) we're now behind the Python community, at least not yet.

**Comment by philipbelesky** [comment]
Making a list of broken things:

- [ ] The scripts in ```data/utils``` due to an error in ```header.py```

Have gotten up to the entering results stage of a simulating, having fixed a few things on the way. On the whole only small things seem broken, so I wouldn't be adverse to merging it into ```develop``` if you're happy to.

**Comment by czlee** [comment]
The `data/utils` scripts look fine to me? They broke for a bit because I forgot to run `2to3` on them, but after 0b0e7fc they should work. What's the symptom?

I don't really mind whether we merge into develop or not—it's not as if we're trying to keep develop stable—though maybe we should have some branching strategy in mind for updates on the Python 2 branch. Which I presume is now synonymous with the master branch, which means it's all hotfixes?

**Comment by philipbelesky** [comment]
Hmm, the traceback is:

```Traceback (most recent call last):

  File "data/utils/generate_random_results.py", line 5, in <module>
    import header

  File "/Users/philip/Code/tc_python3/data/utils/header.py", line 22, in <module>
    django.setup()

  File "/Users/philip/.pyenv/versions/3.4.3/lib/python3.4/site-packages/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)

  File "/Users/philip/.pyenv/versions/3.4.3/lib/python3.4/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)

  File "/Users/philip/.pyenv/versions/3.4.3/lib/python3.4/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)

  File "/Users/philip/.pyenv/versions/3.4.3/lib/python3.4/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)

  File "/Users/philip/.pyenv/versions/3.4.3/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named 'settings'```

Possibly some relative path issue; maybe related to having virtualenvs across django versions.

And yea, I think merging in is a good idea, as I'm not sure how much dedicated debugging there is to do on the branch; probably easier to roll it in so that we can test it in the process of other develop work. 

Hotfix branches seem to be the way to go for releasing to 0.7.

**Comment by czlee** [comment]
Port done, we're basically on Python 3 for the next release now.
