### ISSUE TITLE
Add warnings to documentation and the site about IE8 support

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#226]
[Bootstrap 4](http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/) is out in Alpha. I'd like to upgrade to it eventually, particularly given it switches over to SASS as its preprocessor and has improvements to its JS. There's a slight complication that it drops support for IE8. The support is unlikely to mean the site is *unusable* in IE8, at least on the public facing side. 

IE is only ~4% of our traffic, and IE8 only 1.5% of that segment. So it seems pretty safe, although I worry about a situation where a tab room only has access to IE8 and that could block data entry.

**Comment by philipbelesky** [comment]
Also at the same time it might be easier to move to using [a bootstrap app](https://github.com/dyve/django-bootstrap3) rather than just including the core files, to have access to some convenience methods and make updates easier.

**Comment by czlee** [comment]
Oh, that's a tough call. I'm sort of generally of the view that we should keep up to date with the latest of packages we use, but this complicates things a little. I don't really know what versions of IE are used where... I think Microsoft normally by default upgrades IE to the latest version for that OS? Which should mean that most IE8 users are Windows XP users? I might be wrong/be overestimating how many people do what I would do.

**Comment by philipbelesky** [comment]
IE8 was bundled with Windows 7, and is not a forced upgrade, although is in the standard set of Windows Updates. Has ~15% marketshare globally, although as noted before it appears to be a minuscule proportion of our traffic. I'll leave this up as a note to test things after trying out the upgrade. I would be fine with slight visual artefacts as long as key functionality (particularly wrt data entry and draw release) perform correctly.

**Comment by philipbelesky** [comment]
Slight update, apparently the source used for the ~15% figure is largely inaccurate, usage is more around 2-3%, which is much more in line with our analytics data.

**Comment by philipbelesky** [comment]
In addition to bootstrap, most modern front end related things are dropping IE8 support, such as:

- jQuery 2.0+
- Ember 2.0+
- Bootstrap 4.0+

Due to the bloat required to cater to the IE8 javascript model. I also haven't tested the site in IE8 in ages, I assume it probably isn't working very well. As such we should document our supported browsers in a manner that is pretty clear (basically supporting everything over IE8). We should probably also have a banner or something on the site that displays a warning to those on IE8.

That said we should probably ensure the public facing pages aren't horribly broken in IE8. I'm fine with the javascript not working as long as they layout is presentable.

**Comment by philipbelesky** [comment]
Added  in as per 0f054939711c787ad6c940577e35ba914565542f and 67b8e74666fa7ff475bd65b8c86246e5388b707a

**Comment by philipbelesky** [comment]
Slight update, check the past year and 4.44% of our visitors are on IE, and of those, only 2.94% on 8 or lower. So I think these (relatively minimal) warnings should be enough given that.
