### ISSUE TITLE
Form buttons that disable themselves don't re-enable themselves on error

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#227]
Implementing #209 had the effect of making forms unsubmittable if there is an error on submission, where fields check themselves before sending away the POST (e.g. integer fields with min and max values). The button disables itself when the user clicks it, but the form doesn't submit and prompts the user to fix errors before submitting, and the button is still unclickable, so the revised form can't be submitted.

**Comment by czlee** [comment]
This is happening again on the tabroom assistant enter result page.

**Comment by czlee** [comment]
This is happening again on the create tournament page. (To reproduce, enter "0" or "1" in the break size field.)

**Comment by philipbelesky** [comment]
Ok for context the commit that closed this removed `submit-disable` and `data-loading-text` where it was on a submit element within a form that had data that could be invalid. IE it remains on elements that are either links, or are buttons that POST a form but whose form data isn't user editable. It also remains on some forms like the ballot entry forms that have proper front-end validation of data that prevent the button being stuck in an unsubmittable state.

I believe `submit-disable` is being deprecated in bootstrap 4 anyway, so long term should create seperate methods for indicating link-loading and form-submission.
