### ISSUE TITLE
Rewrite views as class-based views

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#228]
On the backburner:
https://docs.djangoproject.com/en/1.8/topics/class-based-views/

Use the below thread as a scratchpad for ideas on how to structure the classes.

**Comment by czlee** [comment]
This is being done on a "change the ones you touch" basis. I'm writing mixins as they're needed. Once most of them are converted, we'll probably put in a concerted effort to convert the rest, then delete utils/views.py.

**Comment by philipbelesky** [comment]
Keeping track:

- [ ] ActionLog
- [ ] AdjAlloc
- [ ] AdjFeedback
- [ ] Availability
- [ ] Breakqual
- [ ] Draw
- [ ] Breakqual
- [ ] Importer
- [ ] Motions
- [ ] Options
- [X] Participants
- [ ] Results
- [X] Standings
- [X] Venues

**Comment by czlee** [comment]
(I edited the above list to add tournaments and remove the duplicate breakqual.)

**Comment by philipbelesky** [comment]
Mental note: a `JsonDataResponseView` class now exists; many of the remaining views are instances fit the use case.

**Comment by czlee** [comment]
done breakqual! finished it as part of #307

**Comment by czlee** [comment]
Done results!

This means we're actually almost there. Motions is mostly done except for the `motions_assign` view, leaving basically three and a bit modules left.

**Comment by philipbelesky** [comment]
Importer has been all migrated; aside from the now-deprecated import views. So, all done then! 🎉🎊🎉
