### ISSUE TITLE
Remove virtualenv from instructions in favour of new built-in venv module

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#230]
Python 3.3 introduced a new module [`venv`](https://docs.python.org/3/library/venv.html), which makes redundant the need for installing `virtualenv`. This also eliminates the need to install `setuptools` and `pip` into the host (non-virtual) environment, which would greatly simplify the Windows installation. After the port to Python 3, we should drop `virtualenv` from our instructions and suggest that local installers use `pyvenv` instead.

Since Python 3.4 is the current version, I'm happy just to say we do not support any Python version earlier than 3.4, mainly because I can't be bothered writing for any earlier Python version.

**Comment by czlee** [comment]
Annoyingly, it turns out Ubuntu 14.04 ships with a broken `pyvenv-3.4`. Here's the workaround:
https://gist.github.com/denilsonsa/21e50a357f2d4920091e#solution-1

Probably questionable whether we should recommend this for Ubuntu 14.04 users.

**Comment by philipbelesky** [comment]
When you get a moment can you check pyvenv works properly on 3.5? If so we can happily drop virtualenv

**Comment by czlee** [comment]
Sure, do we have a deadline on this?

**Comment by philipbelesky** [comment]
No rush. Ideally we would have it updated once ```develop``` is promoted (ie Bengal released) but thats not particularly urgent

**Comment by czlee** [comment]
I haven't actually tried yet, but I'm not sure that Python 3.5 could help: Python 3.4 is distributed with Ubuntu 14.04, but Python 3.5 is not, and with some quick googling I'm not sure that 3.5 is in any of the official package repositories either. We could always make Python 3.5 a requirement and insist that users install it (after all, we do this for Windows), but I'm not sure if we want to ask users to install Python from source, which unless I'm missing something seems to be the only way.

**Comment by philipbelesky** [comment]
Ah I hadn't realise it wasn't on canonical's package repo. Installing from source doesn't seem too complicated (just adding a different source set from what I understand). I don't think its an undue burden for linux users to install a python. Especially given even if they are on 3.4 they need to install a fix for virtualenv last time I checked?. ETA for the Ubuntu version with 3.5 as default seems to be April. 

That said I was using 3.5 is primarily to align with heroku, it's possible that we could run locally with 3.4 and either set heroku to match, or to use 3.5. For OS X users they're still on 2.7.6 even if on the latest OS, so they're going to have to upgrade regardless.

TODOs before Bengal release:

- [ ] Test ```develop``` using python 3.4 on OS X
- [ ] Test ```develop``` using python 3.4 on Linux
- [ ] Test ```develop``` using python 3.4 on heroku
- [ ] Decide whether to keep heroku on 3.5 (supported) or to force it to match to 3.4 (unsupported but probably fine)
- [ ] Update wiki's install instructions

**Comment by czlee** [comment]
I added Windows to that list :stuck_out_tongue:

I don't have a strong inclination about Python 3.5, which is to say, I feel conflicted between my tendency to keep software up-to-date and that to avoid non-trivial installations. I'm inclined to agree that Heroku should take priority, so we should at least support 3.5.

Are there features in 3.5 that we want to use that aren't in 3.4? A quick look through the [what's new](https://docs.python.org/3/whatsnew/3.5.html) list doesn't seem concerning.

Re the original virtualenv question, I'm sort of thinking we should just recommend the use of the workaround in the above link, and live with it until it's ironed out. I have some recollection of observing that pyvenv was much faster than virtualenv? I should double-check this all works at some point.

**Comment by czlee** [comment]
Update:

`pyvenv` seems to have been removed from the standard Ubuntu 14.04 distribution, as in, the command no longer exists, even on existing installations. The above issue is "fixed", of sorts: the catch is, you have to install a new module, `apt-get install python3.4-venv`.

https://bugs.launchpad.net/ubuntu/+source/python3.4/+bug/1290847

This reduces the benefit of switching to pyvenv a bit, but I still hold that we should do it for the ease it creates on Windows.

**Comment by philipbelesky** [comment]
Yea, I think there's also the factor that linux users can be assumed to be relatively comfortable adding new modules.

**Comment by philipbelesky** [comment]
Similarly, is this resolved? It seems like we need to stick with the current caveat/workaround until we can assume nobody is on 14.04 anymore.

**Comment by czlee** [comment]
Yes, except that I haven't tested properly on Windows yet, but that should be under #248.

14.04 is an LTS release, it'll be a long time before that's out of the way (end of life is April 2019). There might be another solution in the meantime though idk.
