### ISSUE TITLE
Add support for standings by number of adjudicators

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#232]
* Add a `num_adjs` field to `TeamScore`.
* Add support for this field to `BallotSet`.
* Populate `NumberOfAdjudicatorsMetricAnnotator`.

**Comment by czlee** [comment]
Just a note, I refactored the standings app a little so now it's in teams.py rather than metrics.py. It should still largely be the same (the refactoring was just to abstract things out to make speaker standings easier), but just a heads-up.

**Comment by philipbelesky** [comment]
Might have a shot at this as in combination with #251. This could then enable Egyptian Mau be a small 1.X release with the main feature being styles support and more major refactors/features would be pushed to 1.X+1. Good idea @czlee? Questions:

- I assume `num_adjs` represents the 'number of votes given to this Team' not 'panel size'?
- Why does `NumberOfAdjudicatorsMetricAnnotator` have an `adjs_per_debate`? From my understanding WSDC is always adjed by a panel of 3, but if we assume that panel sizes are consistent across a tournament, why the need to specify?
       - That said, it might be interesting to see how it would handle having uneven numbers of panels across a draw. Perhaps (assuming a panel size number is also added) it could be expressed as a percentage value of the number of adjs carried? This could be semi hardcoded with a multiplier of 3 such that it creates sensible looking numbers in the usual circumstances. IE `number_of_votes/panel_size * 3` such that it normally produces 1-3 and only has to use decimals when panel sizes are >3.

**Comment by czlee** [comment]
If you're doing it for fun I guess :laughing:

- I'm not sure what the first question means; the string `"num_adjs"` is just the key used to identify the number-of-adjudicators metric annotator (_e.g._ the value stored in the preferences table in the database).
- The idea was that we _wouldn't_ assume that panel sizes are consistent across a tournament, like you say. So the idea was that you would just scale it to the desired size, _e.g._, if `adjs_per_debate == 3` then a solo judge would count as three votes, using the formula you describe, but with `adjs_per_debate` instead of `3`.
    - To complicate things more though: I think someone mentioned to me that at some (Asian?) tournaments, solo judges can choose to "split themselves" 2-1. Which is another exercise altogether…

**Comment by philipbelesky** [comment]
Sorry in the first question I meant `adjs_per_debate` not `num_adjs`. In relation to this, is it worth hardcoding it to 3 or adding a preference to it? I'm leaning towards hardcoding, as exceptions seem rare (and it would work regardless, just maybe look a little odd). Definitely not interesting in supporting this whole 'split yourself' business.

**Comment by philipbelesky** [comment]
Context for the commits on the current feature branch: I have `TeamScore` both an `votes_given` and a `votes_possible` — the idea being people can manually edit those in the database aera to accomodate any weird edge cases such as 'splitting themselves'.

**Comment by czlee** [comment]
Ah, I see, that makes sense. Then I guess `BallotSet` (in result.py) should learn to calculate those?

**Comment by czlee** [comment]
Oh, you did that part too, I see it now, cool. Looks good :+1:

I'll look at refactoring it into a single SQL query when I get a chance but if it's functional then feel free just to roll it in and I'll performance-enhance it later.

I'm guessing it's not worth writing a data migration to populate existing databases with correct numbers, right? It wouldn't be very hard but I also would like to avoid writing unhelpful migrations in principle.

**Comment by philipbelesky** [comment]
Yea I don't think the data migration is really worth doing, if someone really is curious about redoing the standings WSDC style on an existing tournament they can figure it out themselves.

**Comment by philipbelesky** [comment]
Closed in merge c81fde904fd3ce9397bf549740bb42d2dab198f0

**Comment by czlee** [comment]
The SQL-based annotator was trialled in 58de9ba5fe2d9e57553b6602a7292cc8120ca250 and completed as of 2c47ef79fb6f15b13cffc69a4582c21b8e94f04d (see discussion in ac15e78895649780cf7381150e366693ad29e1e8)
