### ISSUE TITLE
Team and adjudicator pages

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#233]
It would be nice to have pages that lists everything you'd want to know about a team and/or adjudicator. That is, for a team, a page that displays all results of that team so far, including their oppositions, adjudicators, motions and (for debates with results) splits. This could work both during and after the tournament, and they can just be the same page.

There's no reason to make this account-based—it is all information that is public anyway. However, it could include a link to feedback/ballot entry, depending on relevant public submission configuration settings.

**Comment by czlee** [comment]
Removing low-priority tag: I'd like to have a crack at this for Australs this year. There's not much to it conceptually, but probably involves a bit of labour to do right.

**Comment by philipbelesky** [comment]
Ok, cool. Just some thoughts:

- It would probably be most accessible as a kind of enhanced version of the speakers popover we current have. So rather than hovering to see speaker names you would instead click to load a modal popup that would show speaker names along with results, etc. This would load on-demand, and the same view could be used to make a standalone page
- The above proposal is probably best coded as a Vue component. So if you create a view that spits out a json file with an appropriate data structure I can go ahead and implement it (or you could have a crack at creating a Vue component for it). 
- Some simple graphs would be nice if you can think of items that could be usefully visualised. We have Vue components up or in progress for a simple line chart (feedback overview) and donut chart (diversity tab) but I could add in some other types if needed.

**Comment by czlee** [comment]
Detailed list of information to include:

### Team page

Info about team
- Team name
- Institution
- Names of speakers
- Break category eligibility

Current round
- Venue
- Side
- Opposition
- Motion(s)

Results of past rounds
- Round
- Venue
- Side
- Opposition
- Result (win/loss)
- Adjudicators, and whether **each one** called a win or a loss (this is different from most pages, where only *splitting* adjudicators are highlighted)
- Motion (the one actually chosen)
- After the tournament, a link to the scoresheet
- _Need to allow for byes/non-participation_

### Adjudicator page

Info about adjudicator
- Name
- Institution

Current round
- Venue
- Teams (aff and neg)
- Motion(s)

Results of past rounds
- Round
- Venue
- Teams (aff and neg)
- Result of debate
- Result called
- Result each other adjudicator called
- Motion (the one actually chosen)
- After the tournament, a link to the scoresheet
- _Need to allow for rounds where they didn't judge_

### Notes

1. I've written "side and opposition", it could equally just be "affirmative team and negative team", which would be easier to extend to BP later (if we ever do), and also more consistent with other draw layouts. But I think the salient question is, which is easier for teams to read and use.

2. Once team pages exist, the existing Vue component for teams could link to that page! This would be useful, for example, for navigating from team pages to other team or adjudicator pages. Or there could be a link from the team info popover that currently lists speakers' names.

3. I don't currently have any ideas for visualizations that would make sense _during_ the tournament, but after a tournament there could be speaks graphs I guess? Not really sure.

**Comment by philipbelesky** [comment]
Misc thoughts:

- Only "Results of past rounds" seems to need a table; "Current round" has so few items it could probably just be a bunch of headings
- This may be expensive to generate but it would be kind of fun (and possibly cruel) to have a graph of each team's ranking at each round; ie a kind of line chart where x=round and y=ranking to track one's progress. This is assuming tab has been release or the live standings page is on.
- For both adjs and teams it would be great to have a progress counter on the number of feedbacks submitted vs feedbacks owed. Even better would be if this in the "Results of past rounds" for extra public shaming potential. 
- Similarly it would be interesting to run the numbers on a speaker's average speaker score, and perhaps an indication of variability (standard deviation?). As before a line chart tracking someone's relative speaker ranking would also be super interesting.
- Another quasi-interesting stat would be almost a Worlds Schools style 'number of adjudicators carried' — ie for each team how many wins/losses did they have according to ballots; for adjs how often were they in the majority/minority.
- Another quasi-interesting stat would be to see a breakdown of people you debated/adjudicated by gender and region (perhaps measured against the baseline numbers). 
- If some of the above information does get implemented it depends on particular `preferences` or the tab being released; given this it would be nice to also have an admin only version of the page that displays all the information regardless.

**Comment by czlee** [comment]
* Agree re only past rounds _needing_ a table, though it's not obvious to me whether or not a table might make the other stuff easier to read. I suspect it might be (headings in left column, info in right column), but maybe that's worse for mobile phones.
* The standings vs time stuff would be expensive lol, maybe this info should be cached separately every few (say, 10) minutes, so that eight sets of standings don't have to be generator each time? 
* For most summary statistics (not things vs time), you could figure them out in your head just be scanning the detailed info on the screen—that is, they'd be arguably (with statistical caveats) be interesting for quick comparisons between many speakers/adjudicators, but would probably add little for a _single_ team/adj when you can just see everything, particularly if we colour-code things like which way adjudicators voted.
* Agree re admin-only version of the page, in fact, implementation-wise it'd be easier to do that first I guess, then add the display logic for the public version.
* For unsubmitted feedback, we could just have a section dedicated to it, that displays only if feedback is incomplete (so it looks "wrong", like an "error") :wink:
* The past results table (below) might be a bit crowded, any ideas?
* If you have ideas for emoji to replace "aff" and "neg" that might work too. (We should probably keep web accessibility in mind with all of this, _i.e._ suitable alternate text, though with Vue maybe that won't be too hard.)

Updated list:
### Team page

**Info about team/adjudicator:** Name, institution, names of speakers, break category eligibility
**Current round:** Venue, side, opposition, motion(s)
**Unsubmitted feedback:** Display only if more than zero, show unsubmitted targets, links only if non-random URLs are being used, maybe highlight in some bold colour
**Results of past rounds:**

| Round | Venue | Side | Opposition | Result | Adjudicators | Feedback | Motion | Scoresheet |
|-----|----|----|----|----|----|----|----|----|----|
| R1 | G01 | aff | Auckland 1 | ⬆️ | ⬆️ Billy Griffin<br />⬇️ Ramona Cobb<br />⬆️ Holly Howard | All in | Christmas | View ballot |

**Speaker scores:** Graph with four lines, one for each speaker (by speaker, not by position), and one for reply speech (no matter who gave it, this might require a secondary _y_-axis, or maybe just separate axes altogether)

Possibly other visualizations, like speaker and team ranking over time.

### Adjudicator page

**Info about adjudicator:** Name, institution
**Current round:** Venue, teams, motion(s)
**Unsubmitted feedback:** Display only if more than zero, show unsubmitted targets, links only if non-random URLs are being used, maybe highlight in some bold colour
**Results of past rounds:**

| Round | Venue | Affirmative | Negative | Winner | Call | Other adjudicators | Feedback | Motion | Scoresheet |
|-----|----|----|----|----|----|----|----|----|----|
| R1 | G01 | Auckland 1 | Monash 1 | aff | neg | Billy Griffin (aff)<br />Holly Howard (aff) | 1 unsubmitted | Christmas | View ballot |

**Comment by philipbelesky** [comment]
- On standings queries/expensive queries it could be interesting to abstract out the task of generating speaker standings so that it could be cached once a round has finished. In theory this could be cached forever as long as new or edited SpeakerScores invalidate it. 
- I think those summary statistics *could* be calculated mentally; but most people would not think to do so, and it would be a bit of mental overhead to do all of the calculations. I think it would be interesting even if they aren't comparative; like a profile or stats page in some sort of video game having more numbers to measure progress is kind of just inherently interesting. 

For the team page my semi-redesign of the results page I just have a 'results' column that takes the form of 

| Result |
| --------- |
| ⬆️ vs Princeton 2 (Aff) |

...that combines opposition/side/result. The other suggestion would be that for the "feedback" columns to (if easy) list which items of feedback have or have not been submitted. For teams this might just be a ✔️/❌, but for adjs it would be nice to have:

| Feedback |
| --------- |
| ✔️ On Trainee Name <br> ❌ On Panelist 1 Name <br> ❌ On Panelist 2 Name |

...in the table itself, that mirrors the "Other adjudicators" cell adjacent. Then the "Unsubmitted feedback" feedback section could just be a success/danger alert saying the number of ballots not submitted.

**Comment by czlee** [comment]
I started adding links to the team and adjudicator summary pages from places where team names and adjudicator names exist, for example, the list of adjudicators for a given debate. This sort of results in a sea of blue:
![image](https://cloud.githubusercontent.com/assets/1725499/16359846/002eeba0-3afa-11e6-9b25-777c961d30da.png)

I wonder if summary links should be colored differently, like a darker color, or something? Or maybe we just shouldn't put them everywhere—it's a bit of a nuisance, since in most of these cases you have to construct `<a href>` tags manually in the Python code for generating table columns (as in, you can't just add a link to the cell dict).

**Comment by philipbelesky** [comment]
Hmm, is there a reason it can't be passed to the `link` attribute for the cell? The `Cell.vue` does check for a `cellData['link']`.

I think the preferred option would be to only show the link on hover, either as part of a [tooltip](http://getbootstrap.com/javascript/#tooltips) or [popover](http://getbootstrap.com/javascript/#popovers) along with the standard meta data (a team's speakers, and adj's institution).

**Comment by czlee** [comment]
Where there is more text in the column than just the team or adjudicator name (or whether there are multiple adjudicators' names), you don't want to link the entire cell contents, you just want to link the name. So the first column in the above image uses `cell['link']`; the third and fifth columns don't. (The fifth column definitely can't; the third column could if we were prepared to tolerate highlighting "vs" but I think that'd be confusing.)

Do you mean to show the link _in_ the tooltip? We could also have a CSS class for summary links that will show the text as identical to any other text (in particular, does not color it) until rollover.

**Comment by philipbelesky** [comment]
Hmm, so either we can find a way to add more detailed text elements (with individual links) or we could kind of accept that each cell should have a single highlight, and then push all possible highlight information into a single popover element for that cell. I think the latter is probably preferable. 

So for example in the first column one, the popover would just have a title (the team's full name) along with speaker names and a link to 'view record'). 

For the third column a textual explanation of the icons "X won vs Y", along with extra sections to "View Record of X" and "View Record of Y". 

For the fifth column I think its probably easiest to be consistent and have a single popover for all adjs, with the popover having sections for each of the adjs. IE:

Full Name of Adjudicator (Chair)
*From Full Institution Name*
*View Record Link*

Sounds good? There may need to be some constructor methods for building popover content in tables.py (these could be section based with a dict similar to that of a `Cell`). But it seems preferable to have a single source of bringing up information related to the data in cell.

**Comment by philipbelesky** [comment]
Out of scope musing: personalised team and adj pages would also be an interesting way to provide for a controlled release of speaker tabs and (potentially) adjudicator feedback. If they were put behind a 'secret' URL you get around the 'we dont want to show all speaker's scores, but we do want interested parties to be able to view their own performance' issue.
