### ISSUE TITLE
Investigate VM/docker based local install methods

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#241]
Just leaving these here as a mental note to check back in on them later, once they better support Django and Heroku
- https://ottoproject.io
- https://nanobox.io

Both are potential candidates for a properly virtualised 'magic' local install, and potentially similarly easy deployments. Docker based solutions may also work.

**Comment by philipbelesky** [comment]
Something I just came across: creating a virtual heroku instance using docker: https://devcenter.heroku.com/articles/docker

**Comment by philipbelesky** [comment]
Ping @czlee this is all merged now! I've tested the instructions on OS X, Windows 10, and Ubuntu 14.04. If you want to try it on Windows, just a heads up that it may not work if Windows itself is in a VM (I had to restart and boot it natively).

**Comment by czlee** [comment]
Docker doesn't install on Windows Home editions, you have to install Docker Toolbox instead?

**Comment by philipbelesky** [comment]
Ah, I didn't see that Windows Home was missing from that list. I think Docker Toolbox should be fine (ill try it myself in a couple of days).

**Comment by czlee** [comment]
On Powershell:
```
C:\Users\czlee\git\tabbycat>docker-compose up
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 64, in main
  File "compose\cli\main.py", line 116, in perform_command
  File "compose\cli\main.py", line 848, in up
  File "compose\project.py", line 379, in up
  File "compose\project.py", line 557, in warn_for_swarm_mode
  File "site-packages\docker\api\daemon.py", line 73, in info
  File "site-packages\docker\utils\decorators.py", line 47, in inner
  File "site-packages\docker\api\client.py", line 175, in _get
  File "site-packages\requests\sessions.py", line 488, in get
  File "site-packages\requests\sessions.py", line 475, in request
  File "site-packages\requests\sessions.py", line 596, in send
  File "site-packages\requests\adapters.py", line 423, in send
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request
  File "httplib.py", line 1042, in request
  File "httplib.py", line 1082, in _send_request
  File "httplib.py", line 1038, in endheaders
  File "httplib.py", line 882, in _send_output
  File "httplib.py", line 844, in send
  File "site-packages\docker\transport\npipeconn.py", line 31, in connect
  File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 50, in connect
pywintypes.error: (2, 'WaitNamedPipe', 'The system cannot find the file specified.')
docker-compose returned -1
```

On Docker's Quickstart Terminal (the one based on MINGW64), it starts fine, but when I try to load a page:
```
web_1  | [2017-02-08 10:17:45,438] ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: '192.168.99.100:8000'. You may need to add '192.168.99.100' to ALLOWED_HOSTS.
web_1  | ERROR:django.security.DisallowedHost:Invalid HTTP_HOST header: '192.168.99.100:8000'. You may need to add '192.168.99.100' to ALLOWED_HOSTS.
```

One thing: I already have VirtualBox, so I unchecked it during the Docker Toolbox installation. It proceeded to create a new VM for me in my existing VirtualBox. I don't think this is a problem, but mentioning just in case.

**Comment by philipbelesky** [comment]
Hmm, so we could add that IP to `ALLOWED_HOSTS`; or just set all hosts to allowed hosts. Could you try that and see if it fixes the page loading?

I'm not sure what to do with the `docker-compose` error; does it prevent the site from running?

**Comment by czlee** [comment]
I tried both that and `INTERNAL_IPS`; neither helped. I'm just changing local_settings.py though, not sure if Docker copies everything over when on first set-up (so that my changes won't be reflected in the site).

From Powershell, the site doesn't run; whether that error is the cause I don't know.

At the point where Docker already requires VirtualBox, I'm wondering if we could just (eventually) have a build system that compiles all our dependencies into a VM of its own, and for the "fast" version to be just for users to install VirtualBox and open a standard VM image? Or, if Docker's more user-friendly, can we wrap things in a system image for Docker?

**Comment by philipbelesky** [comment]
Yea, you need to do a `docker-compose build --no-cache` to remake the image. During development I often had to remove the existing docker files and restart the service to ensure changes were made. Hopefully that will fix the issue? 

Currently our docker setup builds of the `python` and `postgres` images; it's definitely a possibility to wrap everything up into a `tabbycat` image. We could then also make use of the GUI into docker. I haven't used VirtualBox, but one of the advantages of `docker-compose` is that it can manage multiple images and coordinate between them — having to merge the python/django and postgres images seperate at the moment could be a hassle. Docker also seems to have a better supporting infrastructure for managing the VMs images; as well as opening up future options for using the VM as an online deployment option (heroku already supports this).

That said, to the extent this is an endemic Windows Home issue (that we can't solve via setting `INTERNAL_IPS` or some other issue, I presume Windows Home support is on the Docker roadmap so we could wait it out.

**Comment by czlee** [comment]
Re the second paragraph, wait, wouldn't we just compile everything into a single image? There might be some gap in my understanding of what an "image" is in the Docker context; I was thinking system image (like a VM image).

**Comment by czlee** [comment]
Ah, also, what I actually meant was: Rather than have users build the docker image, can we just do it ourselves and then include it as a release deliverable, so that people just need to download the image and run it?

**Comment by philipbelesky** [comment]
Yes; although part of the promise of Docker should be that there is no difference between having a VM compiled as an image and creating a set of instructions to then create the image needed (the latter is much easier to keep current with the project). Local installs are presumably relatively niche, so I'm happy to have this as a solution confined to OSX/Linux/Windows-not-Home (assuming the issues are just with Windows-Home).

**Comment by czlee** [comment]
Oh, interesting. We don't really have the continuous integration tools for this right now (but I'm sure they shouldn't be too hard to find), but in my head I was thinking of a system that just runs the Docker build on every commit (once pushed to the server), just like how Travis runs tests now.

**Comment by philipbelesky** [comment]
Yea that's probably possible though it seems like most of the docker ecosystem and distribution mechanisms work on distributing the build files themselves.

**Comment by czlee** [comment]
I see, interesting.

**Comment by philipbelesky** [comment]
- [ ] Update Windows Home instructions
- [ ] Recruit a few more testers to try it out on different platforms

**Comment by czlee** [comment]
Done Windows Home instructions.

**Comment by czlee** [comment]
Also, reference for claim that Windows 7 and higher are supported for Docker Toolbox: https://docs.docker.com/toolbox/toolbox_install_windows/#/step-1-check-your-version

**Comment by philipbelesky** [comment]
Going to tentatively close this as 'generally complete'; I'm sure there will be edge cases soon enough though.
