### ISSUE TITLE
Note on pipelines and Bengal timeframe/release

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#245]
Quick misc thoughts on release cycles for the next few months:

- Obviously its 3 vs 3 season again and we are definitely being used at AU Easters and Australs.
- I'd like to do a solid beta test of everything on ```develop``` at a tournament on the 19-22 Feb. 
- Presuming that goes well I think it would be a good candidate for a Bengdal release. I'm ambivalent as to whether thats 0.8 or 1.0, but I would like to have a ```master``` that includes the recent major refactors because:
- I intend to use [heroku's pipelines feature](https://devcenter.heroku.com/articles/heroku-labs-new-pipelines) to setup a dozen or so instances for institutions I know and ideally be able to automatically deploy new releases to all those instances once they hit master. In order to set this up I require #221 and #224 to be in place otherwise future updates will be a nightmare.

Obviously there will probably be a few more releases pre-Australs/Easters, which makes doing a major release in the next month or so slightly awkward as everything attached to the milestone may not be complete. However I don't think any of the planned changes...

- Integrate the adjumo allocation UI
- Integrate new cap rules
- Break rounds GUI
- Config refactors
- Standings refactors
- Various WADL updates
- Etc

... are breaking as per our versioning convention. So they should fit well as point releases.

**Comment by philipbelesky** [comment]
Note: I've added you to a private repo on my account (setup as a duplicate not a fork; I couldn't setup the pipeline for a repo that wasn't attached to my account) that is currently setup to automatically deploy from ```master``` to tabbycatdebate.herokuapp.com (not that this will happen anytime soon) — let me know if thats a bad idea. If you still have a develop/test instance we could set that up to deploy from ```develop```. If you're interested I could add you to the pipeline app on heroku, but I think we will need to setup an organisation for that purpose

**Comment by czlee** [comment]
I'm happy with all of this. Also happy in principle to start an organisation if you want to, but I don't have any particular need to be in on the pipeline app just yet unless you think I do.

I have a moderate preference to stick to 0.8 rather than 1.0, since there are structural refactors in the pipeline, but agree that in principle it is possible to do the config and standings refactors without breaking backwards incompatibility (and I'd probably attempt to do so whether we're on 0.8 or 1.0).

**Comment by philipbelesky** [comment]
Closing as there's not much more to discuss (we decided on 0.8)
