### ISSUE TITLE
Move documentation to readthedocs

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#246]
At present its slightly annoying that the wiki pages are not checked in code, and as such cannot track particular changes in particular branches. IE I would like to be able to writeup the new setup instructions in ```develop``` as I do them, and have them automatically deploy to the official docs once ```master``` merges in ```develop```. As far as I can tell it isn't possible to have different branches with a github wiki. There are also some hassles in maintaining/organising sections with a wiki.

[readthedocs.org](readthedocs.org) seems pretty solid and widely used. It would require us to create a ```docs``` folder in the directory. One or two dependencies would need to be installed to view rendered documentation locally, but this wouldn't be necessary for users. We can set it up so that it creates versions that are tied to releases, and that these automatically update on deploys. Having a web presence outside of github might be a good idea for visibility as well. Sounds good?

**Comment by czlee** [comment]
I take it this supersedes our github.io plan?

**Comment by philipbelesky** [comment]
Github.io runs off jekyll which stores its files in a separate ```gh_pages``` branch. So while it would be nice to have the extra customisation it allows (although that does mean more work setting up a website template) it isn't as easy to version documents in a way that is automatic and tied to releases. So perhaps we could migrate there long term once the API is super stable and we have time to sink into making a nice site, but I think readthedocs is superior for now.

**Comment by czlee** [comment]
Legit. Sounds good to me.

**Comment by czlee** [comment]
Let me know when you want me to write up the new installation instructions for Linux and Windows?

**Comment by philipbelesky** [comment]
Sure, I'd guess Bengal is at best a Feb target, so no rush.

**Comment by czlee** [comment]
Are you keen on migrating (eventually) to reStructuredText as well? It seems to be more powerful, *e.g.* it supports warning boxes, which I've sort of hacked into Markdown/MediaWiki using manual table formatting.

readthedocs seems to support reST and Markdown simultaneously, so I'm thinking more as a practice for new/rewritten documents (like the installation instructions, when I get to them).

**Comment by philipbelesky** [comment]
I'm pretty committed to markdown. But being irrationally committed to writing everything in Markdown is kind of my deal. 

I had attempted a [provisional style guide](https://github.com/czlee/tabbycat/blob/develop/docs/developer/documentation.md) and have been converting warnings from table elements to blockquotes with a bolded warning. IE

> *__Note:__ This is a note of some kind. We can style it with CSS if it needs more pizzaz*

```> *__Note:__ This is a note of some kind. We can style it with CSS if it needs more pizzaz*```

Readthedocs does support reST and Markdown simultaneously, although thats through setting up Sphinx locally. However it also supports deploying from [MkDocs](http://mkdocs.readthedocs.org/en/stable/) (which is what I've setup) which has fewer dependencies, less setup, and can previous the readthedocs theme locally. In theory it shouldn't be hard to switch over to using Sphinx and co-mingling markdown/rest but I don't see any need for it at the moment.

**Comment by czlee** [comment]
Okay. I'd quite like to move to reST - I've often felt constrained when writing documentation about what Markdown is able to provide. How hard would it be for me to persuade you? I don't think we need to translate existing documents, I just mean in general with writing new ones or when we do rewrites. I'm willing to take the Sphinx overhead if it makes writing rich-format documentation easier.

**Comment by czlee** [comment]
(If you don't want to do the actual effort of putting the infrastructure in place then I can do it next time I look at documentation.)

**Comment by philipbelesky** [comment]
What is constraining within markdown / what about sphinx makes it easier? I've only looked into it a little, but it seems reST and markdown have similar capabilities in terms of their synxtax?

**Comment by czlee** [comment]
For me it's mainly directives. I've found warning and note boxes quite important when writing documentation, both to draw attention towards things and to make it obvious what to skip. And I've found blockquotes poor for this purpose: for warnings, they have the opposite effect of what I want.

**Comment by czlee** [comment]
As I understand reST is also a lot more customizable, but I've probably spent about as much time looking into it as you have. [Readthedocs](https://read-the-docs.readthedocs.org/en/latest/getting_started.html#in-markdown) lists two main examples: Directives (like I said) and [inline markup](http://www.sphinx-doc.org/en/stable/markup/inline.html#inline-markup).

I used to think our documentation was straightforward enough not to need such features, but I've felt constrained already and presume if we're stepping up our documentation efforts it'll only get worse, so thought I'd take the opportunity while we make the switchover to start it now? I haven't used reST before, but I do get the feeling it's a lot less lightweight than Markdown.

**Comment by philipbelesky** [comment]
Right, I'm still slightly unclear of what the use cases for directives or inline markup would be here. If the problem is with the presentation layer (warnings not being noticeable enough) I'd prefer to solve that with CSS, or at worst, inline html. That said reST largely seems to be a superset of markdown so happy to have it setup even if we don't use it or rarely do so.

**Comment by czlee** [comment]
Inline HTML is exactly what I was using—but I was using it quite often, and it was getting annoying to copy-and-paste :stuck_out_tongue_closed_eyes:

Even with CSS, we'd need to define classes for the purpose, which Markdown doesn't natively allow for (in effect meaning we revert to HTML to specify divs), and this is what directives are for in reST?

**Comment by philipbelesky** [comment]
Yea, although having gone through some of them I was able to get the same HTML output using the standard feature set. I still think for the purposes of warnings we could just style the generic ```blockquote``` element without the need to add inline html/classes. Anyway to dry and draw this to a close, the rest/markdown syntax for basic elements are largely compatible, so am happy with a solution where the files are ```.rst``` and use standard markdown formatting alongside the occasional directive or other reST feature as needed.

**Comment by czlee** [comment]
As a hypothetical, would Markdown allow different types of `blockquote`s? I was hoping to have different directives for warnings, cautions, notes. For example, I want warnings to have attention drawn towards them, and notes to have attention drawn away. And there are some warnings I'll want to be in like bold red, like, when they're to do with security.

Is the effect of your (actual) solution that we're using reST? I'm not 100% sure on how different Markdown and reST are.

**Comment by philipbelesky** [comment]
Ah no, not unless they were wrapped in a class, so that is probably better as a directive. [They are largely compatible](https://gist.github.com/dupuy/1855764) although links and tables will require a few tweaks. 

At the point we are using reST for some stuff its probably better to have all the files be ```.rst``` and conform to reST syntax where it differs from markdown.

**Comment by philipbelesky** [comment]
Have finished going through and cleaning/updating/standardising the doc files. Stuff still on the critical path for release:

- [ ] Update screenshots with any new interface changes
- [ ] Online Data details to be filled out
- [ ] Adjudicator Allocation details to be filled out
- [ ] Contributing needs to be fleshed out
- [ ] If we are switching to Sphinx, set it up to import AUTHORS.md / CONTRIBUTING.md / etc contents into the equivalents in /docs/
- [ ] Double check install instructions and python version instructions

**Comment by czlee** [comment]
I'll start the work to migrate to Sphinx today, on a new branch.

**Comment by philipbelesky** [comment]
@czlee when you get a sec, could you signup to readthedocs.org and send me your username? I'll need to add you as a maintainer to the project so that you can test the sphinx setup deploys properly.

**Comment by philipbelesky** [comment]
- [ ] Fix literals on read the docs

[This looks promising](https://blog.deimos.fr/2014/10/02/sphinxdoc-and-readthedocs-theme-tricks-2/)

**Comment by philipbelesky** [comment]
Also is this fully merged now and the branch stale? I tend to think of open feature branches as TODO items so aggressively delete them (on the github repo) when done.

**Comment by czlee** [comment]
Branch was definitely stale, sorry, forgot to delete.
