### ISSUE TITLE
Draw tests failing due to python3.5 OrderedDict changes

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#247]
Logs at the end. This probably breaks the draw in some circumstances although I'm not precisely sure which ones. In python2 items() would return a copy of dicts list of key/values whereas in python3 it returns view objects that update as the dict does.

I've tried a few approaches to fixing this but it seems like the new OrderedDict implementation is are now immutable which means a more substantial rewrite is needed. I'm not super confident with the code so would prefer @czlee does it.

That said this problem doesn't exist on 3.4.3 and in light of #230 I think its best to stick for 3.4.3 particularly if this issue requires a substantial rewrite or you don't have the time. 3.4.3 isn't officially supported on heroku but I don't think it should be a problem. 

```
======================================================================
ERROR: test_intermediate_brackets_1 (Sites.tc_wadl.draw.tests.test_draw.TestPowerPairedWithAllocatedSidesDrawGeneratorPartOddBrackets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/philip/Sites/tc_wadl/draw/tests/test_draw.py", line 635, in test_intermediate_brackets_1
    self.bracket_resolve_odd("intermediate1", expecteds)
  File "/Users/philip/Sites/tc_wadl/draw/tests/test_draw.py", line 510, in bracket_resolve_odd
    self.ppd.resolve_odd_brackets(self.b2)
  File "/Users/philip/Sites/tc_wadl/draw/generator.py", line 477, in resolve_odd_brackets
    return function(brackets)
  File "/Users/philip/Sites/tc_wadl/draw/generator.py", line 815, in _intermediate_bubbles_1
    for unfilled_points, unfilled_pool in unfilled.items():
RuntimeError: OrderedDict mutated during iteration

======================================================================
ERROR: test_intermediate_brackets_2 (Sites.tc_wadl.draw.tests.test_draw.TestPowerPairedWithAllocatedSidesDrawGeneratorPartOddBrackets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/philip/Sites/tc_wadl/draw/tests/test_draw.py", line 687, in test_intermediate_brackets_2
    self.bracket_resolve_odd("intermediate2", expecteds)
  File "/Users/philip/Sites/tc_wadl/draw/tests/test_draw.py", line 510, in bracket_resolve_odd
    self.ppd.resolve_odd_brackets(self.b2)
  File "/Users/philip/Sites/tc_wadl/draw/generator.py", line 477, in resolve_odd_brackets
    return function(brackets)
  File "/Users/philip/Sites/tc_wadl/draw/generator.py", line 869, in _intermediate_bubbles_2
    for unfilled_points, unfilled_pool in unfilled.items():
RuntimeError: OrderedDict mutated during iteration

======================================================================
ERROR: test_pullup_invalid (Sites.tc_wadl.draw.tests.test_draw.TestPowerPairedWithAllocatedSidesDrawGeneratorPartOddBrackets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/philip/Sites/tc_wadl/draw/tests/test_draw.py", line 518, in test_pullup_invalid
    self.assertRaises(DrawError, self.ppd.resolve_odd_brackets, self.b2)
  File "/Users/philip/.pyenv/versions/3.5.0/lib/python3.5/unittest/case.py", line 724, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/Users/philip/.pyenv/versions/3.5.0/lib/python3.5/unittest/case.py", line 176, in handle
    callable_obj(*args, **kwargs)
  File "/Users/philip/Sites/tc_wadl/draw/generator.py", line 477, in resolve_odd_brackets
    return function(brackets)
  File "/Users/philip/Sites/tc_wadl/draw/generator.py", line 815, in _intermediate_bubbles_1
    for unfilled_points, unfilled_pool in unfilled.items():
RuntimeError: OrderedDict mutated during iteration

----------------------------------------------------------------------
```

**Comment by czlee** [comment]
OrderedDict was [reimplemented in C](https://docs.python.org/3/whatsnew/3.5.html#collections) in Python 3.5. There's nothing specific about this issue in the what's-new documentation but it could be related to that. In any case, it seems like a bug if I was somehow assuming that I could modify a container while iterating through it - that's generally frowned upon anyway. It wouldn't surprise me if they had just gotten stricter in enforcing it.

It's a nontrivial fix to verify, but that's what unit tests are for, I guess...

**Comment by czlee** [comment]
We should still be good to run on Python 3.5 on Heroku, or at least, this shouldn't stand in its way.

Right now I'm of the view that we should just support both Python 3.4 and Python 3.5 until support for Python 3.5 improves, both with win-psycopg2 and with Linux distributions.

**Comment by philipbelesky** [comment]
Is this not a problem for the draw proper? Given the error was in ```generator.py``` I assumed it was likely a problem for the actual draw process, not just the test?

**Comment by philipbelesky** [comment]
Errr nvm, just saw that there was a fix commit. I assume this means 3.5 is no longer blocked?

**Comment by czlee** [comment]
Correct.

I haven't tested the fix other than to ensure the test passes, but with the nature of intermediate bubbles it is easiest (as always) for adj cores just to be vigilant when they draw a round that uses intermediate bubbles.

**Comment by czlee** [comment]
By the way, we should be able to revert 6974a50e95e3e900fd12c1b9acde00eea75f4cd6, right?

**Comment by philipbelesky** [comment]
Um, yes, I don't think there were any other issues. So we officially support 3.4 or 3.5 is that right?

**Comment by czlee** [comment]
Yeah, I'm happy to support both until win-psycopg2 is updated.
