### ISSUE TITLE
Notes about Python 3 on Windows

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#248]
Making a note for documentation:

* The default install path has changed to . I assume this is fine, but haven't tested it.
* The "Add to PATH" checkbox is now in the first step.

![python35windows](https://cloud.githubusercontent.com/assets/1725499/12196683/9285070c-b5b5-11e5-9d2a-7fe75b25c02e.png)

This makes life a lot easier. As a consequence, when we get round to documenting this, I'm inclined just to support only Python 3.5, and to advise Python 3.4 users to continue on unaccompanied if they don't want to upgrade.

**Comment by czlee** [comment]
Problem:

win-psycopg2 doesn't support Python 3.5 yet:
http://www.stickpeople.com/projects/python/win-psycopg/

I think this might be a dealbreaker. I haven't actually tried it, but I'm not sure that I want to.

**Comment by czlee** [comment]
`pip install --upgrade pip` should be changed to `python -m pip install --upgrade pip`.

**Comment by czlee** [comment]
`easy_install http://www.stickpeople.com/projects/python/win-psycopg/2.6.1/psycopg2-2.6.1.win32-py3.4-pg9.4.4-release.exe`

`easy_install http://www.stickpeople.com/projects/python/win-psycopg/2.6.1/psycopg2-2.6.1.win-amd64-py3.4-pg9.4.4-release.exe`

**Comment by czlee** [comment]
`pip install -r requirements_common.txt` might need to be `python -m pip install -r requirements_common.txt`, but not sure (it doesn't say so in pip docs but definitely isn't harmful)

**Comment by czlee** [comment]
I had a problem with win-psycopg and then reinstalling it seemed to help, no idea why, mental note to try again before updating docs...

**Comment by philipbelesky** [comment]
Should this be closed? Seems like we've opted for 3.4 on Windows.

**Comment by czlee** [comment]
I was gonna close it after I'd tested the instructions properly.
