### ISSUE TITLE
Consider addressing flake8 issues

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#250]
```python
pip install flake8
flake8 . --exclude=venv/,*/migrations/
```
...reports around 3,000 style guide issues (mostly based on [PEP8](https://www.python.org/dev/peps/pep-0008/) I believe. I don't think these are really important, but to the extent there are generalised rules for formatting we should pick those in instances where there are not good reasons to be inconsistent. 

Depending on your thoughts, we could try running the whole project through an automated linter, such as [this one](https://github.com/hhatto/autopep8). It would likely make some code less readable (where there were good reasons for a particular line length say) but if we did eliminate most of the flake8 warnings it would be easier to enforce consistency going forward.

**Comment by philipbelesky** [comment]
Having played with it a little, [yapf](https://github.com/google/yapf) looks slightly smarter and with more resources behind it. It would be nice to have a consistent maximum line length, although I would miss aligning assignments as per the last bullet point [here](https://www.python.org/dev/peps/pep-0008/#pet-peeves).

**Comment by czlee** [comment]
I might have been using some conventions that are slightly different to PEP8 (which strictly speaking only applies to the Python standard library), though at the same time I have also sometimes been rearranging code to get it to conform more closely with some parts of PEP8. Just pointing this out because it might explain some of the differences.

For that reason, I might need some convincing to catch on to an automated linter.

**Comment by philipbelesky** [comment]
Ok, maybe this is better thought of as a series of questions:

1. Do we need some sort of style guide for the project? Or just keep going as-is (ie adhoc)
2. If we do, given that PEP8 is the defacto python stye guide, which parts of it do we want to adhere to?
3. Should we make use of automated tools to highlight style guide errors (ideally they would be configured to match what we specify in 1/2)
4. Should there be a one time conversion (automated or not) to reformat along the lines of 1/2

My general thoughts are I'd like some of the more basic recommendations of PEP8: notably line lengths (wouldn't mind 100/120 over 79, but w/e), consistent before/after class/function spacing, some other small things. It should be possible to configure a tool to enforce those. 

Perhaps the best way to approach all of the above is to setup a tool set to enforce no rules, then iteratively add in rules that we approve? If a rule can't be implemented by an automated linter in a manner that doesn't decrease code readability then we shouldn't add it in?
