### ISSUE TITLE
Consider features for full UADC support

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#251]
Just because I've been going through constitutions for presets. Link to the rules document: http://www.alcheringa.in/pdrules.pdf 

Fundamental issues:

- Teams give feedback on dissenting adjudicators (who also give oral adjudications). I don't believe this is possible at the moment
- Team standings within pools are Wins > Aggregate Speaks (replies included) > Aggregate Margins (negative values for losses) > Random. If I'm not mistaken this requires a new ```team_standings_rule``'

Issues with workarounds:

- Feedback is compulsory, so should the shame page should be enabled it by default
- Adjs get marked on their test marks from A-F, and they are told of the grade. If there is a rego system for Australs done (which may include functionality for anonymous marking adj tests) this is worth thinking about.
- Dissenting adjs speaker scores do not count towards a speaker's score nor team totals nor a team's margin
- It dictates that there be 3 different styles of adj allocation: completely random (rounds 1-3), best panels to best performing teams (rounds 4-5) and best panels to live rooms (rounds 6-7). Being able to specify the adj allocation method (or tweak the parameters on a per round basis) is probably a broadly desirable feature anyway.
- The adj break seems very specified/rigorous — ie it must be the top 24 ranked judges, and judges cannot miss more than 5 rounds. This can be assessed using the UI atm, unclear whether its worth writing a standings function for it
- As much as it pains me, UADC wants a matter/manner/method split. This adds some complexity, but may also be useful for supporting other formats. I think this is a low priority feature though.

**Comment by czlee** [comment]
"_Teams give feedback on dissenting adjudicators (who also give oral adjudications). I don't believe this is possible at the moment_" is now possible (with the new feedback paths option), but teams are still nudged against it with the words "(chair rolled, this panellist gave oral)". Do you think we'd need to provide an option to remove that text, or provide another feedback paths option that says teams are expected to give feedback on all judges? It should be easy enough, except for the expected feedback calculations.

I think "_Team standings within pools are Wins > Aggregate Speaks (replies included) > Aggregate Margins (negative values for losses) > Random. If I'm not mistaken this requires a new `team_standings_rule'_" is possible now?

**Comment by philipbelesky** [comment]
Yea, I think the minimum viable path for support would now be:

- [ ] Some small preference along the lines of 'all adjs give adjudications' that changes the wording of that form and (if not too difficult) changes the expected feedback calculations.
- [ ] A preset that includes a `wins` > `speaks_sum` > `margin_sum` configuration for team standings
- [ ] Some way of solving the dissenting adjs not impacting scores issue. Any ideas here? Perhaps a setting along the lines of 'all adjudicator ballots not required for submission' that allows the form to save without all adjudicators having entered data (I'm not sure if this has any wider repercussions). Unclear if it should enforce a majority of adjs to have data or just be a setting that allows people to do what they want.

**Comment by czlee** [comment]
Wait, isn't dissenting adjudicators not counting towards speaker scores the status quo? Or are we also saying that dissenting adjudicators should not even submit ballots?

**Comment by philipbelesky** [comment]
Ah true, I was confused, I remember there being some issue about this previously, but thats probably faulty. Have removed that item; scores should be able to be entered as normal.

**Comment by philipbelesky** [comment]
Closed as of merge 248bfb8e319c1f5e8967703761d74448c3818105
