### ISSUE TITLE
Configure e-mail on internal server error

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#253]
At the moment, it tries to send an e-mail to test@test.com from an unspecified e-mail server. We should change this to send an e-mail somewhere useful.

**Comment by philipbelesky** [comment]
In 0.7.3 I've specified an email address for logs to be sent to, and added sendgrid to the deploy script/settings for heroku. Sending a test email from the django shell on heroku seems to work, but I'll wait until when I see an actual email from the system itself to check that this works.

**Comment by philipbelesky** [comment]
This should be working now, as of 403229ad91fb37e29c0a4fcf164cf58d9bb2cd31
