### ISSUE TITLE
UI redesign

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#257]
This is ongoing in ```feature/nav_rework```.

![Rework](https://dl.dropboxusercontent.com/u/1590949/tabbycatnav_rework.png)

Key goal is to remove simplify the navigation process by removing drop downs, clarifying round specific vs not round specific views, to better suggest the workflow of a round through the UI, and to have a proper subnav structure rather than relying on a bunch of buttons.

1. Top Most Area
    - Left top-most bar: pips that indicate current round state, and allow you to navigate to a previous rounds round-specific information
    - Right top-most bar: login and settings/import links — basically the usual place for unimportant links
2. Above white/content Area
    - Left most tabs: round-specific sections, arranged in order of progression 
    - Right most tabs: not-round-specific sections (in this image overview should actually be on the left)
3. First row of white.content area
    - Left most pips: the subpages within this particular section (links should actually be blue here). These are highlighted when visited.
    - Right most buttons: the primary action(s) for this section, such as Add Feedback, Release Draw, Advance to Next Round. For the round-specific sections, there should always be a single primary action, and the effect of it should be to advance to the next section. When this is not possible (say while confirming a draw, or when no adjs have been allocated) it should be grayed out. 
4. Above table area:
    - Left: information color key / misc
    - Right: quick search

Notes:
- Major issue now is figuring out the distinctions in 3 between sub page and action.  
- Checkins has been spun off into its own section
- I'm trying to reduce the number of subpages/actions on the draw page; possibly by adding another section related to displaying the draw (including printing functions) and/or splitting of the adj allocation into a separate section.
- Pages currently don't have titles. I'm not sure they need them, although some of the information previously in titles will need to be redistributed.
- Have added a few new overview pages for the top levels of a section — ie checkins, breaks, standings. These can provide overview data (say teams/venues/etc *not* checked in, top 5 speakers/teams/etc) but basically exist as landing pages into a particular section.

**Comment by philipbelesky** [comment]
- [ ] Create primary actions / ensure they exist for round specific sections
- [ ] Add state coloring to top most pips
- [ ] Add state coloring/indicators to the round-based sections
- [ ] Add 'overview' pips
- [ ] Add active state for pips
- [ ] Setup template inheritance within a section (to avoid repeating the actions/pip blocks)
- [ ] Add useful information to the overview pages
- [ ] Remove old title sections
- [ ] Convert old templates to new block structure
- [ ] Check the assistant nav UI isn't mangled by this
- [ ] Check the public nav UI isn't mangled by this

**Comment by czlee** [comment]
:+1: looks great.

Question: To what extent should some rounds in the top-left rounds chain be hidden, for space/brevity?

**Comment by philipbelesky** [comment]
I'd rather make them less visually prominent/smaller than having them be hidden. Even with an Australs number of rounds they should fit within most resolutions. But I should probably test that and maybe add in a limit or fallback

- [ ] Figure out how to display the pips for large numbers of rounds

**Comment by philipbelesky** [comment]
- [ ] Add a 'help' link pointing to the docs

**Comment by philipbelesky** [comment]
- [ ] Add new screenshots and update instructions in docs for running a round

**Comment by philipbelesky** [comment]
Ok, this is merged into `develop` now as any remaining bugs/rough edges aren't obvious to me. Things still to clean up:

- [ ] `break_index` should have some kind of content
- [ ] Make sure buttons that are actions are btn-primary while buttons that are links are btn-default
- [ ] Maybe either move to a tab based nav structured for sub pages, and/or make the navigation buttons consistent across sections
- [ ] Printing probably has bugs given the CSS refactor
- [ ] Admin area probably needs a mobile compatible nav menu
- [ ] Some pages still need emoji

**Comment by philipbelesky** [comment]
Further items, although probably not necessary for release:

- [ ] Fix the mini graphs of feedback on the feedback page
- [ ] Figure out a mobile menu solution for the admin area
- [ ] Nav highlights don't work for most public non-tab pages
