### ISSUE TITLE
Implement "Deploy to Heroku" button and add minimal set of forms to set up blank installation

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#262]
https://devcenter.heroku.com/articles/heroku-button
https://devcenter.heroku.com/articles/app-json-schema

This would deprecate the `deploy_heroku.py` script, but maybe we'd keep it around for developer convenience.

**Comment by czlee** [comment]
This works at a basic level, try:

[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/czlee/tabbycat/tree/develop)

At the moment I have it creating a superuser with username "admin", password "admin", and the `start_url` goes to the page where the user would change this password, in an effort to nudge them to change the password.

It occurs to me that it'll be a blank setup, i.e. without a tournament, so it's still not super user-friendly. In fact, attempting to redirect them automatically to the Django admin change-password page isn't super intuitive either. Any thoughts on what to do about this?

I was going to get it to auto-create a tournament, but it needs things like a tournament name and slug, and while we could set up these up as Heroku config variables, that seems like a clear abuse of them. I don't really have any ideas short of a proper GUI to create a first tournament, or like, a "getting started" wizard or something (that would also force them to create a user account and password rather than the current admin/admin), which tbh is a mini-project in its own right.

**Comment by philipbelesky** [comment]
Can the username/password also be set in the initial config variables that are exposed to the GUI deploy page? I don't mind putting a tournament name/slug there either. The post-deploy script can always be set to unset those variables on deploy. On that note can the waitress threads / caching variables be hidden?

If not, I think the minimally viable version would use placeholder usernames/passwords for an admin, and a placeholder name/slug for the tournament. Alerts could then be added to the frontend to change ones username and password if they are the default values.

Agree, that ideally, if there were no tournament it would prompt you to login and step you through the process of creating basic information such as the rounds and settings.

**Comment by czlee** [comment]
Any variable can be hidden, so long as the app can cope without its existence. So the caching variables can certainly be hidden if you don't want them there. I have some recollection that the app will crash if `WAITRESS_THREADS` isn't set though.

I guess we could put that in the post-deploy script, though my post-deploy script is currently a Django management command, because the only way to create a superuser programmatically without user interaction is using `User.objects.create_superuser()` (the management command insists on prompting for a password).

If you think it's better, I'm not totally averse to using config vars to set username, password, tournament name and slug in Heroku, and then deleting them using the postdeploy script. One obvious problem is that this password would presumably be sent to various places in plain text - though if Heroku does all its transactions over SSL (I think it does?) then maybe it's not such a bad thing. Maybe we should have placeholders for admin username/password, but prompt for tournament name and slug in config vars? Or should we just use placeholders for the lot?

At one point is `WAITRESS_THREADS` actually required? Could we set that in the postdeploy script? Though if we want it to be hidden from users, then there should probably be a default value set in the app somewhere appropriate (separately from the deploy script), if that's possible.

**Comment by czlee** [comment]
Actually, can a Heroku app set config vars from within the app, as opposed to from a client using `heroku config:set`? It occurs to me that this is required if our strategy of unsetting vars post-deploy, or even of setting vars post-deploy, is going to work.

**Comment by philipbelesky** [comment]
Ok cool. I mean this button is for novice users, so would prefer to hide all the variables that are non critical. If `WAITRESS_THREADS` needs to be set, we could just do so in the post-deploy as you suggest. It's not needed until the `Procfile` is called, which is definitely `post_deploy` and `post_compile`. Alternately we could just check for a null value and use default. 

I'm not super concerned about the passwords in plain text thing — heroku environmental variables are already commonly used to store secrets such as AWS credentials.

In python `os.environ['test'] = 'test'` works; however it only sets the variable within that process it seems. That said, if there isn't a way to unset them on the server, I think that would be fine.

**Comment by czlee** [comment]
Would that environment variable show up as a Heroku config var after being set in the app? If there's a way to revert to a default (always, not just for novices) I'd prefer that - it's a bit of a pain for advanced users to have to set it too.

Did we have a preference between putting username/password/tournament names as Heroku config vars, and using default values and alerting users they need to change them? I sort of suspect the latter is slightly more intuitive (since the Heroku page might be a little intimidating to novices), though it does require them to visit the Django admin site.

**Comment by philipbelesky** [comment]
Environment variables seem to be inherited (from parent processes?) but the inheritance doesn't seem to flow back upwards (when setting with python at least).  So I don't think we can rely on setting them permanently within a script.

I think the most intuitive/convenient method would be for usern/passw/tournament names are displayed on that initial deployment page (meaning they must be config variables). I don't think the heroku page is intimidating as long as we make it clear what the variables are and hide the ones that need technical knowledge to understand and set properly.

**Comment by czlee** [comment]
Do you mind setting it up so that it won't crash if WAITRESS_THREADS isn't specified? (This might already be the case, but I have some recollection of this not being the case at some point.) I'll do the rest.

**Comment by czlee** [comment]
It might possible to run `export` from anywhere to set environment variables globally but I quite strongly suspect Heroku will have restrictions on one's ability to do this. So I sort of think that the admin password should not be in an environment variable forever -- the public won't have direct access to them, but like, I don't in general like my passwords sitting around where someone (e.g., you) could find them, and password leaks generally aren't due to password sitting in places with open doors (which is why they're not meant to be stored in plain text, even on secure servers) :stuck_out_tongue:

**Comment by philipbelesky** [comment]
I doubt it's plain text though, or even that putting secrets in environmental configs is even frowned upon — the config page lists S3 credentials as an example. So at the point that is a suggest use case, is this really that bad?

**Comment by czlee** [comment]
I think it's different. For credentials you're storing the credentials the site is using to log in to another site. It sort of has to be stored in plain text, otherwise our site doesn't know what token to send to another site. And it's only our site—if it gets compromised, we can change the password to the third-party service.

In our case we're storing what a user uses to log in to our site. One of the reasons I think passwords shouldn't be stored in plain text is because some users use the same password on multiple sites (I know the practice is advised against, but it's a pragmatic necessity).

Config vars have to be plain text or something from which plain text can be directly derived, because I can recover their values with `heroku config`. The point of not storing user passwords as plain text is that you can _verify_ whether a password is correct but you can't figure out what you'd have to type into a password box to impersonate the account. That's why there's a `User.check_password()` method but not a `User.get_password()` method. It's also why encrypting passwords isn't good enough—_no-one_ is meant to be able to figure out what any user's password is, not even a site admin.

Because it's only one user (and the stakes with a Tabbycat instance aren't very high in the first place—we're not storing credit card details, for instance) I agree it's not as bad as storing all passwords in plain text, but I still think the practice is frowned upon. I think it would be okay enough, however, if it was unset as soon as the user account was created. So if we can just find a way to do that, I'll be satisfied.

**Comment by czlee** [comment]
Actually I sort of think it might be fundamentally impossible. I have some idea of how to push users to the change password page, so I'll have a crack at it some time. Or maybe this should be our nudge to actually implement a change-password page for all users. The problem is that we'd have to intercept every login, but I don't think that's a dealbreaker. And we'd just make the default password "tabbycat" or something.

**Comment by philipbelesky** [comment]
Okay. So the resolution is to make a default username and password, and then prompt users to change that username password ASAP?

I don't think its easy to check the password value, but it is easy to determine when a user has logged in and what their name is (see my additions at the bottom of the root ```urls.py```. At worst, we could use a default username as a proxy for the default password, and link those with default username to the change password section in admin?

**Comment by czlee** [comment]
We can use `User.check_password(pwd)` to check if the password is `pwd` (which in our case would be a constant). The problem with using the username as a proxy is that then they also have to change their username :stuck_out_tongue: 

I've been toying with the idea of just not creating an account and changing the front page so that if there are no user accounts and no tournaments, it prompts the user to create an account and a tournament. Or it'll probably be easier to separate the two—if there are no user accounts, prompt to create a superuser (and only allow this view if there are no user accounts—I don't think that should be a security flaw?), and if there are no tournaments, prompt the user to log in as a superuser if they aren't already, then prompt to create a tournament. It might not be more than a few hours' work if the minimum viable version does not take them through the whole data import.

(Would that be a security flaw? I can imagine maybe race conditions and stuff.)

**Comment by philipbelesky** [comment]
Ah, I assumed that there wouldn't be a function to call/check it. We should do that instead then. 

Agree that ideally there would be a setup screen for when things are at a total blank slate. The person creating the instance has overall control, so not really worried about someone else commandeering it. I don't think having that screen is blocking to enabling the heroku button though — I think a basic password prompt is enough for now?

**Comment by czlee** [comment]
If by "basic password prompt" you mean a "Hi! Please create a first account." screen, then that's what I meant :smile:

**Comment by czlee** [comment]
Though remember once the site is live, anyone who knows the URL can also create the first account, hence race condition. This doesn't matter so much so long as the system only allows a superuser to be created once, and rejects all future attempts to do so. Remember clients can spoof POSTs from any page, so the view needs to catch future POSTs that look like those sent by the original form too—otherwise anyone can create a superuser account at any time.

So long as all second attempts to create a superuser are rejected, even if someone "beats" the original admin to creating the first account, it'll be obvious because the admin won't be able to create one, so they'll just destroy the site and create a new one, which is fine. I think it'll work if the check is done at the POST stage—it's not sufficient to check before displaying the form, because (a) spoof POSTs and (b) even without spoofs, two people could both load the form when it's valid to do so (and then both submit).

**Comment by czlee** [comment]
The race condition I'm worried about is if two people submit at _exactly_ the same time, then the view checks both POSTs before having handled the others. This can only happen if each view is done on a different thread, but I do think that's true. It can be worked around with a semaphore though.

**Comment by philipbelesky** [comment]
Yea, I mean I think that particular race condition is probably pretty unlikely :p

**Comment by czlee** [comment]
I mean, there's almost no such thing as a race condition that is likely :stuck_out_tongue_winking_eye:

**Comment by philipbelesky** [comment]
On the `WAITRESS_THREADS` fronts, having dug back into the documentation it seems that this sets the number of threads per web process. But as adding more dynos adds more web processes, I don't think we ever really want to change this. So we should probably just remove it (the default is 4 anyway). 

Also we should really benchmark gunicorn vs waitress properly at some point. Oh and also benchmark waitress/gunicorn vs `runserver` locally.

**Comment by czlee** [comment]
Okay, so here's a small road block. In order for this to work, one of the following two things needs to happen:
1. The interface needs to be able to function with a tournament that has no rounds.
2. We have to create rounds as part of the user-friendly "create tournament" process.

Since someone setting up a site using the Deploy to Heroku button would presumably be using the "visual importer" function, I'm not sure which is better.

The two options aren't mutually exclusive and we should probably do (1) for correctness. (Currently, if there is no current round, it displays a terse and unhelpful messages redirecting the user to the Django admin site.)

(2) would be faster for a minimum viable implementation. It would restrict users who use this method to preliminary rounds with default settings, but given that this launch method is only for basic users anyway, that's probably okay. Thoughts?

**Comment by czlee** [comment]
Okay I implemented (2), realized that the visual import doesn't currently have rounds import. We'll move (1) to a separate issue or discussion or something.

**Comment by philipbelesky** [comment]
Quick update: the issue with the deploy script / heroku button should be fixed now.

**Comment by czlee** [comment]
There are a bunch of warnings that look like this:

>Found another file with the destination path 'admin/js/inlines.min.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.

Are we concerned?

**Comment by czlee** [comment]
Also, I did this: d1e73cb...326998d, would you mind checking if those are the right things?

**Comment by czlee** [comment]
Okay, so now we're most of the way there. If you deploy, it guides you up to the point where you have an existent but blank tournament. We then just need to decide if/where we want to push them next, presumably the visual data import? A message with a link should probably do the trick.

**Comment by philipbelesky** [comment]
With regards to:

> Found another file with the destination path 'admin/js/inlines.min.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.

Every drop-in replacement for the admin section seems to have the problem where its static files clash or don't clash with other ones. These don't seem to actually affect admin functionality, so are mostly just annoying atm.

d1e73cb...326998d are good, sorry should have caught most of those.

Kicking over to the visual importer sounds good. Maybe the message should also mention the docs?

**Comment by czlee** [comment]
Done. Finally. Take a look and see if you think it constitutes a minimum viable?

**Comment by philipbelesky** [comment]
Looks great! The messages/page flow actually work really well as a guided setup process.
