### ISSUE TITLE
Use csv.DictReader rather than csv.reader for data import?

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#263]
I just realised there's a `csv.DictReader` object that reads rows as dicts rather than lists:
https://docs.python.org/3/library/csv.html#csv.DictReader

Crucially:
> If the _fieldnames_ parameter is omitted, the values in the first row of the _csvfile_ will be used as the _fieldnames_.

And:
> If the row read has fewer fields than the _fieldnames_ sequence, the remaining keys take the value of the optional _restval_ parameter.

I feel like this would be a better way to write the data importer (or any data importers). Our demo data assumes a header row anyway. Currently, `BaseTournamentDataImporter` requires a line parser function that takes the tuple given by `csv.reader`, and is expected to return a dict of keyword arguments that can be passed to the constructor of a model. The proposal would be instead:
* The line parser function would take a dict, and return a dict of keyword arguments that can be passed to the constructor of a model.
* The line parser function could be possibly optional, and if omitted, would be the identity function, or a "smart" identity function that converts strings to integers or floats when appropriate.
* _restval_ would be `None`, and this would replace constructions like `'pronoun': line[6] if len(line) > 6 else None`.

Perhaps there could (also) be a line parser function constructor that takes keyword arguments mapping keys to functions, and for each key in the dict, the base class would apply that function to the value corresponding to that key. For example,
``` python
def _adjudicator_line_parser(line):
    return {
        'name'        : line[0],
        'institution' : pm.Institution.objects.lookup(line[1]),
        'tournament'  : self.tournament,
        'test_score'  : float(line[2]),
        'gender'      : self._lookup(self.GENDERS, line[5], "gender") if len(line) > 5 and line[5] else None,
        'pronoun'     : line[6] if len(line) > 6 else None,
        'independent' : bool(int(line[7])) if len(line) > 7 and line[7] else False,
        'novice'      : int(line[8]) if len(line) > 8 and line[8] else False,
        'phone'       : line[9] if len(line) > 9 else None,
        'email'       : line[10] if len(line) > 10 else None,
        'notes'       : line[11] if len(line) > 11 else None,
    }
```
would become
``` python
_adjudicator_line_parser = self.construct_line_parser(
    institution=pm.Institution.objects.lookup,
    test_score=float,
    gender=lambda x: self._lookup(self.GENDERS, x, "gender"),
    independent=bool,
    novice=int,
    tournament=lambda: self.tournament
)
```
(It could even be the case that things like `test_score=float` could be omitted, and inferred intelligently from the model's field type.)

Pros:
* It wouldn't matter what order the CSV's columns are in.
* Subclasses `BaseTournamentDataImporter` would (probably) be much simpler, and would not rely on "magic constants" (mainly, the numeric indices littered through anorak.py). For example, rather than generate a dict from scratch, it could just modify those elements that need to be changed.

Cons/risks:
* We would then prefer that the header row be the field names *exactly* as in the Django models. This is basically the status quo, but the point is that we would not be able to change header rows to human-friendly names (though they would still be human-readable, of course).
* This would probably increase the learning curve to writing a tournament data import subclass, because there are more (useful) structures authors can take advantage of to save the amount of code they write (which requires them to understand what they do). Good documentation can mitigate this, but the learning curve is probably still there.
* Not super clear yet how this would work with line parser functions that return multiple dicts (see, _e.g._, `_institution_conflict_parser` at [anorak.py:301-314](https://github.com/czlee/tabbycat/blob/develop/importer/anorak.py#L301-L314)), but at worst it's surely just the status quo with numeric indices replaced by string keys.

@philipbelesky: One question among many: If we did this, would it affect your planned work on the visual importer?

**Comment by philipbelesky** [comment]
Ah, I had totally forgotten about ol DictReader. Not having to worry about CSV order is great, as it means you can more easily input a minimal data set, although not allowing alternate header rows could be annoying.

I'm not sure the learning curve increases too much, the kind of structures DictReader encourages are pretty well documented. 

In response to your direct question: I don't have any real planned work for the visual importer apart from more rigorous testing of it. I would like to convert parts of it that take CSV entries to use the standard importer, but thats not immanent. So no real effect on that work.

**Comment by czlee** [comment]
Oh, the learning curve wouldn't be so much from DictReader directly, it'd be from the infrastructure that I add to take advantage of it so that there is less code to write a new importer quickly. But I guess worst case even with DictReader is that I don't write that infrastructure, or I write it once and people use the modified old way, which isn't a harm.
