### ISSUE TITLE
rcssmin requires a C compiler, which breaks Windows local installations

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#265]
Fun times, with current local installations in Windows (from the develop branch):

```
Installing collected packages: rcssmin, rjsmin, django-compressor, sqlparse, django-debug-toolbar, django-ipware, libsas
s, django-libsass, django-suit, django-dynamic-preferences
  Running setup.py install for rcssmin ... error
    Complete output from command c:\users\czlee\git\tabbycat\venv\scripts\python.exe -u -c "import setuptools, tokenize;
__file__='C:\\Users\\czlee\\AppData\\Local\\Temp\\pip-build-idha5rwu\\rcssmin\\setup.py';exec(compile(getattr(tokenize,
'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\czlee\AppData\Local\
Temp\pip-ev6w6zrs-record\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\czl
ee\git\tabbycat\venv\include\site\python3.4\rcssmin:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.4
    copying .\rcssmin.py -> build\lib.win-amd64-3.4
    running build_ext
    building '_rcssmin' extension
    error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).

    ----------------------------------------
Command "c:\users\czlee\git\tabbycat\venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\czl
ee\\AppData\\Local\\Temp\\pip-build-idha5rwu\\rcssmin\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).
read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\czlee\AppData\Local\Temp\pip-ev6w6zrs-record
\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\czlee\git\tabbycat\venv\inc
lude\site\python3.4\rcssmin" failed with error code 1 in C:\Users\czlee\AppData\Local\Temp\pip-build-idha5rwu\rcssmin
```

In a nutshell: django-compressor depends on rcssmin, which appears to need a C++ compiler in order to install. I think rcssmin has a Python version but because it's in django-compressor (two levels deep) persuading it through pip to install without the C extension might be a pain.

This is new in django-compressor 2.0. In django-compressor 1.5, rcssmin and rjsmin were included in django-compressor, rather than external dependencies. See:
* https://github.com/django-compressor/django-compressor/commit/6f4639e6b1cf7dcede4997eeabd8562da9366a9b
* https://github.com/django-compressor/django-compressor/issues/664

Options:

1. Try harder to get it to work without the C extension.
2. Live without django-compressor on Windows local installs (ideally it would detect if there's Visual C++ installed, and make a decision based on that).
3. Require Windows users to install Visual C++.

Thoughts?

**Comment by czlee** [comment]
Link to #248

**Comment by philipbelesky** [comment]
We could probably live without. At the moment it's only earning its keep concatenating a few third party JS libraries, which I could just do manually. Obviously it also compiles the SCSS, but we have libsass and django-libsass so we should be able to sub that in.

**Comment by czlee** [comment]
Okay, so we just have to figure out how to get pip not to install it if it can't find a C compiler, rather than crash :)

**Comment by philipbelesky** [comment]
I'd prefer to just remove it entirely tbh, will go ahead with that. It's overkill for our needs (even libsass/sass is only a dependency for development really).

**Comment by czlee** [comment]
lol, fair enough

**Comment by philipbelesky** [comment]
Ok, this is merged in now, are you able to test? You'll need to nuke your local settings and redo the pip install btw.

**Comment by philipbelesky** [comment]
Just tried this on a VM:

1. Had to add python to my path manually; I did set 'will install' as instructed, but there's a weird GUI bug on ultra high res screens that means maybe it didn't come into effect.
2. Everything otherwise worked fine
3. Monochrome emoji look good

**Comment by philipbelesky** [comment]
Err forgot adding to ready in gitter closes things, feel free to reopen if you think point 1 above is an issue

**Comment by czlee** [comment]
I had issues where the PATH doesn't come into effect unless you open a new command prompt, or maybe restart your computer or something (though I didn't _always_ have to. Could be that? Unclear.

**Comment by philipbelesky** [comment]
Ok, have added a note to that effect.

**Comment by philipbelesky** [comment]
Bumped *back* to compressor 2.0 in response to what I think is an error with heroku's static generation. Will see if that definitely solves the heroku issue in the medium term, and if so, figure out how to get around the problems with the windows install.

**Comment by czlee** [comment]
When installing rcssmin and rjsmin, you can pass the argument `--without-c-extensions` to `python setup.py` to skip compiling the C extensions. This way, rcssmin and rjsmin will install successfully on Windows. This argument can be passed via `--install-options="--without-c-extensions"` in `pip install` from pip 7.0—see the [relevant part of the pip documentation](https://pip.readthedocs.org/en/stable/reference/pip_install/#per-requirement-overrides).

I tried putting this in a new _requirements_windows.txt_ file, with
```
rcssmin==1.0.6 --install-options="--without-c-extensions"
rjsmin==1.0.12 --install-options="--without-c-extensions"
-r requirements_common.txt
```

But for some reason it then tries to pass `--without-c-extensions` to every other package as well. Also, for some reason, `libsass` fails to install, requiring a C compiler as well—presumably because wheels get disabled with `--install-options` is used, so Pip proceeds to look to compile libsass from source.

The best I can think of for now is just to instruct Windows users to install rcssmin and rjsmin first and separately, with
```
pip install rcssmin==1.0.6 rjsmin==1.0.12 --install-options="--without-c-extensions"
```

The obvious downside here is that the documentation will have to be kept up-to-date with the rcssmin and rjsmin versions in [django-compressor](https://github.com/django-compressor/django-compressor), which is where these requirements come from.

**Comment by czlee** [comment]
In case it ever becomes relevant in the future, Windows-only requirements can be specified with environment markers:
https://pip.readthedocs.org/en/stable/reference/pip_install/#requirement-specifiers

**Comment by swiharta** [comment]
I am not using your program but also using Windows and trying to install django-compressor 2.0 which requires rcssmin 1.0.6. I finally got it to work using "wheels":

```
pip install wheel
pip wheel rcssmin
```

Maybe that will help you, not sure.

**Comment by czlee** [comment]
We found one way to get around this, but thanks for the pointer! There's a `--without-c-extensions` option for rcssmin and rjsmin, though passing it to setup.py via pip requires some finesse:

```
pip install rcssmin --install-option="--without-c-extensions"
```

The `pip wheel` command is meant to generate wheels though, so this doesn't work—it crashes with the same error. What I'd really like is for rcssmin to be packaged as a wheel, but I don't know if the developer has any plans to that effect.

**Comment by swiharta** [comment]
I don't know much of anything about wheels, somehow I got it to install after trying everything, I downloaded rcssmin manually from http://storage.perlig.de/rcssmin/rcssmin-1.0.6.zip, cd'ed into the unzipped directory, did  `pip wheel rccsmin` and then `pip install django-compressor`. I guess it was luck. I could not get the command `pip install rcssmin --install-option="--without-c-extensions"` to work.

**Comment by rr-info** [comment]
i managed to run the "without-c-extensions" this way:
download rjsmin, rccsmin,
extract,
open a CMD console, 
cd to the package's root dir (i.e where the "setup.py" file is located),
run the "pip..." command from there
it worked for both packages

(n.b. i'm from another project with same problem)

**Comment by iam-mhaseeb** [comment]
`pip install rcssmin --install-option="--without-c-extensions"` worked for me as well.
