### ISSUE TITLE
Docs edits as required for release

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#269]
I have no idea what to properly call this. But the intent is to detail the different kinds of key information, and where to go to add/edit them. A lot of this information may not be imported with the bulk importer, or may have been skipped over. This is particularly true when doing manual data entry or using the visual importer. I mean information such as:

- [x] The types of conflicts available and how to add/edit them
- [x] Metadata such as novice status, gender
- [x] How test scores and feedback weightings work
- [x] How a team's name is determined
- [x] Venue priorities
- [x] Edge cases in data entry such as composite teams

I think at least some of this could be punted to better help text in the backend area. But the backend are is so extensive (and we tend to warn people away from it) that I think there should be some better explanation of the common pieces of data that need to be edited there.

**Comment by philipbelesky** [comment]
Have added the above under Starting a Tournament. Probably needs some edits to tighten up, but I think its useful information to have. Am turning this in to a grab bag issue for changed to the docs that are needed before the Bengal release. My candidates:

- [ ] Detail printing features
- [ ] Detail adj allocation features
- [ ] Change descriptions of the UI when the redesign is merged in (such as the location of the Data Admin section).

**Comment by czlee** [comment]
[Data entry page](https://tabbycat.readthedocs.org/en/latest/features/data-entry.html) has screenshots for admin interface. Shouldn't these be for the monkey interface, since we explicitly advise against using the admin interface for this purpose?

**Comment by philipbelesky** [comment]
Yup, images have now been updated.
