### ISSUE TITLE
Investigate performance of persistent connections

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#271]
> By default, Django will only create a new persistent database connection for every request cycle of your application. This occurs whenever Django attempts to talk to the database through a SQL query.
Constantly opening new connections is an expensive operation, and can be mitigated with the use Django’s persistent connections.

It seems that we should be enabling this as much as possible...

> Heroku provides managed Postgres databases. Different tiered databases have different connection limits. The Starter Tier “Dev” and “Basic” databases are limited to 20 connections.

...but aware that there is a hard gating factor on it

> When scaling out, it is important to keep in mind how many active connections your application needs. If each dyno allows 5 database connections, you can only scale out to four dynos before you need to provision a more robust database.

When using gunicorn each worker process, by default, has a single persistent connection. I assume there is a 1:1 dyno:process relationship there, but I'm not sure. The per-process max persistent connections can be increased using

    heroku config:set WEB_CONCURRENCY=3

However, note:

> Sometimes a database won’t be accessed by the majority of your views, for example because it’s the database of an external system, or thanks to caching. In such cases, you should set CONN_MAX_AGE to a low value or even 0, because it doesn’t make sense to maintain a connection that’s unlikely to be reused. This will help keep the number of simultaneous connections to this database small.

In our case, this is complicated by the use of waitress and its threading. I'm unclear whether WEB_CONCURRENCY affects each of those (or whether it affects the waitress process as a whole). But I think we should try and test setting this up properly. Additionally we should maybe look into running [connection pools](https://github.com/kennethreitz/django-postgrespool) or [limiting connections](https://devcenter.heroku.com/articles/python-concurrency-and-database-connections#limit-connections-with-pgbouncer)

Quotes via 
[devcenter.heroku.com/articles/python-concurrency-and-database-connections](
https://devcenter.heroku.com/articles/python-concurrency-and-database-connections)

**Comment by czlee** [comment]
"Every request cycle". Does this mean once for every HTTP request? If so it's not obvious to me that we should be enabling persistent connections as much as possible, or even at all, except for things like adj allocation.

**Comment by philipbelesky** [comment]
I  assume it does. But we can probably assume each user is spending less than a minute on each page, and triggering a request whenever they load a new page. As I understand it having a persistent connection would mean there would be a consistent speed up on page loads in the case?

**Comment by czlee** [comment]
Okay I reread it all and I think I got it wrong the first time, somehow had the impression that we would require one connection per user and a persistent connection would only apply to one user. Though, I'm not sure how we used to run out of connections when we released the tab, if it's only one database connection per worker thread.

**Comment by czlee** [comment]
But it's weird that the default for this wouldn't work for us, I mean, like, Tabbycat instances aren't big sites or anything.

**Comment by philipbelesky** [comment]
We aren't although our data seems highly related. Regardless I seem to remember that SQL lookups are a gating factor for a lot of our more complex pages, and part of this is that the heroku basic databases are relatively slow (one of the common recommendations is to move your database of heroku to an external provider).

**Comment by czlee** [comment]
Yeah, but it's not opening a new connection for each SQL query in a single page request, right? If there are 100 queries from one page, it'll just open a single connection for all of them?

**Comment by philipbelesky** [comment]
Yea, having done a bit more research it looks like a bad idea - the scaling is too hard to do right, particularly come tab release. And the performance gains probably not that great.
