### ISSUE TITLE
Consider restructuring the directory

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#273]
We have quite a few top level folders and files. It seems common to split the django specific folders into a single subfolder (probably `tabbycat` in this case) and reserve the top level for files such as the top level markdown files, .gitignore/python-version, travis, the docs folder, etc. Examples:

- [https://github.com/diefenbach/django-lfs](https://github.com/diefenbach/django-lfs)
- [https://github.com/montylounge/django-mingus](https://github.com/montylounge/django-mingus)

Would need to modify some of the installation instructions, and possibly some of the heroku related deploy scripts.

**Comment by philipbelesky** [comment]
Also to consider, the [default project setup](https://docs.djangoproject.com/en/1.6/intro/tutorial01/#creating-a-project) creates a folder (within the base directory for the project) with the same name as the project for top-level `settings.py`, `urls.py`, `wsgi.py` etc (manage.py stays at the root project level)

**Comment by czlee** [comment]
I don't really have strong views on this. It makes sense to me, so long as the app structure is maintained. I'd probably try to see if we could keep deploy_heroku.py in the root directory (as in if it works with import statements okay).

**Comment by philipbelesky** [comment]
This is up in feature/#273 branch, although not working that well. I do like the new structure, but it seems like most of the imports need to change from `import venues` into `import tabbycat.venues` which is somewhat annoying. Waitress runs, although the inbuilt django server does not. There seems to be some path issues or similar going on. Not in the mood for debugging it; may come back to it later.

**Comment by philipbelesky** [comment]
Ok, got bored and had a quick go at this in light of #292 (up on the feature/#273 branch). The thinking is that:

- Code relating to Tabbycat as a somewhat-self contained django project lives in `tabbycat` directory
- Docs and all third-party dependency folders (`static`, `bower_components`, `node_modules`) live as  sibling folders in the top level directory 
- This also allows all the misc dependency/travis/runtime/gulp/bin stuff to live in the top level directory as well
- Currently I've also put data up to the top level; unsure about that. The thinking is the directories in `tabbycat` should all be importable modules
- Ends up with 26 items in the top directory rather than the 58 we currently have

The major advantage is that the new `tabbycat` directory becomes much simpler and easier to navigate (both in the file system and in the sense I can just open that folder in a text editor as its where 99% of the code I want to edit is). It does mean that you'll need to go one level deeper than normal in order to run `manage.py` though (unless running from `bin`). Thoughts? 

Mental notes, if going ahead: 

- Test this works with the heroku deployment options
- Update docs with new install structure
- Check things like the importer and travis test commands that assume the old directory structure
