### ISSUE TITLE
Buttons that change data should always be POSTs

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#287]
If a button changes data, then it should be a button that submits a POST request, and it should go to a view that only accepts POST requests.

`PostOnlyRedirectView` can facilitate this.

**Comment by czlee** [comment]
In things I stumbled across today: [Django docs for `get_or_create()`](https://docs.djangoproject.com/en/1.9/ref/models/querysets/#django.db.models.query.QuerySet.get_or_create) say:
> Finally, a word on using get_or_create() in Django views. Please make sure to use it only in POST requests unless you have a good reason not to. GET requests shouldn’t have any effect on data. Instead, use POST whenever a request to a page has a side effect on your data. For more, see [Safe methods](https://tools.ietf.org/html/rfc7231.html#section-4.2.1) in the HTTP spec.

The HTTP spec essentially says that GET, HEAD, OPTIONS and TRACE requests have to be "safe", _i.e._, must not affect data, so that clients know when to present appropriate warnings to the user (and when they can use automated tools without harm).

On another note, do we have any data-changing POST requests left?

**Comment by philipbelesky** [comment]
Do you mean data-changing GET requests?

**Comment by czlee** [comment]
Whoops, sorry! Yes, I meant do we have any data-changing GET requests left.

**Comment by philipbelesky** [comment]
Hmm not that I can think of or ID easily. Will keep an eye out.

**Comment by czlee** [comment]
Availability still has several, I came across them last night (the check in all buttons)

**Comment by philipbelesky** [comment]
Ah, I see. So they're:

- [ ] `update_availability_breaking_adjs` / `AvailabilityActivateBreakingAdjs`
- [ ] `update_availability_all` / `AvailabilityActivateAll`
- [ ] `update_availability_previous` / `AvailabilityActivateFromPrevious`

**Comment by czlee** [comment]
Also:

- [ ] `toggle_postponed` in results/views.py

**Comment by czlee** [comment]
I think this now ties to #279, in the sense that it's most easily done when the availability app itself is overhauled.

**Comment by czlee** [comment]
- [ ] `adjallocation.view.CreateAutoAllocation`

**Comment by czlee** [comment]
I think that might be it?

**Comment by philipbelesky** [comment]
👏. Can always reopen if not?
