### ISSUE TITLE
Move draw logic into draw app

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#289]
Some of the "outer" draw logic is currently on the Round model. This should change: the Round model shouldn't do anything intelligent with the draw, and the draw generator should just populate things itself.

The current draw generator is designed to be abstracted away from models, so it can be tested without reference to the database. It might be that a wrapper class for the current draw generator would work better.

**Comment by czlee** [comment]
@philipbelesky: Do you have an easy way to test if a draw with divisions still works? Part of this involved refactoring the code for venue assignment, which might break how it works for divisions.

I rewrote the algorithm to try to cover more cases, allowing for future support for _e.g._ accessible venues (or venues for the adj core). It assigns pairings venues in groups if the pairing has an associated venue group, and otherwise does it at random, specifically trying to avoid leaving only low-priority rooms pairings without groups.

**Comment by philipbelesky** [comment]
No I don't at the moment — I intended to write a test case for it but I think it will have to wait until next year at the moment. That said no new division based draws need to be generated for this year (I think). Ill create a seperate issue for testing divisions against this change (and for writing a test).

**Comment by czlee** [comment]
Oh, not even just informally? Like just to sanity check it on an existing database or something? We don't exactly have test cases for venue assignment in general (because before divisions it wasn't complicated) so, although we should, it's not my most precise concern.

**Comment by philipbelesky** [comment]
Not super-easily; on my test copy regenerating a round robin draw crashes due to an unrelated issue (can't find a Bye team in standings) so I would need to dig into that first.

**Comment by czlee** [comment]
Okay, we'll keep this open till you've sanity-checked it—it's pretty complex code so odds are pretty high there's at least one careless bug somewhere. Unless that's going to wait till next year, in which case maybe we should have a division-based dataset or something.

The other way to sanity-check this code would be to build in more elaborate venue preferences, but I sort of suspect by the time we get there, the relevant logic should be moved to the `venues` app. Venue assignment can get surprisingly complex if done properly.
