### ISSUE TITLE
Move feedback progress logic to a separate module

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#290]

**Comment by philipbelesky** [comment]
What did you mean by new module here? Like a new app; or just abstracting it out of the view logic (as in  080cd3b7f86e55382ad4b9034d263da1326f27b5)

**Comment by czlee** [comment]
The latter, sorry, I just meant "module" in the sense if a Python file.

**Comment by philipbelesky** [comment]
Ok, all done then!
