### ISSUE TITLE
Add checkpreferences command to deploys without breaking the heroku button

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#303]
Basically `checkpreferences` needs to be run after an initial migration has been made, else it will cause an error and break the heroku deployment button. `post_compile` is too soon but I am sure there is another method.

**Comment by philipbelesky** [comment]
Other option would be to add some form of logic in `post_compile` that checks if an initial migration has been made. Or a method for running `checkpreferences` that fails silently if migrations have not been made.

**Comment by czlee** [comment]
The lazy thing to do would just be to add the step in each of app.json, deploy_heroku.py, and the instructions for local installation?

**Comment by philipbelesky** [comment]
But if I understand each of those things will only run on the initial
install, whereas the reason for adding 'checkpreferences' is to prevent
errors on existing instances that are updated.

**Comment by czlee** [comment]
Oh, true.

**Comment by philipbelesky** [comment]
Shifted migration from app.json to the post_compile script in f2e23bb984337158f087c55935f022fb690c0c31 and e55024d1ffadbc32e8b102b29964c553f3ac3f2d which seems to work well in combination with checking preferences in deploy_heroku and the auto click button.
