### ISSUE TITLE
Convert break qualification code to class-based generators

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#307]
It would probably make the code a bit tidier/easier to extend, but it's not obvious how to structure this.

**Comment by philipbelesky** [comment]
I assume this only concerns `breakqual/breaking.py`? Going to remove this from the Devon Rex milestone as neither of us has started on it; feel free to add it back in if you're keen to get to it in the near future.

**Comment by czlee** [comment]
agree with removing from Devon Rex, it's pretty low priority now

**Comment by czlee** [comment]
Adding to Egyptian Mau primarily as a means of getting to #213, #349 and #348 properly
