### ISSUE TITLE
Feedback submission confirmations can have wrong source/target

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#308]
I've temporarily removed the message part of the response in 52ea99979dd03e88c5ff296fcd019a29bf58ef4d as the actual feedback seems to go through correctly. Seems to only occur under load.

**Comment by philipbelesky** [comment]
Have re-eneabled the part of the message that notes who the received feedback on. Closing for now as this seems too hard to replicate and is hopefully fixed with the new performance enhancements.

**Comment by czlee** [comment]
"hopefully fixed with the new performance enhancements" lol

but yeah we can't do anything about it until we see it again anyway.
