### ISSUE TITLE
Add trainee allocations to the HungarianAllocator

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#312]
Allocating these manually can be a pain at large tournaments. Some trainees may require manual adjustments in order to be 'tested' but I think a super-basic allocation method where the top-importance debates get the top-ranked trainees is likely to be effective in most cases. Unclear if this is worthy of being a setting or not.

**Comment by philipbelesky** [comment]
I'd like to try getting this going for  Australs, any thoughts on how the allocation policy should work?

In some circumstances its desirable for adj core members to see trainees, in other circumstances they'd prefer not to — I'm not sure whether its worthwhile accounting for this case though. 

Also in determining where to place trainees, I think a straight forward allocation of top trainees to top rooms would be better served by allocating top trainees to top solo chairs (to avoid panels being huge). Looking at past Australs that seems to be the dominant pattern.

Both of the above scenarios will not be correct 100% of the time obviously, but I think even if 50% of the trainees need to be shifted around thats still a reasonably significant time saving over having to place all of them manually.

**Comment by czlee** [comment]
It's probably debatable whether it should be part of the panels allocator, or whether we should just create an extra step of allocating trainees (separate from `HungarianAllocator`, `SAAllocator` _etc._) that runs after the panels allocator does. My instinct is to run with the latter, unless there is a decision to be made about _whether_ a judge should be a panellist or a trainee (which was the case with Adjumo, where trainees could be temporarily promoted to achieve representation).

If we're doing this for Australs 2016, we should consult with the adj core about what they want to do. I try not to have opinions about allocation policy :stuck_out_tongue_winking_eye:

**Comment by philipbelesky** [comment]
Moving this off the current milestone as I think its better approached in conjunction with #344

**Comment by czlee** [comment]
I implemented a Hungarian-based allocator that operates similarly to the solos allocator, but adjusting the debate importances down by 2 for each debate. In particular, conflicts are applied to trainees in the same way as solos. I tidied up the rest of the code in the process, including to take advantage of how the munkres library now supports non-square matrices.
