### ISSUE TITLE
Allocation Page should not allow the same adj to be on the same debate twice

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#321]
When adjudicators are able to be allocated multiple times, allocating the same adjudicator to a debate multiple times then results pages will crash given:

    File "/app/results/result.py", line 35, in __init__ 2016-05-20T08:24:37.962834+00:00 app[web.1]:    
    self.da = self.debate.debateadjudicator_set.get(adjudicator=adjudicator)
    adjallocation.models.MultipleObjectsReturned: get() returned more than one DebateAdjudicator -- it returned 2!

This is pretty rare but should be blocked by the front-end for sure. Idk whether its work explicitly catching the error and reporting it in the init method for `Scoresheet` as well.

**Comment by czlee** [comment]
This is meant to be blocked by the database though! Isn't there a `unique` constraint on that model?

**Comment by czlee** [comment]
Oh, I guess not.
https://github.com/czlee/tabbycat/blob/7dc0fc2/adjallocation/models.py#L6-L25

We should probably add one.

**Comment by philipbelesky** [comment]
Yea, sounds good — I can't think of any reason why you'd want non-unique adjs on a debate.
