### ISSUE TITLE
Auto-create an Open BreakCategory for a new tournament object

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#325]
Just a small thought to improve the usability of Creating/Editing breaks: it should be relatively simple to automatically create an 'Open' `BreakCategory` whenever a new tournament is created; circumventing the need for a user to dive into the database area to work out an initial break. 

Any downsides here? I would think almost all tournaments have an open category. Alternately: any other circumstances where a related object should be automatically created or destroyed? I think the system automatically handles most of these cases (ie removing a `DebateTeam` when a `Debate` is deleted when the draw is remade) although it could be advantageous to have that enforced by the data layer rather than in the function calls (say for regenerating a round).

**Comment by philipbelesky** [comment]
Err I actually totally forgot about the fact that break sizes cannot be assumed. Ok, what should probably happen instead is to just add a "Number of teams in the open break" field to the Create New Tournament Wizard and create it at that step.

**Comment by philipbelesky** [comment]
Mental note: the auto-created `finals` rounds should then also have their `break_category` set at the ame time.

**Comment by czlee** [comment]
lol, I see you've already done it. Why are there two fields, `break_size` and `num_final_rounds`? Can't the latter be inferred from the former?

Also, I'm changing names of variables etc. to `break_rounds` to keep it consistent with other code, if that's okay.

**Comment by philipbelesky** [comment]
Sure. I figured adding a seperate `break size` option was useful for cases where there are partial elimination rounds.

**Comment by czlee** [comment]
You can still infer the number of rounds from the break size, even if the first one is partial :stuck_out_tongue_winking_eye:

(For example, if there are 19 breaking teams, then you must be breaking to partial double-octos, so there will be five break rounds. You take log base 2, then round up.)

**Comment by philipbelesky** [comment]
Ah true. Done in 135b3b1805d61599859e52132aa665a5486b5ca7
