### ISSUE TITLE
Should EliminationDrawGenerator or Availability determine advancing teams?

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#326]
I'm working on `EliminationDrawGenerator` for WADL's purposes, and noticed the code that provided results from `EliminationDrawManager` seems to have gone (or maybe it wasn't there ever; I'm not good at searching histories). 

Anyway the way `EliminationDrawGenerator` works at the moment is it expects a list of the pre-advanced teams as `teams` and then extends them using the winners from the provided `results`. However I think this is somewhat at odds with how the availabilities workflow proceeds: in all other circumstances only teams that have been checked in will be considered as available for the draw. 

Would it make sense to then to determine those who get through using the `activate_all_advancing_teams()` method? Currently it filters just for the winners from the previous break round; it could relatively easily be modified to also retrieve the top x breaking teams, assuming x can be reliably calculated as the `break_category` size minus the number of teams debating in the previous round. If I'm not mistaken then the `DrawGenerator` doesn't need to know about results at all. Alternately the generator could do all this, but it does seem less intuitive to the user perhaps?

**Comment by philipbelesky** [comment]
Mental note for the morning: does/should `FirstEliminationDrawGenerator` abide by this principle? IE if you check in breaking teams does it remove the safe/advancing teams from the generation? Should this cull instead be done at the availability stage (perhaps with alerts/warnings to this effect?)

**Comment by czlee** [comment]
I've certainly never fully implemented support for subsequent elimination rounds (when I wrote the draw generator code I threw it in the "too hard" basket), so if you haven't implemented it, then it's never been there.

From a technical standpoint, the purpose of availability is to determine who should be in the draw. Thinking about it now, I'm not sure that this makes any sense for elimination rounds. Break round draws don't depend on who is present, unless the just-missing teams are held as "reserves" for absent breaking teams (a policy that is highly tournament-dependent and not worth making automatic).

Or, to put it the other way round: say that some teams in a given break round need to be "deactivated". What would, or should, Tabbycat do with that information?

**Comment by philipbelesky** [comment]
I swear I had tested it at some point, but maybe I am misremembering. At smaller tournament's I've certainly had situations where a breaking team had to be deactivated for particular break rounds (say flight times clashed with the GF). 

Anyway I guess the question is whether the checkin process for teams should be preserved for elimination rounds, and (related) how `DrawGenerator` should deal with circumstances where some teams have been deactivated. I'm inclined to preserve the existing workflow of having there be some checkin process, even if it is largely automated and explain to the user. It helps to keep things consistent, and to the extent break round draws can be a bit of a black box, being able to check which teams are in the draw (and why) seems beneficial over having it be automatic. 

So for example the 'checkin breaking teams' or 'checkin advancing teams' buttons would ideally check in the correct teams, with a confirmation alert to the effect of say 'Checked in the bottom 16 teams in the Open Break (top 8 teams skip the Partial Octo)' or 'Checked in 8 teams advancing from Partial Octo and the top 8 teams from the Open Category)'. In either circumstance the function (choosing which teams to make debates for) happens, but by having it be in availability there is the opportunity to explain in a bit more detail to the user and potentially account for edge cases.

**Comment by philipbelesky** [comment]
Context, in terms of possible edge cases away from a 'standard' focto type arrangement:

> "In terms of the Seniors - so there are 13 Divisions which means there will be 13 division winning teams. These 13 teams will progress directly to the Octofinals. The 3 remaining Octofinal spots will be determined by a preliminary final/partial elimination. So the top 6 non Division winning/wildcard senior teams will debate against each other in order to determine the 14/15/16th ranked teams for the Octofinals."

**Comment by philipbelesky** [comment]
Redundant given the other changes made to break round draw generation. The above focto case can be accommodated by either setting draw flags or manually making matchups.
