### ISSUE TITLE
Importer should trip run returned lines/values through strip()

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#328]
Leading/trailing whitespace is an annoyance when running the importer. Presumably this should go in `base.py` sometime but I don't have time to figure out where atm.

**Comment by czlee** [comment]
It's not already doing that? :confused:

**Comment by philipbelesky** [comment]
Seems not to be; perhaps just in this circumstance (institution lookups). For that matter the lookup should be case insensitive as well.

**Comment by philipbelesky** [comment]
Also for that matter boolean fields should read null values as false (this seems not be the case for `use_institution_prefix`

**Comment by philipbelesky** [comment]
Ditto for adjudicators being imported without a `test_score`. I'm editing the `demo` CSVs to account for these edge cases, will push up in a second.

**Comment by czlee** [comment]
Do you need this dealt with soon?

**Comment by philipbelesky** [comment]
Nah, I don't have much data so its easy to work around all of these issues. One more:

- cell in `team_conflicts` called 'A Team Has No Name' throws:
- `ERROR importer.base: line 5, creating adjudicator-team conflict: Couldn't parse line: No institution matching 'A Team Has No'`
- Not sure why its truncating the name, or trying to parse it as an institution. Perhaps the lookup is assuming team names have institutional prefixes?

**Comment by czlee** [comment]
Possible, will look into it

**Comment by czlee** [comment]
Keep listing hiccups here :smile:

**Comment by philipbelesky** [comment]
Ha, be careful what you wish for. When importing regions.csv:

`IntegrityError: duplicate key value violates unique constraint "participants_region_pkey"`

I assume regions importing isn't checking for existing objects (this was a re-import)

**Comment by czlee** [comment]
with re-imports you might have to hit a command line option to get it to ignore duplicates

**Comment by czlee** [comment]
`TeamManager.lookup()` currently assumes that the last word of a team name is its reference, and all other words are the institution. It's marked as a `TODO`. There is a much bigger question of "how do we identify teams by human-written names?" that I was avoiding at the time.

**Comment by philipbelesky** [comment]
Ok, to summarise this:

[  ] Leading/trailing whitespace in fields isn't trimmed in institutional lookup
[X] Boolean fields should read null values as false
[X] Adjudicators should be able to be imported without a test_score
[  ] `team_conflicts` can't lookup teams that dont use prefixes

Should these be split into seperate issues?

**Comment by czlee** [comment]
No, the only one that was hard was the last one, and now that I've done #334 it's actually very straightforward (since the inability to search by long/short name was the main inhibitor before then).

**Comment by czlee** [comment]
The new whitespace strategy is to strip whitespace before a line runs through the interpreter, as in 5690147. The Python csv library has built-in support for stripping leading whitespace but not trailing whitespace: https://docs.python.org/3/library/csv.html#csv.Dialect.skipinitialspace. So I'm just doing the stripping in the importer.

A note: I'm not permitting extra whitespace in the _middle_ of a name, _e.g._ `"Caltech  2"`. We could go through every item in the CSV file, collapsing all whitespace into a single space, but that seems overkill to me—registration officers should be able to keep whitespace in the middle of a cell out.
