### ISSUE TITLE
Should feedback/ballot submission URLs be lowercase?

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#329]
Just a thought that it may be non obvious to people the URLs can be case sensitive, and that entering them in mobile devices is kind of a pain. If we need more entropy I think it would be better to have a longer string instead.

**Comment by czlee** [comment]
If this is in fact a problem then this is fine with me. I use Swype, so at the point that it's not a word in the dictionary, I find case doesn't tend to make much of a difference in degree of nuisance when typing, but that might just be me.
