### ISSUE TITLE
Apparent missing dependency for pylibmc

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#33]
I got this when running `pip install -r requirements.txt`:

```
Downloading/unpacking pylibmc (from django-pylibmc-sasl==0.2.4->-r requirements.txt (line 15))
  Running setup.py egg_info for package pylibmc
    
    warning: no files found matching 'LICENSE'
    warning: no files found matching 'runtests.py'
    warning: no files found matching '*.py' under directory 'pylibmc'
Installing collected packages: pylibmc
  Running setup.py install for pylibmc
    building '_pylibmc' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DUSE_ZLIB -I/usr/include/python2.7 -c src/_pylibmcmodule.c -o build/temp.linux-x86_64-2.7/src/_pylibmcmodule.o -fno-strict-aliasing
    In file included from src/_pylibmcmodule.c:34:0:
    src/_pylibmcmodule.h:42:36: fatal error: libmemcached/memcached.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    Complete output from command /home/czlee/git/tabbycat/venv/bin/python -c "import setuptools;__file__='/home/czlee/git/tabbycat/venv/build/pylibmc/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-wdEsqJ-record/install-record.txt --install-headers /home/czlee/git/tabbycat/venv/include/site/python2.7:
    running install

running build

running build_py

running build_ext

building '_pylibmc' extension

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DUSE_ZLIB -I/usr/include/python2.7 -c src/_pylibmcmodule.c -o build/temp.linux-x86_64-2.7/src/_pylibmcmodule.o -fno-strict-aliasing

In file included from src/_pylibmcmodule.c:34:0:

src/_pylibmcmodule.h:42:36: fatal error: libmemcached/memcached.h: No such file or directory

compilation terminated.

error: command 'gcc' failed with exit status 1

----------------------------------------
Command /home/czlee/git/tabbycat/venv/bin/python -c "import setuptools;__file__='/home/czlee/git/tabbycat/venv/build/pylibmc/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-wdEsqJ-record/install-record.txt --install-headers /home/czlee/git/tabbycat/venv/include/site/python2.7 failed with error code 1 in /home/czlee/git/tabbycat/venv/build/pylibmc
Storing complete log in /home/czlee/.pip/pip.log
```

Probably a dependency we need to instruct about, am looking it up.

**Comment by udbhav-tiwari** [comment]
python-dev may also be required to fix all dependecy issues, as found here 
http://kirang89.github.io/blog/2013/01/24/installing-pylibmc-in-ubuntu/
The install was giving me errors even after installing the libmemcached-dev and installing the python-dev fixed it!

**Comment by czlee** [comment]
It appears I already have that on my machine, so that's great to know, thanks!

**Comment by czlee** [comment]
Have updated documentation:
https://github.com/czlee/tabbycat/wiki/Installing-locally

There might actually be more, but we'll add them as we confirm they are in fact actual dependencies (_i.e._, as someone who tries to install Tabbycat discovers them).

**Comment by philipbelesky** [comment]
Following up on a note that I recently made to myself when I had similar install issues with memcache on OS X. [This metafilter thread](http://stackoverflow.com/questions/14803310/error-when-install-pylibmc-using-pip) had the relatively easy fix.

**Comment by philipbelesky** [comment]
Closing as pylibmc has been removed from the local requirements.

**Comment by phydroxide** [comment]
> This failed for the same reason:
> 
> ```
> pip install pylibmc
> ```
> 
> Then I ran
> 
> ```
> sudo apt-get install libmemcached-dev
> ```
> 
> and then tried again and it worked.
> 
> An internet search suggested this several times over:
> http://stackoverflow.com/questions/11507639/memcached-on-heroku-w-django-cant-install-pylibmc-memcacheify
> http://stackoverflow.com/questions/20388722/installing-pylibmc-on-ubuntu
> but I haven't found anything suggesting a way to check for it using `pip`.

This is precisely how I resolved it on Mint 20:

 sudo apt-get install libmemcached-dev
...
The following additional packages will be installed:
  libhashkit-dev libhashkit2 libsasl2-dev
The following NEW packages will be installed:
  libhashkit-dev libhashkit2 libmemcached-dev libsasl2-dev
...


pip3 install pylibmc
Collecting pylibmc
  Using cached pylibmc-1.6.1.tar.gz (64 kB)
Building wheels for collected packages: pylibmc
  Building wheel for pylibmc (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/pwaters/oci_sdk_env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p9ff69aj/pylibmc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-p9ff69aj/pylibmc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-4p48tztr
       cwd: /tmp/pip-install-p9ff69aj/pylibmc/
  Complete output (10 lines):
  /tmp/pip-install-p9ff69aj/pylibmc/setup.py:98: DeprecationWarning: 'U' mode is deprecated
    with open("README.rst", "U", encoding="utf-8") as r:
  /tmp/pip-install-p9ff69aj/pylibmc/setup.py:100: DeprecationWarning: 'U' mode is deprecated
    with open("src/pylibmc-version.h", "U", encoding="utf-8") as r:
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for pylibmc
  Running setup.py clean for pylibmc
Failed to build pylibmc
Installing collected packages: pylibmc
    Running setup.py install for pylibmc ... done
Successfully installed pylibmc-1.6.1

**Comment by lzy3240** [comment]
> > This failed for the same reason:
> > ```
> > pip install pylibmc
> > ```
> > 
> > 
> > Then I ran
> > ```
> > sudo apt-get install libmemcached-dev
> > ```
> > 
> > 
> > and then tried again and it worked.
> > An internet search suggested this several times over:
> > http://stackoverflow.com/questions/11507639/memcached-on-heroku-w-django-cant-install-pylibmc-memcacheify
> > http://stackoverflow.com/questions/20388722/installing-pylibmc-on-ubuntu
> > but I haven't found anything suggesting a way to check for it using `pip`.
> 
> This is precisely how I resolved it on Mint 20:
> 
> sudo apt-get install libmemcached-dev
> ...
> The following additional packages will be installed:
> libhashkit-dev libhashkit2 libsasl2-dev
> The following NEW packages will be installed:
> libhashkit-dev libhashkit2 libmemcached-dev libsasl2-dev
> ...
> 
> pip3 install pylibmc
> Collecting pylibmc
> Using cached pylibmc-1.6.1.tar.gz (64 kB)
> Building wheels for collected packages: pylibmc
> Building wheel for pylibmc (setup.py) ... error
> ERROR: Command errored out with exit status 1:
> command: /home/pwaters/oci_sdk_env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p9ff69aj/pylibmc/setup.py'"'"'; **file**='"'"'/tmp/pip-install-p9ff69aj/pylibmc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-4p48tztr
> cwd: /tmp/pip-install-p9ff69aj/pylibmc/
> Complete output (10 lines):
> /tmp/pip-install-p9ff69aj/pylibmc/setup.py:98: DeprecationWarning: 'U' mode is deprecated
> with open("README.rst", "U", encoding="utf-8") as r:
> /tmp/pip-install-p9ff69aj/pylibmc/setup.py💯 DeprecationWarning: 'U' mode is deprecated
> with open("src/pylibmc-version.h", "U", encoding="utf-8") as r:
> usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
> or: setup.py --help [cmd1 cmd2 ...]
> or: setup.py --help-commands
> or: setup.py cmd --help
> 
> ## error: invalid command 'bdist_wheel'
> ERROR: Failed building wheel for pylibmc
> Running setup.py clean for pylibmc
> Failed to build pylibmc
> Installing collected packages: pylibmc
> Running setup.py install for pylibmc ... done
> Successfully installed pylibmc-1.6.1

I had the same problem on mint 20.
