### ISSUE TITLE
Make Team.short_name and Team.long_name database fields

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#334]
I'm using the new "performance" label to log possible bottlenecks I find when profiling.

Numeric columns are: cumtime, per, tottime, per, count

Loading draw display by venue for round 8 of Australs 2015 dataset:
![image](https://cloud.githubusercontent.com/assets/1725499/16678823/907659f4-4497-11e6-9eb2-76c134b8dae7.png)

Loading draw display by team for round 8 of Australs 2015 dataset:
![image](https://cloud.githubusercontent.com/assets/1725499/16678836/ab4818b2-4497-11e6-9ec7-582fcd00957a.png)

where I've hidden deeper in the stack trace, all functions are in libraries (sometimes in debug_toolbar).

It seems to me that calling `Team.short_name` is taking quite a bit of time. Remember in these pages, there are _lots_ of team short names to find, but that's true of a lot of pages I think. In each of these cases it's going to the `get_cached_institution` function as intended. SQL calls comprise less than a second of a ~30-second load time, so I don't think the problem is that it's missing caches, and a quick look through the cache logs shows that it is indeed retrieving `teamid_xx__institution__object` a lot. It seems to me that even with the institution appropriately cached, and even though `short_name` is a `cached_property`, the act of piecing together the short name from the institution and reference, or maybe even retrieving it from the cache, takes a while.

Originally the idea behind the `Team.use_institution_prefix` and `Team.reference` structure was to make it easier to rename institutions, but it seems like it might not be worth the performance hit.

Idea is to make `short_name` and `long_name` database fields rather than Python attributes, and do one of the two following:

1. Abolish `use_institution_prefix` and `reference`, and provide tools (command-line if nothing else) to help easily change institution codes/names in team names. The tool would just parse the old names, detect if it looks like an institution-prefixed name, and substitute the new name.

2. Keep the `use_institution_prefix` and `reference` fields, and write `Team.save()` to generate `short_name` and `long_name` on every save. Ideally, `short_name` and `long_name` should be read-only to other Python code, _i.e._, only `Team.save()` should be able to write to them. But this isn't that important; the point is just that `short_name` and `long_name` are both database fields, and `use_institution_prefix` and `reference` only exist for when the names need to be updated. Since this is affected by the institution's name, `Institution.save()` or a post-save signal on Institution will also need to find all related teams and update them with the new names.

This isn't so much of an issue for `Team.long_name`, because it's not used very often, but if we do one we may as well do both.

**Comment by philipbelesky** [comment]
Just a heads up that this has broken a large quantity of tests as creating a `Team` now requires `long_name`/`short_name` to not be blank. If its a matter of copy/pasting in the new fields let me know. Similarly the teams portion of the visual importer throws a similar error.

**Comment by czlee** [comment]
Well, that's bad.

The object populates the fields when `Team.save()` is called, which means that there are certain situations where the fields will not be auto-populated appropriately. For example, [`bulk_create`](https://docs.djangoproject.com/en/1.9/ref/models/querysets/#bulk-create) creates objects without calling `save()` (though I don't think we currently use `bulk_create()` anywhere. Maybe fixtures are too?

**Comment by czlee** [comment]
Oh, right, it's trying to validate the model before saving which won't work because the fields themselves don't know how to clean themselves. Will see what the best way to handle an autopopulated field is.

**Comment by czlee** [comment]
Bingo! https://docs.djangoproject.com/en/1.9/ref/models/fields/#editable

(Found at http://www.b-list.org/weblog/2006/nov/02/django-tips-auto-populated-fields/)
