### ISSUE TITLE
Heroku commands won't run after directory changes

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#341]
Probably a simple fix but `heroku run dj createsuperuser` and the like won't run as manage.py is a directory down.

**Comment by czlee** [comment]
^ That's obviously not a fix, just a workaround for the deploy_heroku script.

**Comment by philipbelesky** [comment]
Closing this as the new path has been added to the `post_compile` / `deploy_heroku` scripts and in the relevant docs. The workaround of just adding `tabbycat/manage.py` seems fine.
