### ISSUE TITLE
Split out BREAK_QUALIFICATION_RULE_AIDA_2016 into Easters/Australs variants

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#349]
Mental note that this should be ready prior to the next easters. Test cases for each variant are available in the `past_australs_easters` folder of the datasets repo where there are comparisons of past breaks and the changes that would result according to the new australs/easters rules.

**Comment by philipbelesky** [comment]
Link to #307

**Comment by czlee** [comment]
that commit was meant to close #349, not 309, typo
