### ISSUE TITLE
Add infrastructure for views unattached to a tournament

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#356]
Notable current cases:

- Shift confirmations
- WADL style 'mass draw pages'

First thought would be to create a number of new paths (added per-module as needed) in the base `urls.py` however I'm not sure how to then restrict the module-specific paths such that it doesn't try to load the ones that are tournament specific. Maybe a `include('participants.urls_xtournament'))` style pattern? Having an extra `urls_xtournament.py` in the few modules that have cross tournament urls is a little annoying but probably good for structuring things.

**Comment by czlee** [comment]
Yeah, maybe we should have a helper function that just looks up all of the relevant url files in each named module, and add them if they exist.

**Comment by czlee** [comment]
Actually that makes no sense, since the cross-tournament ones would be referenced from a different file.
