### ISSUE TITLE
Ballot entry crashes with evenly-divided panel

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#370]
We had this error report:
```
ResultError at /Test/admin/results/debate/16/new/ No team had a majority in T1 1 vs T5 1.
```
with this POST data:
```
aff_motion_veto = ‘14’
aff_score_a25_s1 = ‘76’
aff_score_a25_s2 = ‘76’
aff_score_a25_s3 = ‘75’
aff_score_a25_s4 = ‘38’
aff_score_a27_s1 = ‘75’
aff_score_a27_s2 = ‘75’
aff_score_a27_s3 = ‘74’
aff_score_a27_s4 = ‘37.5’
aff_speaker_s1 = ‘1’
aff_speaker_s2 = ‘2’
aff_speaker_s3 = ‘3’
aff_speaker_s4 = ‘1’
confirmed = ‘on’
debate_result_status = ‘C’
motion = ‘13’
neg_motion_veto = ‘15’
neg_score_a25_s1 = ‘75’
neg_score_a25_s2 = ‘75’
neg_score_a25_s3 = ‘74’
neg_score_a25_s4 = ‘38’
neg_score_a27_s1 = ‘76’
neg_score_a27_s2 = ‘75’
neg_score_a27_s3 = ‘75’
neg_score_a27_s4 = ‘37.5’
neg_speaker_s1 = ‘13’
neg_speaker_s2 = ‘14’
neg_speaker_s3 = ‘15’
neg_speaker_s4 = ‘13’
```

It looks like this is on a debate with two adjudicators, which isn't a use-case that we handle (and the assertion is designed to fail quickly on hitting it). Options:

1. Catch the case in the form as a `ValidationError` and insist that the user resolve it by the usual means of presenting form errors. Either than can enter a ballot where both judges vote the same way, or they can exit the form and fix the adj allocations.
2. Catch even panels when generating the form, and refuse to show the form, instead returning to the results page with an error message, just like it does with an empty panel currently.
3. Modify result.py to allow even panels with the chair getting the casting vote.
4. Do not allow adj allocations with even panels to be saved in the first place.
5. Do nothing.

Thoughts?

**Comment by philipbelesky** [comment]
I'm leaning towards (3), presuming it doesn't have any wider repercussions, ie have a high likelihood of causing bugs down the line. Two person panels are relatively hard to make accidentally; and they occasionally happen at small tournaments. If implemented though, there should be an alert/warning at the top of the ballot entry page explaining that if entered as a two person panel the chair will break any ties.

**Comment by czlee** [comment]
I think it should be safe to do without wider repercussions. Agree, should probably also put that same warning on the draw page.
