### ISSUE TITLE
AssertionError when break size is zero

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#371]
Error report:
```
AssertionError at /Test/admin/draw/round/4/create/ break rounds only make sense for break_size > 1 (found 0)
```

The assertion is a fail-fast—break categories should never have a break size of less than 2.

Options:
1. Enforce the minimum break size at the model level, using [`MinValueValidator`](https://docs.djangoproject.com/en/1.10/ref/validators/#minvaluevalidator).
2. Catch the AssertionError and present it to the user as an error message.

I lean towards (1). Thoughts?

**Comment by philipbelesky** [comment]
Yea I think (1) is ideal
