### ISSUE TITLE
‘ForfeitBallotSet’ object has no attribute ‘_dts_lookup’

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#374]
Internal Server Error: /juniorpremier2016/admin/results/debate/541/new/

AttributeError at /juniorpremier2016/admin/results/debate/541/new/ ‘ForfeitBallotSet’ object has no attribute ‘_dts_lookup’

Traceback:

```
File “/app/.heroku/python/lib/python3.5/site-packages/django/core/handlers/exception.py” in inner
39.             response = get_response(request)
File “/app/.heroku/python/lib/python3.5/site-packages/django/core/handlers/base.py” in _get_response
187.                 response = self.process_exception_by_middleware(e, request)
File “/app/.heroku/python/lib/python3.5/site-packages/django/core/handlers/base.py” in _get_response
185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
File “/app/.heroku/python/lib/python3.5/site-packages/django/contrib/auth/decorators.py” in _wrapped_view
23.                 return view_func(request, *args, **kwargs)
File “/app/tabbycat/utils/views.py” in foo
28.         return view_fn(request, request.tournament, *args, **kwargs)
File “/app/tabbycat/results/views.py” in new_ballotset
318.             form.save()
File “/app/tabbycat/results/forms.py” in save
477.                 ballotset.set_motion_veto(side, motion_veto)
File “/app/tabbycat/results/result.py” in set_motion_veto
524.         self.motion_veto[self._dt(team)] = motion
File “/app/tabbycat/results/result.py” in _dt
50.             return self._dts_lookup[team]

Exception Type: AttributeError at /juniorpremier2016/admin/results/debate/541/new/ 
Exception Value: ‘ForfeitBallotSet’ object has no attribute ‘_dts_lookup’
```

**Comment by czlee** [comment]
@philipbelesky: I started fixing this, but then when testing the changes I ran into this:

```
Traceback:

File "/home/czlee/git/tabbycat/tabbycat/venv/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  39.             response = get_response(request)

File "/home/czlee/git/tabbycat/tabbycat/venv/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  178.             response = middleware_method(request, callback, callback_args, callback_kwargs)

File "/home/czlee/git/tabbycat/tabbycat/venv/src/django-debug-toolbar/debug_toolbar/middleware.py" in process_view
  87.             response = panel.process_view(request, view_func, view_args, view_kwargs)

File "/home/czlee/git/tabbycat/tabbycat/venv/src/django-debug-toolbar/debug_toolbar/panels/profiling.py" in process_view
  151.         return self.profiler.runcall(view_func, *args, **view_kwargs)

File "/usr/lib/python3.5/cProfile.py" in runcall
  109.             return func(*args, **kw)

File "/home/czlee/git/tabbycat/tabbycat/venv/lib/python3.5/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/home/czlee/git/tabbycat/tabbycat/utils/views.py" in foo
  28.         return view_fn(request, request.tournament, *args, **kwargs)

File "/home/czlee/git/tabbycat/tabbycat/results/views.py" in new_ballotset
  318.             form.save()

File "/home/czlee/git/tabbycat/tabbycat/results/forms.py" in save
  478.                 ballotset.set_motion_veto(side, motion_veto)

File "/home/czlee/git/tabbycat/tabbycat/results/result.py" in set_motion_veto
  524.         self.motion_veto[self._dt(team)] = motion

Exception Type: TypeError at /demo/admin/results/debate/73/new/
Exception Value: 'NoneType' object does not support item assignment
```

I get the feeling something else is wrong—it's not meant to attempt to save the motion vetoes if there's a forfeit, right? How are forfeits supposed to work?

**Comment by philipbelesky** [comment]
Um, I don't think Forfeits were designed to be used in the context where there are motion vetoes. They should probably explicitly not attempt to do so — ie `if self.using_vetoes and not self.`forfeit_declared`. IIRC forefeits are a method of producing a two TeamScore's that have normal points/margin/win values but with scores of 0 and a `forefeit` flag to prevent them from being used in standings and the like.

**Comment by czlee** [comment]
How about the other way round: what _should_ be saved? Currently it looks like the form does a lot of redundant work entering scores _etc._ into the `BallotSet` object, even if there's a forfeit.

It should just be `discarded`, `confirmed` and `Debate.result_status`, I guess? Everything else is auto-filled? So `BallotSetForm.save()` should short-circuit most things if it's a forfeit (it currently doesn't)?

I'm wondering if entering forfeits is best done through a different interface, say, similar to the postponement links?

**Comment by philipbelesky** [comment]
I think it was implemented before a `BallotSet` refactor, hence the short-circuiting. 

I don't think there is much upside in making a second interface, partly because it will disrupt existing use cases and that a forfeit seems to fit within the 'a debate state altering outcome' kinda role that those pages cater for currently. What is the impetus for splitting it off?

**Comment by czlee** [comment]
Maintainability. Forfeits by definition don't entail any scores or motions or anything, so there's a bunch of logic to un-require most of the field on the form, both in Python and in JavaScript—already a violation of DRY. But more importantly this makes it hard to modify the ballot set form (say, add a field) without needing to modify all this logic appropriately. Essentially, the logic for dealing with (complete) ballots isn't encapsulated appropriately. If forfeits aren't interested in scores _etc._ then they shouldn't deal with them—they shouldn't have to work around them floating around in the background.

To give one example of how the DRY thing gets messy: The Python code for `BallotSetForm` un-requires _all score_ fields if forfeits are _enabled_. But it still (manually) decorates the fields with the `required` class, so that JavaScript will pick up on it and _conditionally_ validate it client-side. Normally forms validate server-side (where you're immune from client interference or stupidity), and client-side validation adds convenience, but in this case server-side validation is turned off completely. It's not crippling—if you bypass client validation you just get a 500—but I tend to think it's not how forms are supposed to work. If `required` is set in Django correctly, the CSS class isn't needed for client-side validation to function (I think it works off the `required` attribute, which is set by Django, as opposed to CSS class).

I don't think any of this is very urgent, this is more a discussion of how I think the forms should be structured eventually.

Question: Why are forfeits tied to ballot submissions? Is the idea that a forfeit and a completed ballot are "competing versions" of a result? Or was that just for convenience so you could get something in the database for team scores?

**Comment by czlee** [comment]
I should say—we could (without too much difficulty) write in form logic that also _conditionally_ requires scores and motions when it's in fact a forfeit. But that doesn't get around DRY, since said Django form logic won't trigger JavaScript (it would be implemented in `BallotSetForm.clean()`, not field properties. And also I think it's a bit much to have `clean()` check almost every field on the form for blankness—this is exactly the use-case for the field `required` property, it's just we're conditionally ignoring most of the form based on part of it. I don't have a problem with this in a UI sense, but unless there's a very good UI reason to have it in the ballot set form, I'd default to the more maintainable code.

**Comment by philipbelesky** [comment]
Yea, the idea is that they are both tied to a result; and that if you wanted to 'fix' a false forfeit you could do so by creating a new ballot submission or by editing the original one. It also seems the most intuitive place for it given the general results workflow.

If this issue is with code maintainability on the front and backend for that results form, how about a split solution, where if forfeits are enabled that box on the result form contains a link, say 'One of the teams forfeited'. This then loads a *new* form/page for that specific debate which allows the user to nominate which team forfeited and then submit the result. This page can then have completely distinct form/view/validation code to keep the cases clean. It adds an extra step from the user's perspective, but maintains the existing workflow and keeps the forfeit entering where it intuitively belongs.

**Comment by czlee** [comment]
Yeah, the extra step option totally works for me.

I was also thinking about it this afternoon, if it's worth the effort to
keep the UI intuitive, we could write subclasses of things to abstract out
the conditionally required fields, so that they can be specified in exactly
one place, through a new property, like "`required_except_forfeit`" or
"`normally_required`". Then both JS and Python logic would draw specs from
the same place. That would be a bit of an investment, but it can work in
principle.

Question: Is there a hypothetical scenario where two *different* forfeits
in the *same* tournament should get different TeamScore specifics like
scores/margins/points? Or, conversely, is it more sensible to have a
framework where the forfeit treatment for a tournament could be adjusted
after the fact in the same place? My instinct is to allow for the former,
but just wanted to see what you think.

**Comment by philipbelesky** [comment]
Syncing up front and backend validation is always a bit of a pain — you could definitely pass custom attributes like `required_except_forfeit` as `data-attributes` or something but the frontend would still have to enable its own conditional logic in response to that flag (unless you want to sink a lot of time into fully abstracting the js out somehow?).

By `forefeit treatment` you mean like a universal set of rules for what a forefeit implies in terms of scores/margins/speaks? I think there probably is per-tournament, although exceptions may occur (but I can't think of the scenario though). I assume the latter would equate to having a configurable set of outcomes ?

**Comment by czlee** [comment]
Well, the idea would be that you sink time into abstracting out the JS and Python, to mitigate both future routine tasks and potential for mistakes when adding fields. But I agree it would be a pain (or, euphemistically, an investment), so it's only worth doing if the UI would be substantially better entering forfeits from the same page.

Yes, that's what I mean. The latter would mean that, and it could also mean we don't bother saving `TeamScore` instances for forfeits, since they would be implied by the fact that it was a forfeit. My instinct is that it's probably better to allow for the flexibility to do per-debate treatment, so that in the edge case tab directors can just edit the database; and if needing to configure how forfeits work becomes a thing then we should just write code to overwrite the TeamScores for all existing forfeits.

**Comment by czlee** [comment]
(The above discussion about how forfeits work should be continued in a new issue.)
