### ISSUE TITLE
Consensus ballots

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#375]
So this is mostly an issue with the underlying data structure. The user experience of the entry itself would be reasonably simple.

The laziest option would just be too link the three ballot forms together, such that entering in a 'master' copy will duplicate data across the others. There may be some benefit to having this approach (ie keeping seperate TeamScores/SpeakerScores) in the database in being able to transition between consensus and non-consensus settings.

@czlee you know the ballots/results code much better than me so I'll leave the non-lazy option spec to you :p. If the non-lazy option isn't horribly flawed I could implement the setting front-end code for it whenever.

**Comment by czlee** [comment]
Only `SpeakerScoreByAdj` is kept on a per-adjudicator-debate-team basis anyway. Just thinking out loud:

- `SpeakerScoreByAdj` would basically be useless in this context. We could ditch it.
- This would render a lot of the logic in `BallotSet` superfluous; a new class might just write directly to `SpeakerScore` from the data entry, and do away with `Scoresheet` too.
- But then either `BallotSetForm` would need to know how to deal with both classes, or the new consensus ballot set class would need to use the same interface as the existing one.

On the other hand, we could leave the back-end in-place and only change the function of panellists, _i.e._, panellists are treated like trainees in the tab system. This seems at face simpler, not sure whether better or worse.

**Comment by czlee** [comment]
Quick note: It would actually beneficial not to use SpeakerScoreByAdj, or at least not to have the UI rely on SpeakerScoreByAdj, because that way we could change adjudicators after debate results are entered without losing any data.

**Comment by czlee** [comment]
A first pass of this is done as of 84eabaa and is on the refactor/ballots branch. Because it's a significant restructure, I want to wait until after Australs before merging this into develop.

**Comment by philipbelesky** [comment]
Just a heads up: this has been merged in and a draft version of the Canadian Parliamentary format added. I'll try and check in with someone from Canada to nail down what the presets are.

**Comment by philipbelesky** [comment]
Should this be closed? Are there any edge cases or testing procedures we should run through prior to release?

**Comment by czlee** [comment]
None that I can think of, it can be closed.
