### ISSUE TITLE
Canadian Parliamentary support: motion fiat and flexible sides

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#376]
AFAIK in some Canadian Parliamentary formats aff gets to choose the topic (from any conceivable topic) and neg gets to choose sides. Both of these are supported by the system in terms of data structures but would require changes to the frontend to make them easier to enter. Namely:

- [ ] If a motion fiat config option is enabled, the result form offers up a text field for arbitrary motion entry. Upon saving that motion is set as selected for that debate
- [ ] There should be some easy method to swap the sides of each team within the results form. This probably requires a decent refactoring of the results form to do client side, which I might use as an excuse to convert the entire form to a Vue component (this will tidy up the validation methods at the same time).

Last item relates to #163, in that for this format (and NZ easters) debates could be presented in a pre-allocated-sides state.

**Comment by czlee** [comment]
I know APDA tab software currently doesn't care for motions, not sure about CP but I wouldn't be surprised if recording cases just wasn't considered a useful feature.

Not 100% about CP but if it's anything like APDA, choosing sides isn't _really_ choosing sides—the opposition can choose which side of the case to argue, but they still speak in the same order, and they are still the opposition, _i.e._ it's more that the government flips their case, than it is that they swap sides.

Will check with someone more knowledgeable about both.

**Comment by czlee** [comment]
Yeah, I think neither of these are necessary, certainly not for minimum-viable. Case recording is at best a nice-to-have. Opp choice doesn't involve actually swapping sides.
