### ISSUE TITLE
Prevent users from generating draw before break is generated

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#385]
#Draw generation for a first elimination round (rightly) crashes when there are fewer than two breaking teams. We currently prevent users from setting a break size smaller than two, but that still leaves the following scenarios:

- [x] 1. A user tries to generate a first elimination round draw before generating the break.
- [x] 2. The break is generated and break size is correct, but due to other reasons (_e.g._ eligibility constraints, other breaks), there happen to be fewer than two breaking teams.

(1) is probably not too hard, we can catch that before it happens in the UI.

I'm not sure exactly what to do about (2) though. We could catch it before it happens, but I guess this is the sort of situation I have in mind with #384. Relying on a catch-before-it-happens whose condition is coded separately violates DRY, in that we'd need to keep them in sync in future. The condition is actually nontrivial (not difficult, just nontrivial) to write—you have to filter eligible teams appropriately and stuff. (The risk of future changes isn't so much the at-least-two requirement as it is how breaking teams are classed/filtered.) My instinct is that it's rare enough to be the sort of situation we want to just catch after the fact, and have a good means of handling (that would also extend to handling other errors).

That said, before said #384 system exists, I'm also fine with just catching it separately before it happens.

**Comment by czlee** [comment]
I forgot that I already implemented such a #384-style system for draw generation, it catches `DrawError` lol. I'm modifying it to also do a `logger.critical()` whenever it catches a `DrawError`, and of course to catch `AssertionError` during that call and convert them to `DrawError`s. So that's (2) handled. Just need to catch (1).

**Comment by czlee** [comment]
Done (1), @philipbelesky you might like to review it, it affects the break round generation workflow. Other than relevant alerts/messages, the main change is that rather than taking the break size, the check-ins page now takes the number of teams that will actually compete in the break rounds for the relevant category.

**Comment by czlee** [comment]
Also I forgot to put this on hotfix and it turns out that the cherry-pick to develop is brimming with conflicts so it'll have to wait until v1.2.0 :disappointed:

**Comment by philipbelesky** [comment]
Ah, maybe we should just release 1.2.0 rather than a hotfix then? I've made a note to checkout the  changes here.

**Comment by czlee** [comment]
Could do. 1.2.0 is quite the migration though, since it involves two ContentType refactors, so I'd probably want you to roll it out on a couple of sites first if you have a means of doing so?
