### ISSUE TITLE
Allow venues to be in multiple groups

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#388]
One oversight when I implemented #318 (and that we hit at Australs) was that the groups you want to use for constraints might not, and probably often won't, match the groups you want to use for other logistical purposes, like maps/room labelling.

Ideally, for constraints, we'd want venues to be able to be part of more than one group, in case, say, "step-free access" and "close to briefing room" intersect but neither is a subset of the other, and then in case they're each subsets of two or more colour zones. We can't do this in the current database structure. But at the same time, we can't just convert `Venue.group` into a `ManyToManyField`: the database needs to know about some sort of "primary group".

Here are some options:
1. Stop using `VenueGroup`s for venue constraints entirely, and just create a new `ConstraintVenueGroup` that is basically the same as `VenueGroup` except in name, and in that it would be related to `Venue` through a `ManyToManyField` rather than a `ForeignKey`.
   - Advantage: Easiest abstraction to understand, almost no change to existing logic
   - Disadvantage: Where constraint groups and logistical groups do align, you have to enter the data twice.
2. Add a new field `Venue.constraint_groups` that is a `ManyToManyField(VenueGroup)`. The existing `Venue.group` field remains in place. When querying for what groups a venue is in or what venues are in a group, query for both `group` and `constraint_groups`.
   - Advantage: Simplest addition, avoids double data entry
   - Disadvantage: Queries would be complex
3. Use `VenueGroup`s for constraints as currently, and change `Venue.group` to a `ManyToManyField`. In the `through` model, include a boolean field `primary`, for which only one group per venue can be `True`. Then rewrite `group` to retrieve the group for which `primary` is True.
   - Advantage: An easy database schema to understand
   - Disadvantage: Prefetches would be difficult, but not impossible: `VenueManager.prefetch_related()` can be overridden to catch for a `'group'` argument, and convert it to `Prefetch('groups', queryset=VenueGroup.objects.filter(primary=True), to_attr='_primary_groups')`.

I think I lean towards (1), just taking the double data entry hit. @philipbelesky, would you have any thoughts?

**Comment by philipbelesky** [comment]
Sure, (3) is somewhat conceptually attractive, but with things like the WADL views, where every venue has a group that needs to be displayed, it sounds like the performance might be difficult? 

Having seperate data entry processes is probably useful as well in terms of clarifying what each type is for. The constraints-model should probably be labelled slightly differently though, perhaps `ConstraintVenueType` rather than `ConstraintVenueGroup`?

**Comment by czlee** [comment]
Yeah, I think (3) can be done in a way that doesn't degrade performance by much (_i.e._ by more than one database hit per view), but it'd be annoying. A bit like retrieving confirmed ballots for each debate, whose structure is similar—I figured out that it can be done with a `prefetch_related()` but you still end up getting the ballot as a list of one item rather than the item, which you then have to deal with yourself in the class.

Agree name should be different—that's a good point. Not sure what the name should be though, "type" doesn't quite do it, since I sort of conceptualise them as... well, groups. Or sets.

**Comment by czlee** [comment]
@philipbelesky It's not obvious to me whether divisions should continue to use venue groups, or whether they should use the new venue constraint categories (as I've decided to call them). In order for them to use venue constraint categories, I'd have to move the `team_capacity` field to venue constraint categories (I think). In order for them to use venue groups, I'd need to have a new division venue constraint/preference model that references venue groups rather than venue constraint categories (like the current model, since I'm changing the model to refer to categories _instead of_ groups). Also, remember that unlike venue groups, venue constraint categories need not be disjoint. Thoughts?

**Comment by philipbelesky** [comment]
@czlee um, I'm fine with the new VenueConstraintCategories effectively superseeding VenueGroups as long as they can be used in effectively the same manner. Which probably does mean tacking on a `team_capacity` for legacy's sake. What's the timeframe for this likely to be? I'll need to update a bunch of WADL code and documentation, ideally before when their draw is being prepared.

We should also consider how the new VenueConstraintCategories being many-to-many works in terms of visual presentation. When identifying venues by category (replacing identifying them by VenueGroup) do we just show the first category `Red 45` (ie pseudo replicating the old functionality); show all of them `Red Accessible 45`; or have some way of marking which VenueConstraintCategories should be visible on the public draw `Red 45` (frontend) `Red, Accessible 45` (backend)?

**Comment by czlee** [comment]
On timeframe, probably one more week? It's my next task, and it's not too difficult, mainly annoying with renaming things. If you're willing to do the WADL work, it could be a couple of days, since divisions is the second main difficulty (after migrations).

I was going to keep the old VenueGroups around for display purposes, the idea being that venues are divided into venue groups for participants' physical navigation ease, but constraint categories have an entirely different and orthogonal purpose. Because categories are a many-to-many relationship there's not really a concept of a "first category"; even if that's marked with a Boolean, given that the "primary category" in many cases won't be used for accessibility, it seems a better model to me just to keep the two entirely distinct.

**Comment by czlee** [comment]
On another note, I've just concluded that it's practically impossible to make this migration reversible, so it won't be possible to roll back from 1.2 to 1.1 (at all, not even if you allow data loss).

**Comment by philipbelesky** [comment]
That seems fine. The only people I can think of who might want to roll back this change would be WADL and I can handle the contingencies for this.

**Comment by czlee** [comment]
@philipbelesky Would you want to add anything to the edit venues UI for this, say, to show which venue constraint categories a venue is in, or even to point out on the edit venues screen when a constraint is unmet? Or even if so, maybe not now, but when you next do a makeover of the edit venues UI?

(fwiw, I don't think this is at all a high priority, just thought I'd ask.)

**Comment by philipbelesky** [comment]
@czlee Yea I think that would be ideally done as part of #354.
