### ISSUE TITLE
Visual importer: Handling of uniqueness violations

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#395]
Related to #394, just making a separate note so I remember to test for it.

Currently, if you create a team with the same institution and reference as an existing team, it gives a 500 with the following ProgrammingError:
> duplicate key value violates unique constraint "participants_team_reference_2c58fafe_uniq"
DETAIL:  Key (reference, institution_id, tournament_id)=(1, 11, 1) already exists.

It should fail more gracefully.

**Comment by philipbelesky** [comment]
Pretty sure this was fixed in ce554f6a260e54eb7d23a89efe57215c165b9501

**Comment by czlee** [comment]
Oh, I intended for this to be a reminder for when I implement #394. Integrity errors can technically be due to more than just uniqueness violations I think, so the current solution works fine, but not as robust as it could be. But any further work would depend on #394.
