### ISSUE TITLE
Don't expect feedback for silent rounds

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#396]
Currently making a round silent overrides everything, which means you have to unsilent a round to release its results. As far as redundancy goes, this is probably a good thing; I'm sort of reluctant to change the logic that always hides silent rounds even if the "release all" box is checked.

Probably the way to distinguish between rounds where feedback is and is not expected is to have a new Boolean field associated with the round, called "expect_team_feedback" or something, that for most rounds should match the silent box until after silent results are released. This risks overcomplicating the configuration, but is probably better in terms of customisability. (Thoughts?)

**Comment by philipbelesky** [comment]
I don't think it's per-se a huge problem — at the point results are released then efeedback is almost always irrelevant or shut down. So maybe I'm missing a use case but having only one kind of silent seems easiest.

**Comment by czlee** [comment]
The problem's the other way round, though: If we only have one kind of silent, then either (a) the "release all" mechanism has to override the "silent" setting, which reduces redundancy against accidental silent round release , or (b) once rounds are unsilented, record pages will erroneously show that feedback has not been submitted. Unless you were thinking of hiding the public feedback progress records after a tournament is over? In which case, we should probably turn them off for Australs 2016…

**Comment by philipbelesky** [comment]
I’d be relatively happy with (a) overriding the silent setting. Release All is a relatively 'advanced feature' in that it is a little hard to find/activate. In every case I’ve used it it’s been the end of a tournament such that you’d naturally want silent rounds to also be released then.

**Comment by czlee** [comment]
Hmm, okay. I'm actually more worried about bugs than user error (remember what happened at WAustrals?) but maybe my assessment of the risk mitigation of having silence override everything is misplaced.

**Comment by czlee** [comment]
Ah, I see you've already done that. So really the only fix needed was to show silent rounds on team record pages when all results are released, which I've done in 5f71c5a6481dd67cb7f52c3a59509c16cc8d2d77.
