### ISSUE TITLE
django-dynamic-preferences 0.8.3 crashes the settings pages

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#397]
django-dynamic-preferences released 0.8.3 recently which includes this commit introducing a mandatory parameter (that is not in 0.8.2):
EliotBerriot/django-dynamic-preferences@723f2ece8376b07bbb9ccb5ee689a4fca08ae20f
which appears to break all of the settings pages.

I'm not entirely sure what `sections_url_name` is supposed to be, but it shouldn't be too hard to fix. But I'm also not sure whether this would break installations using 0.8.2, in which case we'd need to update `requirements_common.txt` accordingly.

**Comment by czlee** [comment]
I've fixed it in the sense that it shouldn't crash anymore, but it's not clear to me that this setting does anything, it's only used in the template [sections.html](https://github.com/EliotBerriot/django-dynamic-preferences/blob/3052d3c30be94a42983715811a4cfd87bba9c94c/dynamic_preferences/templates/dynamic_preferences/sections.html), which is included in [base.html](https://github.com/EliotBerriot/django-dynamic-preferences/blob/3052d3c30be94a42983715811a4cfd87bba9c94c/dynamic_preferences/templates/dynamic_preferences/base.html). Do we use any of the built-in django-dynamic-preferences templates?

**Comment by philipbelesky** [comment]
Not having it in front of me, I think we inherit from their class based views somewhere. Also IIRC we are on the 0.8.X version of the library; so if 0.8.3 has introduced a regression we should bump the minimum up ASAP as part of 1.1.5.

**Comment by czlee** [comment]
The regression's fixed as part of 0.8.4 (Eliot got onto it super quickly, as you'll notice from the fact that EliotBerriot/django-dynamic-preferences#67 is now closed). Turns out the fix for 0.8.3 in bb6544d breaks compatibility with 0.8.2 and 0.8.4, so I might revert it…
