### ISSUE TITLE
Allow number of speakers/speeches per team to be specified

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#4]
Including:
* [x] Styles with two speakers only
* [x] Styles with and without replies

Ideally, software code would be written to be even more generic in the back-end code, but for simplicity constrained at the front-end.

**Comment by philipbelesky** [comment]
Assigning myself to this while I remember. I'm assume the best way to deal with Australian Easters is to have a config toggle for Replies, and use (a ton of?) conditions to hide the UI elements and change any tallying logic.

On another note is there any demand to use Tabby Cat at NZ easters? Would the change to two speakers be difficult?

**Comment by czlee** [comment]
Yup! Re NZ, not yet but it's been used at Joynt and won't be super-easy,
but shouldn't be hard and would also it to be used in American
Parliamentary, so it's worth doing.

I've already abstracted to constants for this purpose, which are members of
`Tournament` (`LAST_SUBSTANTIVE_POSITION` etc.), if I've done it right
those should be helpful. Ideally it should just be a matter of changing
those properties to retrieve the config rather than return constants. But
I've never actually tried it. (See cccc1d2.)

**Comment by philipbelesky** [comment]
Quick note that optional replies has been rolled into develop and is available via a config flag

**Comment by philipbelesky** [comment]
Up in 316eebe769f3d48be504acf44ef91160a9bcc196
