### ISSUE TITLE
Investigate deployment method that doesn't require heroku account verification (ie credit card)

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#412]
So it turns out heroku actually only requires a credit/debit card if:

- Use more than one dyno in the app.
- **Add any add-on to the app, even if the add-on is free. The only exceptions to this are the free plans for the Heroku Postgres and Heroku Connect add-ons, which can be added without verification.**
- Add a custom domain to the app.
- Receive the transfer of an app that has paid resources.
- Exceed default one-off dyno limits on the app.
- Have more than 5 apps at a time. Verified accounts may have up to 100 apps.

Of those the add-ons are the one we hit. Memcachier, papertrail, and sendgrid are arguably non-essential items that the app could run without. However it would mean not receiving error reports from the apps and potentially having apps without the ability to cache.

Having a credit card seems like a serious block for many people so this probably should be considered. I assume that we would either have a deploy setting or perhaps a second deploy button that uses this 'lite' option or perhaps having some sort of configuration option during the deploy wizard. 

Potentially we could mitigate the harms of not having an email/caching system by setting up a centralised copy of those services that the apps could then connect to if they are not present locally.

It might also be worth investigating a deploy button that automatically deploys the upgraded database for larger tournaments.

**Comment by czlee** [comment]
Second deploy button might be doable, but would involve some trickery. Basically involves a second app.json file somewhere else that is instructed to refer to this repository.

**Comment by philipbelesky** [comment]
@czlee looking into this it seems like there's no way around having `app.json` kept in the project root. We can point it to branches though. Would you have a problem with keeping around a `tabbycatlight` branch that just has the relevant addons deleted and that is then kept in sync with master? It's a little more work to remember to merge things there post-release each time but not a major pain.

Similarly any ideas for what to name this? Tabbycat Light? Tabbycat Light? Tabbykitten?

**Comment by philipbelesky** [comment]
Update:

- Tried setting an ENV variable in the deploy string. This worked, however there was no way to create addons in the `postdeploy` script that I could find. This meant there was no way to programatically set addons, and thus probably no way to do things with a single `app.json`
- Seemingly the `repository` value in an `app.json` field is only meta data; Heroku will build from the actual branch and repo that the app.json is located at. Thus orphan branches don't work. Maybe a `precompile` hook could switch the branch out? But I doubt it.

So idk; I'm leaning towards the 'just have a full branch that we do one-way merges to' but maybe you'll be able to find a method I couldn't. Note that I've kept the `kitten` branch around using this method (and for the README/docs updates).

**Comment by czlee** [comment]
Okay, here's my additional effort:

* Agree with orphan branch assessment.
* Also, I realized that even the Heroku [Platform API](https://devcenter.heroku.com/articles/setting-up-apps-using-the-heroku-platform-api) explicitly expects the app.json file to be in the source tarball, so it can't be separated from the code at all. I didn't realize this on my earlier reading.

That being the case I'm now also of the opinion that the "full branch with one-way merges" is our best option.

My one remaining concern is that our release process is starting to involve a few steps now (the others being updating version numbers in two places), and is hence error-prone. But that can only be solved by over-the-top things, like a script that checks that everything is in order that we run just before releasing, so isn't strictly relevant to this issue. Also I'm not too concerned about that just yet.

@philipbelesky I notice at the moment you've changed the readme on the kitten branch (3ede0b30d9fd4e00bda68dbfe8bcf092824bfc48). The standard "Deploy to Heroku" button, if clicked from https://github.com/czlee/tabbycat/tree/kitten, actually also deploys from the kitten branch (it deploys from whichever branch the current URL is). Were you planning to move that doc edit to develop, eventually? Also, is the `KITTEN=true` environment variable still used, or should we remove that from the deploy URL?

**Comment by philipbelesky** [comment]
Yea, a script might be overkill; maybe a checklist somewhere in the documentation would work?

The README changes for the kitten branch are probably a little confused as I think I lost the actual edit I wanted when deleting one of the aborted branch. Ill make changes to the README in develop as needed with a seperate deploy button linked to the kitten branch.

The KITTEN=true environment variable is worth sticking around, if just perhaps to help with debugging issues (say if we ever get added as collaborators to an app). In the future there might also be a way to send emails from a kitten app (either using an inbuilt email method or having a shared service) in which case it would be good to add that to the log.

Steps to close the issue

- [ ] Update the README in `develop` with explanatory text and a correct link
- [ ] Update the standard button in README to ensure it definitely goes from master
- [ ] Update the docs to refer to / explain the kitten process (as in README)

Anything else?

**Comment by czlee** [comment]
Nope, sounds good to me!
