### ISSUE TITLE
Bump to python 3.6

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#415]
Python 3.6 is released and is a [supported runtime for heroku](https://devcenter.heroku.com/articles/python-support#supported-python-runtimes). Will stick in a branch until it's clear that dependency support and code changes are all good.

**Comment by philipbelesky** [comment]
Note: may as well bump Postgres to 9.6 also as that is now the heroku default.

**Comment by czlee** [comment]
Hmm, this is interesting: https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals
(We're still pretty inconsistent in our code, sometime using the old-style `%` syntax, sometimes the new-style `.format()` syntax.)

**Comment by philipbelesky** [comment]
Both bumps seem to be working fine; have merged into `develop.` Tests and `deploy_heroku.py` I guess we can reopen if there are any issues.

**Comment by czlee** [comment]
Are we dropping support for Python 3.4 and 3.5, or keeping support for 3.4 through 3.6?

Also, we'd need to check this on Windows installations. I don't know when I get a chance to do that. The hold-up last time was [win-psycopg](http://www.stickpeople.com/projects/python/win-psycopg/). There's a bug in Python that prevents win-psycopg from working with 64-bit Python until 3.6.1 is released, so I guess we need to advise accordingly in Windows documentation?

**Comment by czlee** [comment]
Also, will you be developing on Python 3.6? Just wondering whether I should download Python 3.6 manually onto my Ubuntu machine now, or wait until it comes through the APT distributions (if it ever does).

**Comment by philipbelesky** [comment]
I will be. I'd recommend setting up [pyenv](https://github.com/yyuu/pyenv) and using that to handle installs.

**Comment by czlee** [comment]
Okay, I'll try and upgrade my Ubuntu and Windows environments soon.

**Comment by czlee** [comment]
- [ ] Check on Ubuntu 16.04
- [ ] Check on Windows 10

**Comment by czlee** [comment]
As discussed above, Windows can't be done until Python 3.6.1, which is expected to be [released 2017-03-13](https://www.python.org/dev/peps/pep-0494/#id1). What do we want to do in the meantime, tell Windows users to stick to Python 3.5 and PostgreSQL 9.5?

**Comment by czlee** [comment]
Actually, the lack of official support for Python 3.6 on Ubuntu 16.04 complicates installation quite a bit, so I'm reluctant to change docs for it, and just leave people to use Python 3.5 if that's what they have. (Python 3.6 is available through apt on 16.10 but not 16.04, there's a popular third-party PPA for 16.04 but it seems silly to insist that everyone use it if Python 3.5 works.) Would you have any objections to that?

**Comment by czlee** [comment]
Added advice for Windows in e955eec13c222418d0cdff8afefa58ad92757297, done as far as Foldex is concerned, successor issue is #423.
