### ISSUE TITLE
Bump travis' postgres to 9.6

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#416]
If `.travis.yml` specifies postgres 9.5 builds fail with `RuntimeWarning: Normally Django will use a connection to the 'postgres' database to avoid running initialization queries against the production database when it's not needed (for example, when running tests). Django was unable to create a connection to the 'postgres' database and will use the default database instead.`. 

Haven't really looked into it precisely but it seems like some aspects of newer versions are [not enabled in travis yet](https://docs.travis-ci.com/user/database-setup/). I assume the risk of regressions here are low so I'm noting this to check back in on this later.

**Comment by czlee** [comment]
If I remember right it's generally nontrivial to upgrade database between PostgreSQL versions—they don't just migrate, you have to dump and restore them. So we'd want to think about upgrade paths before bumping our standard expectation to 9.6.

**Comment by czlee** [comment]
Yeah, root problem is that 9.6 isn't installed:
```
$ sudo service postgresql stop
 * Stopping PostgreSQL 9.1 database server        * Stopping PostgreSQL 9.2 database server        * Stopping PostgreSQL 9.3 database server        * Stopping PostgreSQL 9.4 database server        * Stopping PostgreSQL 9.5 database server       
cp: cannot stat `/var/lib/postgresql/9.6': No such file or directory
$ sudo service postgresql start 9.6
PostgreSQL 9.6 is not installed!
```

That page you linked to indicates that it should work with Trusty (14.04) though (it's currently on Precise, which is 12.04), so if you like we could make Travis run on Trusty? I'm not sure why Precise is still their default.

**Comment by czlee** [comment]
I've kept it on a separate branch (`feature/#416-trusty-postgres`), building now, I'd want more than just the tests to pass before bumping to PostgreSQL 9.6 though—I think we need to each be running PostgreSQL 9.6 in our development environments (and Python 3.6 for that matter) for us to migrate our primary support to those versions, and also what I said earlier about the upgrade path for existing installations.

**Comment by philipbelesky** [comment]
It's nontrivial to upgrade between versions but I don't think that really affects any of our users, particularly on heroku. Is the concern users with local installs?

FWIW I've been running 9.6 for a couple of weeks without problems.

**Comment by czlee** [comment]
No, it's actually just our pipeline (the sites we manage). So if you think you've got that under control, it's fine with me. We'll have to keep support for PostgreSQL 9.5/Python 3.5 for Windows (win-psycopg2 only supports one version of psql per version of Python), but I don't think that would be fatal, it only affects installation instructions: our code is unlikely to be compatible with psql 9.6 but not psql 9.5, and it seems as if we're still supporting Python 3.5 in tests.

Would changing the runtime specification break existing Heroku installations, or is Heroku smart enough to figure out what it needs to do? If it's not possible just to upgrade from Tabbycat 1.1 to Tabbycat 1.2 without a nontrivial database migration procedure, we should probably say something about that in release notes/documentation.

(Local installations won't upgrade postgres without the user actually upgrading postgres, and at that point they probably know what they're doing, so I'm less concerned about that, though maybe it would be good to include a note in documentation there as well.)

Tests passed: https://travis-ci.org/czlee/tabbycat/jobs/194708029

I'm happy to merge it into develop, but I'd like it if I had a chance to upgrade my development environments and run them for a couple of weeks before pushing out a release that bumps to these versions. Is that okay?

**Comment by philipbelesky** [comment]
I don't think it affects heroku in the sense that heroku doesn't upgrade databases between versions; it just changes the default version that new databases are created as. 

So yea outside of someone needing to update a local install (and even then they can carry on using 9.5 without issue) I don't think there is really a need to worry about migration paths. 

Merging it in sounds good. 'A couple of weeks' is probably a good timeframe for the Foldex release so that sounds like it should all work out?

**Comment by czlee** [comment]
Checked Postgres 9.6 on Ubuntu 16.04. As mentioned in #415 we can't do 64-bit Windows yet (and I can't be bothered testing 32-bit), so Windows will have to wait until mid-March. I might try the Windows Bash Subsystem, but given that that's in beta I don't think that should be our primary method for Windows.

**Comment by czlee** [comment]
Added advice for Windows in e955eec13c222418d0cdff8afefa58ad92757297, done as far as Foldex is concerned, successor issue is #423.
