### ISSUE TITLE
Rendering numbers as floats to the ballot fields caused the front-end validator to fail

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#418]
So, the scenario is using standard Australs rules for speaker ranges. After entering initial data and returning to the same ballot I could not then save changes to that ballot as the front end validator was saying `77.0 must be a multiple of 1`. This failed because the `<input>` element has rounded floats; ie the score's value was 77.0; it's min 68.0; it's max 82.0.

I'm not sure why the front end validator has just now started having the issue. The behaviour doesn't seem to exist in `master`. Possibly a bug fix update in the jquery plugin or something.

The solution was to, when constructed the form, to ensure only `Ints` are set for value/min/max/step on the input element when the Step setting is itself able to translate into an Int; ie 1.0/2.0/3.0 etc. As a result we now also get nice fully rounded numbers in the form. 

Ping @czlee it's probably worth reviewing the changes at your leisure to ensure I haven't done something stupid :p

**Comment by czlee** [comment]
Oh, weird, okay, I couldn't reproduce it then I did `npm install` to upgrade and now I see it.

**Comment by philipbelesky** [comment]
Yea such is the `npm` life. We should probably shift to freezing the npm versions precisely rather than allowing minor bumps; the dependency tree there is huge.

**Comment by czlee** [comment]
This bit us with pip as well (recall #397). Do you think we should just freeze all versions at the patch level, and update them once per Tabbycat patch release? With our current system for all we know, regressions in packages could be hitting our users before we find out and get to do anything about it?

**Comment by philipbelesky** [comment]
Yea, at the point we've come across more bugs than fixes from allowing free patch upgrades we should freeze both of them. I'll make a note to bump everything to the latest for 1.2 and then freeze (assuming it works)

**Comment by czlee** [comment]
We could just start this practice from 1.1.8?

**Comment by philipbelesky** [comment]
Hmm, I think it might end up being a relatively major change as I will probably end up bumping quite a few of the npm dependencies (either minor or patch versions). Part of the problem seems to be node packages move fast on minor version such that older ones don't get too many patches.
