### ISSUE TITLE
Investigate how to allow for passwords to be reset

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#426]
I wonder how many people just totally forget their login and have to abandon an instance. I'm sure there are some packages than enable an email-to-reset password function. Although this would require us compulsorily collecting admin emails (maybe not a bad idea) and handling cases when Sendgrid or some other mail service is not provisioned.

**Comment by czlee** [comment]
Further packages shouldn't be necessary, this is quite sensibly built into Django's authentication app (which we already use): https://docs.djangoproject.com/en/1.10/topics/auth/default/#django.contrib.auth.views.password_reset

Note this part:
>If the email address provided does not exist in the system, this view won’t send an email, but the user won’t receive any error message either. This prevents information leaking to potential attackers. If you want to provide an error message in this case, you can subclass `PasswordResetForm` and use the `password_reset_form` argument.

I think we should abide by this (_i.e._ I think we should not subclass `PasswordResetForm`), but still not make admin e-mails mandatory; instead we should just collect the information when they create the first superuser account and warn them that if they don't provide an e-mail address, they won't be able to regain access to the system if they lock themselves out. (Maybe we'd do this with an alert, to emphasise that it's strongly recommended.) This wouldn't require any model changes—the Django `User` model has an `email` field.

By the way, if someone does forget their login, their instance isn't actually gone forever, right? They can just make a new superuser and use that to log in. The catch is that they'll need to have Heroku CLI installed.

On a tangential note, there's also a `password_change` view that we should probably make available, some day.

**Comment by czlee** [comment]
Okay, so it's pretty easy. All we have to do is include all the templates rather than hand-picking two. I've done so in e8bf693. I think everything's all built in, as in, to get something minimally viable, we don't need to do anything more.

That said, the templates it currently goes to are the ones provided by Jet, so we might want to replace them before merging this back into develop. It's not dangerous, but there is a link to the "Django admin" home page in the top left of the template, which could be confusing for non-superusers, I guess. (If you're not a superuser, clicking it takes you to the login page, since you wouldn't have the relevant permissions.)

**Comment by philipbelesky** [comment]
Where is this link to the django admin area? I've gone through the reset process and modified the templates slightly, but wasn't able to see it

**Comment by czlee** [comment]
Oh, the templates I added override it. If you want to see the Django admin link, delete (or rename) all of the password reset templates, then try again.

**Comment by czlee** [comment]
(Or just check out commit e8bf693.)

**Comment by czlee** [comment]
I merged this into develop, the reset part's certainly done, all that's left now is to find a neat place for the link for logged-in users to change their password. Remember there's both the admin and assistant accounts to do.

**Comment by philipbelesky** [comment]
@czlee I figure the best place to put it is in the site index, as that is consistent between admin and assistant users. I've added the html and chosen an icon in 087e6a227078b63ca219466460a29a5a62d36188 but couldn't (from my brief research) figure out what link to use — could you add that in?

**Comment by czlee** [comment]
Done 😄
