### ISSUE TITLE
Update dynamic preferences to 1.0

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#434]
Just a quick mental note that upgrading to 1.0 has some breaking changes, such as on `UserPreferenceModel` and to remember to actually do this upgrade.

**Comment by czlee** [comment]
I see. Just adding links for future reference:
https://github.com/EliotBerriot/django-dynamic-preferences/issues/33
https://django-dynamic-preferences.readthedocs.io/en/latest/upgrade.html
