### ISSUE TITLE
Show error page where current round not set

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#436]
We've hit this several times before (#212, a901dd87adb48693ef6c3d40dce8c5c32179c1fb, 34c9200c949e64559a0d3f2e3a7e780a8079db8c), but we're still getting sites without rounds currently set. Perhaps we should just check on every request, even at the cost of the introduced overhead.

Rough idea:

1. Override `dispatch()` in `TournamentMixin`. Get it to check the tournament's current round, and to return a standard view upon error.
2. The standard view would be akin to 404/500 error pages: It would _not_ be a redirect, it would just replace the view that is actually meant to be shown. It would be as plain as possible, and would just carry some simple instructions for how to fix the problem, including (e.g.) a link to the change tournament page for that instance in Jet.

Also, we should probably add a warning to the change tournament page in Jet to warn people that setting current round to None will crash the site (similar to our current debate-team warnings).

- [x] Add general error page
- ~Add warnings to Jet~

**Comment by philipbelesky** [comment]
Questions about the view being shown:

- Is this for both the public and admins? 
- Aren't we likely to have a higher chance of success if we allow users to fix the problem in-situ rather than bouncing them off to jet — ie provide a list of rounds in a simple form and allow people to set it there.

**Comment by czlee** [comment]
1. I'd say both. I'd avoid the assumption that an admin will notice the problem—they might, for example, unset the current round then log out. So the message for the public would be to notify tournament staff.

2. Maybe. The main problem with this is just implementation: I think this should be akin to an error page, which means it is shown _at_ the URL that fails, not a redirect. In order for a form to work, we'd have to render the form in `TournamentMixin` and have it returned in place of the normal view for that URL. I'm sure this is possible, but it'd get messy and confusing, both to code, and for the user: you don't really expect an error page to be interactive.

    Of course, we could instead make it a redirect to a standard for that allows you to select the current round. But I'm not a fan of that approach—I think we should present as an error, like a clear abnormality; I think a redirect makes it look like a standard error (akin to "not being logged in").

    A third option would be to do both: give a standard error page that is _not_ interactive, but rather than sending them to Jet, bounce them to a form that just does this one thing. This would be less error-prone than Jet, and might have its own uses, too: arguably, it would just be useful to have a place where admins can _always_ access to set the current round of the tournament, without risking changing anything else. This page could also explain properly what the current round is used for. Thoughts on this last idea?

3. As an aside: If we implement this, I'd also remove the current mechanism that automatically sets the current round in the tournament overview page. Thoughts?

**Comment by philipbelesky** [comment]
1. Perhaps; I'd have thought in most cases deleting or unsetting a round is a precursor to some other action such that there is a slim chance that they would then not immediately notice the page. It's also a bit odd to have a page saying 'tell the tab director to do X'. But I don't mind adding it, or just a generic error page, in conjunction with (2)
2.  
    1. What's the reason for wanting to show it at the exact URL? Also I think the reason you don't expect and error page to be interactive is because error pages are a last resort — the system can't intervene to solve the problem. If it is a known issue then it should reveal to the users the actions that can fix them as directly and simply as possible.
    2. I don't see the problem with using the standard admin page layout with a big red angry error message; but if we do want to raise the severity I could live with a more stripped down (but not bare) error style page. The issue of 'error fixability' and 'error severity appearance' seem like they can be both done independently.
    3. I'd rather just bounce them to this form in the first place along with any error message, as in (2). If the round-set function needs to be a normally-accessible page we can make the error warnings configurable. That said I'm not sure what purpose this new page would have in most cases — I can't think of the last time I've ever needed to go back a round in an actual tournament and I'd worry about it confusing users who wouldn't have gone into the database area and set the round in the first place.

3. Makes sense

**Comment by czlee** [comment]
Okay, maybe to make things a bit more precise: would you be in favor of modelling this after user authentication, almost exactly? i.e.: if there's no current round (and there is an admin session active), the page redirects to the "set current round" page, then once that's done, it redirects to the original page the user was trying to view (not the home/overview page)?

I could work with that, since I can how appropriate messages would be added to that to make it clear what's happening, similarly to the login sequence.

**Comment by philipbelesky** [comment]
Sure, that sounds good.

**Comment by czlee** [comment]
Done! @philipbelesky, would you please review this before we merge it in?

**Comment by czlee** [comment]
Except I forgot to remove the old workaround, whoops. Will do that later.

**Comment by czlee** [comment]
Also, as it stands there's no way to access this page via a link—only by either typing in the URL (which works fine) or by being redirected when current round is `None`. We could potentially put it under "Setup" in the admin nav if you think it'd be useful?

**Comment by czlee** [comment]
Last piece put in place in d2875bc68303b2e3f6abefbab12f734f7bbe492a.
