### ISSUE TITLE
Internal server error report - failure to generate draw

### ISSUE THREAD

**Issue by actdu** [czlee/tabbycat#437]
I hit an internal server error while trying to load this URL:
https://actdu2016.herokuapp.com/senior2017/admin/draw/round/1/

Please describe what you were doing when the error happened, along with any other useful information:
Probably deleting a team and creating a new team caused the bug. From the action log, it would be related to the most recent three actions: "edited teams availability"
<img width="994" alt="screen shot 2017-03-02 at 1 53 02 pm" src="https://cloud.githubusercontent.com/assets/26129523/23491154/9c61f510-ff50-11e6-8210-1db96d113cba.png">

**Comment by czlee** [comment]
Ah, did you delete the team in question in the Edit Database area? That might've done it. All you need to do is somehow resolve the debate that only has one team (the one with Orana 1 in it, or debate ID 795), either by adding another team to it, or by deleting the debate. If you've recreated the team, you'll probably want to do the former, but you'll have lost their speaker scores unrecoverably (if the result had already been entered). If you meant to permanently delete the team, you'll want to do the latter, but that should also mean losing all other data associated with the debate.

(Team availability is independent of that - changing team availability doesn't add/delete teams, just marks them active/inactive.)
