### ISSUE TITLE
Add support for speaker categories

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#443]
Basically ESL/EFL/novice categories for speakers, independently of team. In my imagination they'd function basically in the same way as break categories, except that they'd do much less, namely, just act as a filter for the speaker tab. This would then replace the existing pro/novice designation, if `Speaker.novice` isn't used for anything else.

If we wanted to be really cool, we could add the ability to autogenerate team eligibility from speaker eligibility. I'd suggest that this not be automatic though, as in, a human should have to click a button to start that process, so that team eligibility can be overridden where necessary.

**Comment by philipbelesky** [comment]
Just a quick note I might implement a basic version of this for this year's Australs, although in a manner that extends/replicates how we handle the novice category. A more abstracted version can be put back on the more long term todo list.

**Comment by czlee** [comment]
Sure, sounds good.

**Comment by philipbelesky** [comment]
Ok, this has been merged in. Should we keep this issue around for if/when we properly abstract these types of categories; or close it for now?

**Comment by czlee** [comment]
Let's keep it open. If it's an important feature, it shouldn't be too hard. The only question is how to deal with pros: currently this is the absence of a novice status, not the presence of a pro one, right? Would we rather have the system generate standings for "speakers not in X category", or would we rather just get into the habit of creating a pro category and making people check it explicitly?

**Comment by philipbelesky** [comment]
Um that's probably better a question better broached when/if these categories are more broadly abstracted. I wouldn't mind in general switching `novice` to be `pro` so that the special versions of the speaker tab all use the same format of "extra_field is True" but have a slightly-different query format for each page isn't really a hassle or much code bloat.

**Comment by czlee** [comment]
I notice that the current Boolean fields are on `Person`, not `Speaker`. Are these statuses meant to apply equally to adjudicators, or are they just for speaker rankings?

Obviously we could define them on adjudicators, but they should only be defined in `Person` if we expect to manage them on speakers and adjudicators in very similar ways.

**Comment by czlee** [comment]
@philipbelesky I've done an initial implementation on the `feature/#443-speaker-categories` branch. It includes almost-full migrations, including to pro status (as in it creates a pro category and assigns, so migrations-wise the Australs site should be upgradeable, though I don't necessarily recommend actually doing it with the branch in its current state. The one migrations I haven't included is the new "show speaker categories" setting, so that'll have to be re-enabled on any site that upgrades.

To avoid data loss I've left the old novice/esl/efl fields (of Person) in, for now.

Things that you might be interested in improving (if not, no problem):
- Merging [edit_eligibility.html](https://github.com/czlee/tabbycat/blob/be6c4d20435a3d4b5078f65aaf25d033781fa044/tabbycat/breakqual/templates/edit_eligibility.html) and [edit_speaker_eligibility.html](https://github.com/czlee/tabbycat/blob/be6c4d20435a3d4b5078f65aaf25d033781fa044/tabbycat/participants/templates/edit_speaker_eligibility.html) into a single template, since they're very similar.
- Finding a sensible place for the link to the new edit speaker eligibility page (see: [urls_admin.py](https://github.com/czlee/tabbycat/blob/be6c4d20435a3d4b5078f65aaf25d033781fa044/tabbycat/participants/urls_admin.py#L12-L14))
- A bunch of nav highlights are now broken

I started on the assumption that the `novice` field should also be elided into the new speaker category system, but I've now noticed two things:
- `novice` is also used in the diversity overview
- We use a glyphicon for novices
- `novice` was also used for adjudicators, but quite differently; perhaps we should move the novice field to `Adjudicator`.

Not sure if these are reasons to roll back the abolition of the `novice` field, and treat novice as a special case (so that speaker categories would be mainly ESL/EFL in use cases currently known to us). I'm probably inclined not to, though, since the fundamental logic in treatment is the same as for ESL/EFL, so I'd rather deal with special treatment only at the higher layers if necessary (just have a convention that the novice category should have the slug `"novice"`). Any thoughts on this?

**Comment by czlee** [comment]
Also, while I remember, we'll have to think of how to get the importer to deal with this, I guess.

**Comment by czlee** [comment]
Plans for remaining mundane tasks:
- [ ] Merge edit_eligibility.html and edit_speaker_eligibility.html into a single template
- [ ] Move `novice` field to `Adjudicator`, and rename it `trainee` (verbose name "always trainee")

We probably don't _need_ to get the importer to deal with it, now that I think about, though it'd be nice for the command-line importer.

**Comment by czlee** [comment]
Okay, I've taken it all the way through now, including migrations that remove the old `novice/esl/efl` fields. I did a test run on a local copy of the Australs 2017 database and the migrations all work fine (as in all data is retained, including limits), so hopefully upgrading the Australs 2017 site will be seamless, but of course take a backup first just in case.
