### ISSUE TITLE
Improve how Release Motions/Draw relate to their public settings

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#444]
So it seems that the Release Motions and Release Draw probably don't make much sense unless you are also aware of the corresponding settings that enable their public pages. There should probably be a couple of pieces of conditional logic that actively grey them out when those settings are not enabled and explain what the setting is and where to find it.

**Comment by czlee** [comment]
Counter-intuitively, they actually do matter in other scenarios: If you're using e-ballots or e-feedback, they control whether the options for this round are available, to avoid e-ballots and e-feedback being a backdoor to unreleased information. So this probably gives us even more explanation to do…

**Comment by philipbelesky** [comment]
Ah yes, I had totally forgotten about those options. Which makes the logic more complex, but I think accounting for those options would also help demystify them somewhat.

**Comment by czlee** [comment]
Yeah, definitely agree that they could be less cryptic, lol.
