### ISSUE TITLE
Missing speaker score by adj can cause results form to crash

### ISSUE THREAD

**Issue by Sarangan95** [czlee/tabbycat#447]
I hit an internal server error while trying to load this URL:
https://nlsd2017.herokuapp.com/nlsd2017/admin/results/ballots/1/edit/

Please describe what you were doing when the error happened, along with any other useful information:

I am not able to edit a result in a previous round. The error message is - 'Internal Server Error (500)' 
How do I resolve this? Any help will be appreciated

**Comment by czlee** [comment]
I'm not sure what the root cause is, but it looks like there's a missing score that's assumed to be present. Can you go into the Edit Database area, and check that the SpeakerScoreByAdj objects associated with the BallotSubmission whose `id = 1` form a complete set of speaker scores?

I've Facebook-messaged you debugging information specific to your tournament.

Error information:

> TypeError at /nlsd2017/admin/results/ballots/11/edit/
> 
> float() argument must be a string or a number, not 'NoneType'
> 
> Request Method:	GET
> Request URL:	https://nlsd2017.herokuapp.com/nlsd2017/admin/results/ballots/11/edit/
> Django Version:	1.10.5
> Exception Type:	TypeError
> Exception Value:	float() argument must be a string or a number, not 'NoneType'
> Exception Location:	/app/tabbycat/results/forms.py in coerce_for_ui, line 89

```
/app/tabbycat/results/forms.py in __init__ (line 162)
        self.initial = self._initial_data()
/app/tabbycat/results/forms.py in _initial_data (line 314)
                    initial[self._fieldname_score(adj, side, pos)] = coerce_for_ui(score)
/app/tabbycat/results/forms.py in coerce_for_ui (line 89)
            return float(x)
```

**Comment by czlee** [comment]
5af9b31 fixes the crash, but doesn't really resolve the underlying problem: that it's possible to edit adjudicators after a result is entered, and the act of doing so deletes results for that adjudicator. For that, see #403.
