### ISSUE TITLE
Move Randomised URL section to Setup

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#451]
Random URLs are probably an important enough feature to warrant their own section. Their current location under Feedback is also not particularly intuitive; given they apply to both ballots and feedback.

**Comment by czlee** [comment]
While we're at it, if you ever manage to think of a better name for "randomised URL", I'm definitely down to change it. But I've got nothing.

**Comment by philipbelesky** [comment]
I've used 'private URLs' it the new docs section, we could replace it with that perhaps?

**Comment by philipbelesky** [comment]
Ok, everything is all moved over and I've added pages for printing/emailing the ballot URLs.

**Comment by philipbelesky** [comment]
(feel free to continue the conversation about naming the URLs)

**Comment by czlee** [comment]
"Private URL" could work. Though, some people think (on good grounds) it's a bit of a misnomer, and we should probably make sure whatever we do makes clear to users that it is not a secure solution.
https://softwareengineering.stackexchange.com/questions/325806/are-private-unguessable-urls-equivalent-to-password-based-authentication
I'm still comfortable with "private URL", as long as the degree of (lack of) security is made clear to users.

Another option would be "Individualized URL", though (a) that's a long word and (b) it understates it a bit, technically a URL by ID or even team name could also be considered "individualized".

**Comment by philipbelesky** [comment]
Yea, I think 'private' is the most clean nomenclature to the average user; hopefully the existing documentation/interface text makes it clear what the nature of them being only semi-secure. I'll go through and update the docs/interface text.
