### ISSUE TITLE
Feedback submitted success messages still getting mixed up

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#455]
As has happened before, the alert-success warnings will return "Thank you for submitting on X" when the person had actually submitted on "Y". This seems to happen in high-traffic situations.

**Comment by philipbelesky** [comment]
Currently working solution (at least for Genetta) would be just to remove the part where it names who you submitted feedback upon.

**Comment by philipbelesky** [comment]
So, this might be related to the fact that we track sessions on the cache layer:

    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

We are also using a session storage option that [doesn't write through to the database](https://docs.djangoproject.com/en/1.11/topics/http/sessions/#using-cached-sessions). Switching to the write-through version would also mean logins persist after server restarts (or when memcached is otherwise unavailable) I think.

The other thing is we are redirecting users to the `tournament-public-index` page after they have submitted; which is itself a cached page.

So given how hard this is to replicate (outside of being able to simulate high traffic reliably) I wonder whether its better to remove the identifying information from each message, or to try a fix along the lines of 1) change to db-backed sessions and 2) redirect to a non-cached page after submitting.

**Comment by czlee** [comment]
Oh, that's an interesting diagnosis—I hadn't thought of (2), and I think it's far more likely than (1). If anything you'd expect db-backed sessions to be more prone to this than cache-backed sessions, wouldn't you?

**Comment by philipbelesky** [comment]
We also don't have `MESSAGE_STORAGE` currently set, which [as per this](http://stackoverflow.com/a/32652157) could be part of the issue.

**Comment by philipbelesky** [comment]
Bumping to Havana Brown in the hope that a37360b6ca9faafd0bfb76b3fd9705e16d3ebe1b has fixed it and this can be verified before that is released.

**Comment by philipbelesky** [comment]
Slight update: not sure if this is still happened at Australs although I mentioned it might happen in the briefing, so people may just not be mentioning it. However the messages for user logins did seem to be occasionally get mixed up.

**Comment by philipbelesky** [comment]
Haven't seen reports of this at the last few tournaments, so finger's crossed it's resolved now!
