### ISSUE TITLE
Add presets to tournament wizard

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#460]
Basically just a simple drop down listing the different tournament configurations; or at least the ones that map to established styles. Selected option would then be applied to the tournament post-creation.

**Comment by philipbelesky** [comment]
This has been done when creating new tournaments; doesn't work when importing the demos. The easiest way around this might be to add a second 'step' to the wizard that prompts users to set a configuration (regardless of whether creating a new one or importing a demo). Perhaps this page could also add another simple configuration, such as whether to apply the public information preset and one or two common settings like showing institutions. Thoughts @czlee ?

**Comment by czlee** [comment]
Could also make the create demo tournament page a separate form altogether, with two dropdowns: (1) which preset to apply, (2) which demo tournament to pick? (Not sure, just throwing ideas around.)

**Comment by philipbelesky** [comment]
Hmm, that seems like we would end up with more pages and a more complicated process. Ideally a 'wizard' style setup would have a consistent number of pages/steps. So at the moment that might be:

1. New Tournament page (either configure basic data like name/rounds or import demo data)
2. Configure Tournament page (set format presets; possibly other common settings)

In future, some other steps might be:

- Manually agreeing to license conditions as a step 0?
- Linking to documentation and/ or the support resources as a step 3?

**Comment by czlee** [comment]
More pages? There'd be exactly two pages:

- "Create New Tournament", which creates a new tournament
- "Load Demo Tournament", which loads a demo tournament

That's the same number of pages in total as in a two-step wizard. The difference is that the user only has to go through one of them for any given tournament, which to me sounds like a simpler process, not a more complicated one.

**Comment by philipbelesky** [comment]
Yes, but two distinct pages operating in parallel is probably as complicated as having two distinct pages working in serial :p 

The advantage of having them work in serial would be that there is a single point of entry ('New Tournament' rather than 'New Demo Tournament' and 'New Tournament') and we can use each page to describe the tradeoffs between them. It would be easier to extend with additional steps if needed in future.

**Comment by czlee** [comment]
If you're fairly sure extending this to a multiple-step process is likely to be a good idea in future, this sounds good to me. I'd advocate designing it so that the two aren't "equal" (to avoid the demo button getting in the way of regular users), but I'm sure that can be done in either pattern.
