### ISSUE TITLE
Automatically add created Teams to the open BreakCategory

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#462]
This is just a small quality of life thing, but for things like the liveness calculator to work it currently needs users to have assigned teams to the open break category, which I suspect most users wouldn't do until it is time to actually generate the breaks, so the feature kind of doesn't do much if users don't realise this.

Rather than making eligibility for open breaks be opt-in, it would seem to be more convenient if it were opt-out; ie there was a hook on newly-created `Teams` that automatically assigns them to all `is_general` `BreakCategory`'s (assuming any exist).

**Comment by philipbelesky** [comment]
As a sidenote for the future, I wonder whether its worth extending this to other pieces of data, such as `Tournaments` having automatically added Open Break Categories, and new `Adjudicators` always having an institutional conflict with their own institution (ie things we already account for in the simple importer or wizard).

**Comment by philipbelesky** [comment]
Ok, to continue the discussion on the commit, agree that this should be an implicit behaviour in the importers, but should not happen when adding in the edit database area.

**Comment by czlee** [comment]
Oh, I did a partial implementation on the feature/#462 branch, lmk what you think. The partial implementation pre-selects a "default" of all general categories if, and only if, there's exactly one tournament.

**Comment by philipbelesky** [comment]
Yup, that looks good to merge. Pre-populating when there is only one-tournament and having the visual importer auto-add should cover the use cases I had imagined.
