### ISSUE TITLE
Record page links aren't regenerating when participant tables are re-sorted

### ISSUE THREAD

**Issue by viranweerasekera** [czlee/tabbycat#464]
In the Australs deployment of Havana Brown (1.4.0a), if the user sorts the participants tables (either teams or adjs) in a way that's different from what was initially loaded (ie. In any way other than by name in descending order), links to the team/judge record pages don't update to reflect the new speaker/adj in that table row).

**Comment by philipbelesky** [comment]
Thanks for the bug report! Haven't look into this in detail yet, but I suspect that when Vue reorders the table it changes the content inside an html element, rather than recreating it. The Bootstrap method that calls up the popovers thus remains attached to the original table cell. Probably could fix by manually recalling the popover method whenever a table is sorted.

**Comment by philipbelesky** [comment]
Ok, this might be more tricky than I thought. Notes to self: the Cell component calls in to PopoverMixin to setup the initial content, but that does so by binding a jQuery mouseover/mouselave call, which presumably doesn't get updated when the table is resorted. Either the popover logic needs to remove jquery for this purpose, or it hovers need to check and rebind jquery to the right element each time

**Comment by philipbelesky** [comment]
Sidenote: this also affects the check boxes on the Availability pages. Checking some then sorting the list causes the boxes to uncheck.

**Comment by viranweerasekera** [comment]
It also appears to affect the break check-boxes on the Feedback page (in that checking an adj as breaking, then re-sorting the table will also cause the box to uncheck).

**Comment by philipbelesky** [comment]
Slight update: this has been fixed for the popover and tooltip elements in tables; for the checkboxes I'll need to migrate those using a dedicated Vue component. But this should definitely be in for 1.4 as it has the potential to cause the wrong data to be saved.

**Comment by philipbelesky** [comment]
Turns out this only affected the Feedback overview table and it's checkboxes from what I can tell. Although if anyone sees inconsistent saving behaviour from the checkbox fields this is probably it.
