### ISSUE TITLE
Hungarian allocator assigns best panel to least important rooms

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#471]
So, just playing around with a local copy, but the highest-importance room with a panel has a 3 - 2 - 2, whereas the lowest has a 4 - 4 - 4. This correlates with what we've noticed at Australs.

**Comment by philipbelesky** [comment]
Hmm, so this might not be a bug (I thought it was a change with the sorting of debates) but just me misunderstanding the hungarian allocator. Although if there is a parameter here that is easy to correct for that would be nice, looking a trial run of the Australs R1 draw with the voting score at 0, the panels in the -2 importance rooms seem distinctly stronger than the -1 rooms.

**Comment by czlee** [comment]
I don't know if it helps, but the allocator does something closer to trying to "match" adj rankings to debate importances, than it does allocate the best adjs to the top rooms. But it uses an exponentially weighted penalty, which I would've assumed would have the same effect.

**Comment by czlee** [comment]
I think I might've found it. When the normalized importance is zero, (https://github.com/czlee/tabbycat/blob/08dc077588e0bd18e0d51d26264f5fd5cd80cd75/tabbycat/adjallocation/hungarian.py#L55)[hungarian.py:55] sets it to two. This is probably a hangover from when importance was assumed to be between 1 and 5, so if `debate.importance` was None, that implied that a default important (2 on a 1–5 scale) should be used.
