### ISSUE TITLE
Add infoslide options to the "Motions Display" area

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#476]
Apparently showing motions using Tabbycat is more popular than I thought. As such we should add some basic field for information slides/context. We could almost do it with the current text field and interface, except it doesn't accept line breaks. We should probably just add a second field so we can better visually structure it and include it in the motions info/standings.

**Comment by czlee** [comment]
For context, is this for minor tournaments, major tournaments, or both?

**Comment by philipbelesky** [comment]
Both.

**Comment by philipbelesky** [comment]
Completed in 35cbd0c06c5f7c00c8d15237582ee5dc06c0e487 and earlier
