### ISSUE TITLE
Address dynamic preferences incompatability

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#479]
Tests fail when bumping dynamic preferences from 1.1.1; error message is broadly:

    raise cls.exception('MultiValueSerializer only deserializes strings separated by {0!r}'.format(cls.separator))
    dynamic_preferences.serializers.SerializationError: MultiValueSerializer only deserializes strings separated by '//'

From what I remember of the repo discussions the choice field was refactored from 1.1 -> 1.3. 1.1.1 works for now though so no rush to refactor things.

**Comment by czlee** [comment]
Turns out it wasn't too hard 🙂
