### ISSUE TITLE
Consider/add Tournament Guide docs

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#482]
As part of this years Australs we made a decent amount of notes on the logistics side of tabbing things. While this could just be published elsewhere it would be nice to have as a living document as part of Tabbycat, and potentially to publish it as part of the release. Once release is more immanent we can reconsider based on how edited it is and whether it will be appropriate.

**Comment by philipbelesky** [comment]
Heads up: the first two sections of this are up on the #482 feature branch. While it's a relatively huge page, I've kept it as a single file/section to prevent it from taking over the entire sidebar.

While it would be nice for this to be spun out into a seperate project in the long term, I think there needs to be a degree of buy-in first from other people who can make it more rigorously applicable across other circuits/softwares, and who will expand it out from its current form into a more readable/comprehensive format. In the mean time I think it benefits from the visibility associated with being part of our docs; and will be nice to have it as a 'feature' in 1.4.

Thoughts?

**Comment by czlee** [comment]
Without having looked at it, I'm not sure that there'd be any visibility gain from putting it in Tabbycat docs. Likely, visibility would mostly derive from Facebook sharing, which is independent of location.

That said, we don't really have any stats on who looks at Tabbycat documentation, right?

**Comment by philipbelesky** [comment]
Progress

- [X] Planning/Prep
- [X] Tab Setup
- [ ] Pre-Rounds Setup
- [ ] Managing Rounds
- [X] Breaks and Break Rounds
- [X] Appendix: Briefing Notes
- [ ] A general editing/checking pass by someone not me
