### ISSUE TITLE
Refactor checkbox columns to be sorting-resilient and autosaving

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#497]
- [X] Checkins
- [x] Team's break categories
- [x] Speaker category eligibility

**Comment by philipbelesky** [comment]
@czlee note this has been merged now; I've checked the use cases I could think of but maybe keep an eye out for anything funny when marking adjs as breaking / checkin in availabilities / marking eligibilities.

**Comment by czlee** [comment]
Noted, thanks!
