### ISSUE TITLE
"Break" dropdown link does not work on iOS

### ISSUE THREAD

**Issue by hce95** [czlee/tabbycat#518]
On iOS specifically (not Android) running Chrome and Safari, tapping the top right dropdown button and tapping "Break" yields nothing. The Break submenu does not expand and tapping "Break" either does 0 or opens the motions list.

**Comment by philipbelesky** [comment]
This should be fixed in 796d8ebc413d1b06033a6bb3ddf716020d93d030; however note due to browser caching it may not show up on currently deployed sites for a while.
