### ISSUE TITLE
Warn user if a new adjudicator allocation will lead to a loss of results data

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#82]
For obvious reasons, if you change the adjudicator allocation for a debate that already has a result, data gets lost. While this should never happen in practice, if it does, the user should be warned about the consequences.

Also, ideally the result would be cleanly deleted, i.e. the `BallotSubmission` gets deleted too. At the moment, only `SpeakerScoreByAdj`s get deleted - aggregate scores remain in the database.

**Comment by philipbelesky** [comment]
Superseeded by #258
